// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-22044"] = /*JSON-START*/ {
 "id": "cryptic-22044",
 "number": 22044,
 "series": "cryptic",
 "name": "Cryptic crossword No 22,044",
 "setter": "Janus",
 "date": 973036800000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/cryptic/22044",
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 14,
   "clue": "Skilful strings play in tennis match (first class!) (6-8)",
   "separatorLocations": {
    "-": [
     6
    ]
   },
   "solution": "DOUBLESTOPPING",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 14,
   "clue": "Dejected after plucking birds with one's teeth? (4,2,3,5)",
   "separatorLocations": {
    ",": [
     4,
     6,
     9
    ]
   },
   "solution": "DOWNINTHEMOUTH",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 7,
   "clue": "Ideally perfect note on new piano (7)",
   "separatorLocations": {},
   "solution": "UTOPIAN",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 9,
   "clue": "Gladly permit to remain uncultivated (3,6)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "LIEFALLOW",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 8,
   "clue": "Oliver, for example, getting Ruth to relent (4,4)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "SHOWPITY",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 6,
   "clue": "State alternative to Ronay (6)",
   "separatorLocations": {},
   "solution": "OREGON",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 5,
   "clue": "Tree with flat surface (5)",
   "separatorLocations": {},
   "solution": "PLANE",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 7,
   "clue": "Boy taking novice a flower (7)",
   "separatorLocations": {},
   "solution": "NIGELLA",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 1
   },
   "length": 14,
   "clue": "Its report should stimulate athletic progress (8,6)",
   "separatorLocations": {
    ",": [
     8
    ]
   },
   "solution": "STARTINGPISTOL",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 9,
   "clue": "Unbroken part is healthy (9)",
   "separatorLocations": {},
   "solution": "WHOLESOME",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 2
   },
   "length": 5,
   "clue": "Try to acquire outward skill in slang (5)",
   "separatorLocations": {},
   "solution": "ARGOT",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 5,
   "clue": "Excerpt from Nazi bible put back in place (5)",
   "separatorLocations": {},
   "solution": "IBIZA",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 4
   },
   "length": 9,
   "clue": "Appropriate length in a driving mechanism (9)",
   "separatorLocations": {},
   "solution": "PROPELLER",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 8,
   "clue": "Not returning to Italy, perhaps, for key (8)",
   "separatorLocations": {},
   "solution": "TONALITY",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 6
   },
   "length": 6,
   "clue": "Expedition to see sporting body in foreign attire (6)",
   "separatorLocations": {},
   "solution": "SAFARI",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 6
   },
   "length": 9,
   "clue": "Citadel producing a harvest on poor soil (9)",
   "separatorLocations": {},
   "solution": "ACROPOLIS",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 7
   },
   "length": 8,
   "clue": "He hopes to make a profit from vines replanted on hill (8)",
   "separatorLocations": {},
   "solution": "INVESTOR",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 6,
   "clue": "Makes financial provision on getting bad news about party (6)",
   "separatorLocations": {},
   "solution": "ENDOWS",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 8
   },
   "length": 7,
   "clue": "One who straightens furniture (7)",
   "separatorLocations": {},
   "solution": "DRESSER",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 8
   },
   "length": 8,
   "clue": "Unusually daring, if demeaning (5,3)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "INFRADIG",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 8
   },
   "length": 7,
   "clue": "Hollow tear produced by certain flies (7)",
   "separatorLocations": {},
   "solution": "DIPTERA",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 9
   },
   "length": 6,
   "clue": "Object when time signal is put out for birds (6)",
   "separatorLocations": {},
   "solution": "PIPITS",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 9,
   "clue": "Labourer having the power to act (9)",
   "separatorLocations": {},
   "solution": "OPERATIVE",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 10
   },
   "length": 5,
   "clue": "Confound with a blow (5)",
   "separatorLocations": {},
   "solution": "ABASH",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 10
   },
   "length": 5,
   "clue": "Is to go back for a drink (5)",
   "separatorLocations": {},
   "solution": "PEPSI",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 5,
   "clue": "Girl bringing back something worth having (5)",
   "separatorLocations": {},
   "solution": "TESSA",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 12
   },
   "length": 9,
   "clue": "Let client exercise rational powers (9)",
   "separatorLocations": {},
   "solution": "INTELLECT",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 14
   },
   "length": 14,
   "clue": "Cart-horse conducted to stable in theatre (9,5)",
   "separatorLocations": {
    ",": [
     9
    ]
   },
   "solution": "ORCHESTRASTALL",
   "annotation": null
  }
 ]
} /*JSON-END*/;
