// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-27991"] = /*JSON-START*/ {
 "id": "cryptic-27991",
 "number": 27991,
 "series": "cryptic",
 "name": "Cryptic crossword No 27,991",
 "setter": "Brummie",
 "date": 1574985600000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/cryptic/27991",
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 0
   },
   "length": 9,
   "clue": "National park players would tread them, if river were relocated (3,6)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "THEBROADS",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 0
   },
   "length": 5,
   "clue": "More straight trousers lost — SOS sent out (5)",
   "separatorLocations": {},
   "solution": "TRUER",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 0
   },
   "length": 7,
   "clue": "Transport energy proposal (7)",
   "separatorLocations": {},
   "solution": "EMOTION",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 0
   },
   "length": 5,
   "clue": "Dicky's a mess? Do this! (5)",
   "separatorLocations": {},
   "solution": "RETIE",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 0
   },
   "length": 7,
   "clue": " Regulation pro ground that accommodates would-be high flyers (7,6)",
   "group": [
    "4-down",
    "12-across"
   ],
   "separatorLocations": {
    ",": [
     7
    ]
   },
   "solution": "AIRPORT",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 0
   },
   "length": 9,
   "clue": "Aspen, say, forming border round rambling rose? (3,6)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "SKIRESORT",
   "annotation": null
  },
  {
   "id": "6-across",
   "number": 6,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 0
   },
   "length": 4,
   "clue": "Hoax brought to a satisfactory ending (4)",
   "separatorLocations": {},
   "solution": "CODA",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 0
   },
   "length": 7,
   "clue": "Diminutive canine surgical scraping instrument (7)",
   "separatorLocations": {},
   "solution": "CURETTE",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 0
   },
   "length": 9,
   "clue": "Death shift (9)",
   "separatorLocations": {},
   "solution": "DEPARTURE",
   "annotation": null
  },
  {
   "id": "8-across",
   "number": 8,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 8,
   "clue": "Train someone who'd like to make it big in the US, too? (8)",
   "separatorLocations": {},
   "solution": "EUROSTAR",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 2
   },
   "length": 6,
   "clue": "Italian carrying back sound content to inflict an invasion (6)",
   "separatorLocations": {},
   "solution": "IRRUPT",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 6,
   "clue": "Tom's drive to find a temporary partner? (6)",
   "separatorLocations": {},
   "solution": "CRUISE",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 4
   },
   "length": 8,
   "clue": "Against entering rocky route on approach (8)",
   "separatorLocations": {},
   "solution": "OVERTURE",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 6,
   "clue": "See 4",
   "group": [
    "4-down",
    "12-across"
   ],
   "separatorLocations": {
    ",": []
   },
   "solution": "LOUNGE",
   "annotation": null
  },
  {
   "id": "13-down",
   "number": 13,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 6
   },
   "length": 9,
   "clue": "'Ohio Dylan' playing 'Tripping'? (2,7)",
   "separatorLocations": {
    ",": [
     2
    ]
   },
   "solution": "ONHOLIDAY",
   "annotation": null
  },
  {
   "id": "14-down",
   "number": 14,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 6
   },
   "length": 9,
   "clue": "Deployed falsely, perhaps, by a woman (9)",
   "separatorLocations": {},
   "solution": "EYELASHES",
   "annotation": null
  },
  {
   "id": "15-across",
   "number": 15,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 6
   },
   "length": 8,
   "clue": "Excessively under guidance, finished carrying a gun (6,2)",
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "TOOLEDUP",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 8,
   "clue": "Go from first to second to suspend energy on entering knockout competition? (6,2)",
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "CHANGEUP",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 8
   },
   "length": 7,
   "clue": "Orphan Annie denies houses given unnecessary protection (7)",
   "separatorLocations": {},
   "solution": "NANNIED",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 8
   },
   "length": 7,
   "clue": "Pounds added to independent working payment (7)",
   "separatorLocations": {},
   "solution": "PENSION",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 8
   },
   "length": 6,
   "clue": "Token party nominees? (6)",
   "separatorLocations": {},
   "solution": "TICKET",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 8
   },
   "length": 7,
   "clue": "Choir managed to hold repeated note for so long (7)",
   "separatorLocations": {},
   "solution": "CHEERIO",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 8,
   "clue": "Factory involved in a type of banana (8)",
   "separatorLocations": {},
   "solution": "PLANTAIN",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 10
   },
   "length": 6,
   "clue": "Union member's smear reported (6)",
   "separatorLocations": {},
   "solution": "GREECE",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 10
   },
   "length": 5,
   "clue": "In vogue, stalwart chat show participant? (5)",
   "separatorLocations": {},
   "solution": "GUEST",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 10
   },
   "length": 5,
   "clue": "Rail about garden implement (5)",
   "separatorLocations": {},
   "solution": "CRAKE",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 6,
   "clue": "Rummy party backed by attractive type (6)",
   "separatorLocations": {},
   "solution": "ODDISH",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 12
   },
   "length": 8,
   "clue": "Treat Crimea wounded outside gutted castle (3,5)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "ICECREAM",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 4,
   "clue": "Nymph of the woods evicting river couple (4)",
   "separatorLocations": {},
   "solution": "DYAD",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 14
   },
   "length": 9,
   "clue": "Star needs massage — result of overexposure (9)",
   "separatorLocations": {},
   "solution": "SUNSTROKE",
   "annotation": null
  }
 ]
} /*JSON-END*/;
