// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-24286"] = /*JSON-START*/ {
 "id": "cryptic-24286",
 "number": 24286,
 "series": "cryptic",
 "name": "Cryptic crossword No 24,286",
 "setter": "Paul",
 "date": 1200441600000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/cryptic/24286",
 "entries": [
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 0
   },
   "length": 8,
   "clue": "A nearby resident almost caught old Conservative doing u-turn, the rotter! (4-4)",
   "separatorLocations": {
    "-": [
     4
    ]
   },
   "solution": "COCACOLA",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 0
   },
   "length": 4,
   "clue": "See 20 across",
   "group": [
    "20-across",
    "18-down",
    "2-down"
   ],
   "separatorLocations": {},
   "solution": "FELT",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 0
   },
   "length": 6,
   "clue": "Silence understood to mean trouble (6)",
   "separatorLocations": {},
   "solution": "SHTOOK",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 0
   },
   "length": 7,
   "clue": "Times when one died entering brawls (7)",
   "separatorLocations": {},
   "solution": "FRIDAYS",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 0
   },
   "length": 8,
   "clue": "A fresh river mouth (8)",
   "separatorLocations": {},
   "solution": "APERTURE",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 0
   },
   "length": 10,
   "clue": "Girl turning up with blokes in street given grief (10)",
   "separatorLocations": {},
   "solution": "HARASSMENT",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 0
   },
   "length": 6,
   "clue": "Posh wife embraced by little Dickensian, as was Jeffrey Bernard (6)",
   "separatorLocations": {},
   "solution": "UNWELL",
   "annotation": null
  },
  {
   "id": "8-across",
   "number": 8,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 1
   },
   "length": 8,
   "clue": "See 24 down",
   "group": [
    "24-down",
    "14-across",
    "8-across"
   ],
   "separatorLocations": {},
   "solution": "TOGETHER",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 1
   },
   "length": 5,
   "clue": "Face for the radio might be so? (5)",
   "separatorLocations": {},
   "solution": "PLAIN",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 3
   },
   "length": 4,
   "clue": "Oven meal, but no starter (4)",
   "separatorLocations": {},
   "solution": "OAST",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 3
   },
   "length": 10,
   "clue": "On which the day's business is prepared, or otherwise (5,5)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "ORDERPAPER",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 6,
   "clue": "Pair of kings securing oil producers Russian money (6)",
   "separatorLocations": {},
   "solution": "KOPECK",
   "annotation": null
  },
  {
   "id": "13-down",
   "number": 13,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 5
   },
   "length": 10,
   "clue": "Test foreign students about Nepal regularly, before university (6,4)",
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "ELEVENPLUS",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 5
   },
   "length": 8,
   "clue": "See 24 down",
   "group": [
    "24-down",
    "14-across",
    "8-across"
   ],
   "separatorLocations": {
    ",": [
     8
    ]
   },
   "solution": "YOURSELF",
   "annotation": null
  },
  {
   "id": "15-across",
   "number": 15,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 7
   },
   "length": 7,
   "clue": "Doctor attending more anaemic Sicilians here (7)",
   "separatorLocations": {},
   "solution": "PALERMO",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 7
   },
   "length": 8,
   "clue": "Complaint of middleaged blokes creating an awful stink among unruly gatherings (3,5)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "MANBOOBS",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 7
   },
   "length": 7,
   "clue": "Acknowledgment given when time-piece runs backwards (7)",
   "separatorLocations": {},
   "solution": "RECEIPT",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 7
   },
   "length": 8,
   "clue": "See 20 across",
   "group": [
    "20-across",
    "18-down",
    "2-down"
   ],
   "separatorLocations": {
    ",": [
     8
    ]
   },
   "solution": "PRESENCE",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 8
   },
   "length": 7,
   "clue": "Bird appears creamiest topless (7)",
   "separatorLocations": {},
   "solution": "OSTRICH",
   "annotation": null
  },
  {
   "id": "20-across",
   "number": 20,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 9
   },
   "length": 8,
   "clue": "Influence others to ensure immediate success of liposuction, might you say? (4,4,8,4)",
   "group": [
    "20-across",
    "18-down",
    "2-down"
   ],
   "separatorLocations": {
    ",": [
     4,
     8
    ]
   },
   "solution": "MAKEONES",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 9
   },
   "length": 6,
   "clue": "Piano kept in dry below A sharp (6)",
   "separatorLocations": {},
   "solution": "ABRUPT",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 9
   },
   "length": 6,
   "clue": "Flap wings of thrush going through bumpy ride (6)",
   "separatorLocations": {},
   "solution": "DITHER",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 9
   },
   "length": 6,
   "clue": "One's dotty, seeing neat '60s teenager head over heels in love (6)",
   "separatorLocations": {},
   "solution": "DOMINO",
   "annotation": null
  },
  {
   "id": "23-across",
   "number": 23,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 10,
   "clue": "Line got reversed on page among stuff for cipher (10)",
   "separatorLocations": {},
   "solution": "CRYPTOGRAM",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 11
   },
   "length": 4,
   "clue": "Hot filling seat that's hot! (4)",
   "separatorLocations": {},
   "solution": "PHEW",
   "annotation": null
  },
  {
   "id": "24-down",
   "number": 24,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 11
   },
   "length": 4,
   "clue": "Advice to self-pitying curtains? (4,8,8)",
   "group": [
    "24-down",
    "14-across",
    "8-across"
   ],
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "PULL",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 13
   },
   "length": 5,
   "clue": "In sound, the perfect thing is to test depth (5)",
   "separatorLocations": {},
   "solution": "PLUMB",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 13
   },
   "length": 8,
   "clue": "Struggle against first of chains during escape (8)",
   "separatorLocations": {},
   "solution": "CONFLICT",
   "annotation": null
  }
 ]
} /*JSON-END*/;
