// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-28191"] = /*JSON-START*/ {
 "id": "cryptic-28191",
 "number": 28191,
 "series": "cryptic",
 "name": "Cryptic crossword No 28,191",
 "setter": "Crucible",
 "date": 1595289600000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/cryptic/28191",
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 7,
   "clue": "Ditch exasperated expression Pete's forgotten (7)",
   "separatorLocations": {},
   "solution": "FORSAKE",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 0
   },
   "length": 7,
   "clue": "Like a summer event: begin with song (4-3)",
   "separatorLocations": {
    "-": [
     4
    ]
   },
   "solution": "OPENAIR",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 0
   },
   "length": 5,
   "clue": "Sauce too reduced in South America (5)",
   "separatorLocations": {},
   "solution": "SALSA",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 0
   },
   "length": 7,
   "clue": "Dresses sank unevenly, stuffed with a newspaper (7)",
   "separatorLocations": {},
   "solution": "KAFTANS",
   "annotation": null
  },
  {
   "id": "5-across",
   "number": 5,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 7,
   "clue": "For one, golf trophies make breakfast containers (3,4)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "EGGCUPS",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 0
   },
   "length": 6,
   "clue": "Sanction a run in souped-up car, a small one for racing (2-4)",
   "separatorLocations": {
    "-": [
     2
    ]
   },
   "solution": "GOKART",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 0
   },
   "length": 9,
   "clue": "Halfwit hires crooked bolt cutters? (9)",
   "separatorLocations": {},
   "solution": "CLOTHIERS",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 0
   },
   "length": 7,
   "clue": "Salesman delivers this new model (7)",
   "separatorLocations": {},
   "solution": "PATTERN",
   "annotation": null
  },
  {
   "id": "9-down",
   "number": 9,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 1
   },
   "length": 13,
   "clue": "Lift bottom line up for an LBD, perhaps (8,5)",
   "separatorLocations": {
    ",": [
     8
    ]
   },
   "solution": "COCKTAILDRESS",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 4,
   "clue": "Very inaccurate story about religious coverage (4)",
   "separatorLocations": {},
   "solution": "VEIL",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 2
   },
   "length": 10,
   "clue": "Fellow staggers round firm engaged in making formal wear (5,5)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "FROCKCOATS",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 6,
   "clue": "View missing yellow hat (6)",
   "separatorLocations": {},
   "solution": "PANAMA",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 4
   },
   "length": 8,
   "clue": "Royal couple precede cook carrying one cover for crown (8)",
   "separatorLocations": {},
   "solution": "KERCHIEF",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 9,
   "clue": "Tense French artist shows what's in bottom drawer (9)",
   "separatorLocations": {},
   "solution": "TROUSSEAU",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 6
   },
   "length": 9,
   "clue": "Articles from abroad flank bottom (9)",
   "separatorLocations": {},
   "solution": "UNDERSIDE",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 6
   },
   "length": 5,
   "clue": "Nice bloke's casual wear (5)",
   "separatorLocations": {},
   "solution": "JEANS",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 5,
   "clue": "Inspect stallion approaching filly's rear (5)",
   "separatorLocations": {},
   "solution": "STUDY",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 8
   },
   "length": 7,
   "clue": "Hardy girl acquires old place, revealing chest (7)",
   "separatorLocations": {},
   "solution": "TOPLESS",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 8
   },
   "length": 9,
   "clue": "Perhaps cabaret mystifies housewife (5,4)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "FLOORSHOW",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 8
   },
   "length": 7,
   "clue": "Enjoy longer life not working on river (7)",
   "separatorLocations": {},
   "solution": "OUTWEAR",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 8
   },
   "length": 7,
   "clue": "Protective wear, more than a couple of lines (7)",
   "separatorLocations": {},
   "solution": "OVERALL",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 9
   },
   "length": 6,
   "clue": "Top British runner keeps left (6)",
   "separatorLocations": {},
   "solution": "BLOUSE",
   "annotation": null
  },
  {
   "id": "23-across",
   "number": 23,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 8,
   "clue": "Second pen containing large stone (8)",
   "separatorLocations": {},
   "solution": "SPARKLER",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 10
   },
   "length": 6,
   "clue": "Stole hospital garb idiot sent round (6)",
   "separatorLocations": {},
   "solution": "TIPPET",
   "annotation": null
  },
  {
   "id": "25-down",
   "number": 25,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 10
   },
   "length": 5,
   "clue": " Standard car coat (5)",
   "separatorLocations": {},
   "solution": "PARKA",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 10,
   "clue": "After start of dissent, see clique split and melt away (10)",
   "separatorLocations": {},
   "solution": "DELIQUESCE",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 12
   },
   "length": 4,
   "clue": "Bring up sappers and gunners facing backwards (4)",
   "separatorLocations": {},
   "solution": "REAR",
   "annotation": null
  },
  {
   "id": "28-across",
   "number": 28,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 7,
   "clue": "Like well-balanced school qualification (2-5)",
   "separatorLocations": {
    "-": [
     2
    ]
   },
   "solution": "ASLEVEL",
   "annotation": null
  },
  {
   "id": "29-across",
   "number": 29,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 14
   },
   "length": 7,
   "clue": "Part of old sewer's altered after collapsing (7)",
   "separatorLocations": {},
   "solution": "TREADLE",
   "annotation": null
  }
 ]
} /*JSON-END*/;
