// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-29104"] = /*JSON-START*/ {
 "id": "cryptic-29104",
 "number": 29104,
 "series": "cryptic",
 "name": "Cryptic crossword No 29,104",
 "setter": "Brendan",
 "date": 1687478400000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/cryptic/29104",
 "provenance": {
  "publisher": "Guardian",
  "series": "cryptic",
  "acquiredBy": "tools/fetch_puzzle.py",
  "acquiredOn": "2026-09-17",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 7,
   "clue": "Cascara part-exchanged in South American city (7)",
   "separatorLocations": {},
   "solution": "CARACAS",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 6,
   "clue": "Capacity of youngster to mature (6)",
   "separatorLocations": {},
   "solution": "CUBAGE",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 6,
   "clue": "Country upset about nothing in this part of the world (6)",
   "separatorLocations": {},
   "solution": "REGION",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 10,
   "clue": "Muscat dome rebuilt to required specifications (6-4)",
   "separatorLocations": {
    "-": [
     6
    ]
   },
   "solution": "CUSTOMMADE",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 5,
   "clue": "Positive reaction from Spain that's binding in a part of Egypt (5)",
   "separatorLocations": {},
   "solution": "SINAI",
   "annotation": null
  },
  {
   "id": "5-across",
   "number": 5,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 7,
   "clue": "Is able to divide into sections as French or Italian ballad (7)",
   "separatorLocations": {},
   "solution": "CANZONE",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 9,
   "clue": "States theme, as seen in 14, 20, 22 and elsewhere (9)",
   "separatorLocations": {},
   "solution": "COUNTRIES",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 4,
   "clue": "France's negative statement about European gas (4)",
   "separatorLocations": {},
   "solution": "NEON",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 8,
   "clue": "Something used by cook, as it happens, in modified olio (5,3)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "OLIVEOIL",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 8,
   "clue": "Eastern workers in their part of the world right to use what is not theirs (8)",
   "separatorLocations": {},
   "solution": "EASEMENT",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 5,
   "clue": "Phoney source of fuel in Ireland, you said, is imported (5)",
   "separatorLocations": {},
   "solution": "BOGUS",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 2
   },
   "length": 9,
   "clue": "People badly affected by anxiety changed 5 down (9)",
   "separatorLocations": {},
   "solution": "NEUROTICS",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 10,
   "clue": "Old record is included in contracts for rock cognoscenti? (10)",
   "separatorLocations": {},
   "solution": "GEOLOGISTS",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 4
   },
   "length": 4,
   "clue": "Country finally rejecting any possible reason for complaint (4)",
   "separatorLocations": {},
   "solution": "GERM",
   "annotation": null
  },
  {
   "id": "13-down",
   "number": 13,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 5
   },
   "length": 10,
   "clue": "North of Kent port, letters he has passed across (6,4)",
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "HANDEDOVER",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 4,
    "y": 6
   },
   "length": 11,
   "clue": "Plot Haiti conman concocted (11)",
   "separatorLocations": {},
   "solution": "MACHINATION",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 6
   },
   "length": 9,
   "clue": "Really stupid 5 down in disarray (9)",
   "separatorLocations": {},
   "solution": "CRETINOUS",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 7
   },
   "length": 8,
   "clue": "One kind of African thus followed by another (8)",
   "separatorLocations": {},
   "solution": "SOMALIAN",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 7
   },
   "length": 8,
   "clue": "Architectural style from state on Atlantic (8)",
   "separatorLocations": {},
   "solution": "GEORGIAN",
   "annotation": null
  },
  {
   "id": "18-across",
   "number": 18,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 11,
   "clue": "Reversed so poorly, then drove initially in wrong gear (11)",
   "separatorLocations": {},
   "solution": "OVERDRESSED",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 9
   },
   "length": 6,
   "clue": "German physicist more intelligent than he sounds? (6)",
   "separatorLocations": {},
   "solution": "PLANCK",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 9
   },
   "length": 6,
   "clue": "Book some Italians taking horses across motorway (6)",
   "separatorLocations": {},
   "solution": "ROMANS",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 4,
   "clue": "Some land in Israeli city (4)",
   "separatorLocations": {},
   "solution": "ACRE",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 10
   },
   "length": 10,
   "clue": "Author from Sicily and I fled valley, falling into Italian river (10)",
   "separatorLocations": {},
   "solution": "PIRANDELLO",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 10
   },
   "length": 5,
   "clue": "Greek storyteller making front of audience sit up (5)",
   "separatorLocations": {},
   "solution": "AESOP",
   "annotation": null
  },
  {
   "id": "24-down",
   "number": 24,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 11
   },
   "length": 4,
   "clue": "Someone from an Asian country that is dismissing conclusions (4)",
   "separatorLocations": {},
   "solution": "THAI",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 9,
   "clue": "Edible seaweed from best part of shore I miss in confusion (5,4)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "IRISHMOSS",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 12
   },
   "length": 5,
   "clue": "Relatively older Russian in play against a New York ace (5)",
   "separatorLocations": {},
   "solution": "VANYA",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 7,
   "clue": "Poles embracing orphan, those who look after kids (7)",
   "separatorLocations": {},
   "solution": "NANNIES",
   "annotation": null
  },
  {
   "id": "28-across",
   "number": 28,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 14
   },
   "length": 7,
   "clue": "Rugs from western part of Persia and instruments from Hawaii (7)",
   "separatorLocations": {},
   "solution": "PERUKES",
   "annotation": null
  }
 ]
} /*JSON-END*/;
