// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-28971"] = /*JSON-START*/ {
 "id": "cryptic-28971",
 "number": 28971,
 "series": "cryptic",
 "name": "Cryptic crossword No 28,971",
 "setter": "Brendan",
 "date": 1674086400000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/cryptic/28971",
 "entries": [
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 4,
   "clue": "Booker? With prize ultimately secured, trim one's sails (4)",
   "separatorLocations": {},
   "solution": "REEF",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 6,
   "clue": "Power of the mind seen in part of 24 across (6)",
   "separatorLocations": {},
   "solution": "PINNER",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 10,
   "clue": "If pedant is confused about hard recipe initially, he seeks way to proceed (10)",
   "separatorLocations": {},
   "solution": "PATHFINDER",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 6,
   "clue": "One of six in charge of our land, one a so-called farmer (6)",
   "separatorLocations": {},
   "solution": "GEORGE",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 8,
   "clue": "Restrained, cut line in second edition (8)",
   "separatorLocations": {},
   "solution": "SHACKLED",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 4,
   "clue": "See 7",
   "group": [
    "7-down",
    "6-down"
   ],
   "separatorLocations": {
    ",": []
   },
   "solution": "MOON",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 8,
   "clue": " Imaginary character, one of the first two Wells wrote about (3,2,3,4)",
   "group": [
    "7-down",
    "6-down"
   ],
   "separatorLocations": {
    ",": [
     3,
     5,
     8
    ]
   },
   "solution": "MANINTHE",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 4,
   "clue": "Part of painter's work starts off collection of art treasures (4)",
   "separatorLocations": {},
   "solution": "COAT",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 1
   },
   "length": 9,
   "clue": "Hungarian saint containing the blaze I mishandled (9)",
   "separatorLocations": {},
   "solution": "ELIZABETH",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 1
   },
   "length": 5,
   "clue": "Love label linked with old wine-producing region (5)",
   "separatorLocations": {},
   "solution": "OTAGO",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 3
   },
   "length": 5,
   "clue": "Bird presented in last part of French chapter (5)",
   "separatorLocations": {},
   "solution": "FINCH",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 3
   },
   "length": 9,
   "clue": "With repetition of first part, contrive changes to sentence again (9)",
   "separatorLocations": {},
   "solution": "RECONVICT",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 7,
   "clue": "Large rodent, hard to handle, not keeping up like pig (7)",
   "separatorLocations": {},
   "solution": "PORCINE",
   "annotation": null
  },
  {
   "id": "13-down",
   "number": 13,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 5,
   "clue": "Beat seed (5)",
   "separatorLocations": {},
   "solution": "PULSE",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 5
   },
   "length": 7,
   "clue": "Found pound and ounce, say, in abbreviated dictionary (7)",
   "separatorLocations": {},
   "solution": "LOCATED",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 5
   },
   "length": 10,
   "clue": "Novel form in old verse penned by Conservatives (5,5)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "CRIMESTORY",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 5
   },
   "length": 5,
   "clue": "Letters from London nearly delivered for poet (5)",
   "separatorLocations": {},
   "solution": "DONNE",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 7
   },
   "length": 5,
   "clue": "Endless fortune I had put together, that's clear (5)",
   "separatorLocations": {},
   "solution": "LUCID",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 7
   },
   "length": 8,
   "clue": "Coping partly with limited capital, just under fifteen pounds (8)",
   "separatorLocations": {},
   "solution": "CAPSTONE",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 7
   },
   "length": 3,
   "clue": "Like the Chairman's little work (or books in general, we hear) (3)",
   "separatorLocations": {},
   "solution": "RED",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 7
   },
   "length": 8,
   "clue": "Deity repeatedly upset another — that's very unusual (4,4)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "RARAAVIS",
   "annotation": null
  },
  {
   "id": "20-across",
   "number": 20,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 7
   },
   "length": 5,
   "clue": "Don't allow to leave with odd characters out of discretion (3,2)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "ICEIN",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 9
   },
   "length": 7,
   "clue": "Agent in European capital backed Julian, say (7)",
   "separatorLocations": {},
   "solution": "EMPEROR",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 9
   },
   "length": 7,
   "clue": "Increase organised valet parking in large parts of East End (7)",
   "separatorLocations": {},
   "solution": "ELEVATE",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 9
   },
   "length": 6,
   "clue": "Denouement that's heart-rending? Not half (6)",
   "separatorLocations": {},
   "solution": "ENDING",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 9
   },
   "length": 6,
   "clue": "King or president (6)",
   "separatorLocations": {},
   "solution": "ARTHUR",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 9,
   "clue": "Encountered Oliver's friend in London suburban area (9)",
   "separatorLocations": {},
   "solution": "METROLAND",
   "annotation": null
  },
  {
   "id": "24-down",
   "number": 24,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 4,
   "clue": "Source of inspiration and great power in the writer (4)",
   "separatorLocations": {},
   "solution": "MUSE",
   "annotation": null
  },
  {
   "id": "25-down",
   "number": 25,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 11
   },
   "length": 4,
   "clue": " Old author I'd pronounced woke? (4-4)",
   "group": [
    "25-down",
    "27-down"
   ],
   "separatorLocations": {
    "-": [
     4
    ]
   },
   "solution": "OPEN",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 11
   },
   "length": 5,
   "clue": "It's put in the kind of barns churches once found helpful (5)",
   "separatorLocations": {},
   "solution": "TITHE",
   "annotation": null
  },
  {
   "id": "27-down",
   "number": 27,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 11
   },
   "length": 4,
   "clue": "See 25",
   "group": [
    "25-down",
    "27-down"
   ],
   "separatorLocations": {
    "-": []
   },
   "solution": "EYED",
   "annotation": null
  },
  {
   "id": "28-across",
   "number": 28,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 13
   },
   "length": 5,
   "clue": "Become aware of things smelt, heard but not seen (5)",
   "separatorLocations": {},
   "solution": "SENSE",
   "annotation": null
  },
  {
   "id": "29-across",
   "number": 29,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 13
   },
   "length": 9,
   "clue": "Part of bicycle that doesn't make it to 24 across? (5,4)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "INNERTUBE",
   "annotation": null
  }
 ]
} /*JSON-END*/;
