// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-29228"] = /*JSON-START*/ {
 "id": "cryptic-29228",
 "number": 29228,
 "series": "cryptic",
 "name": "Cryptic crossword No 29,228",
 "setter": "Brockwell",
 "date": 1700006400000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/cryptic/29228",
 "provenance": {
  "publisher": "Guardian",
  "series": "cryptic",
  "acquiredBy": "tools/fetch_puzzle.py",
  "acquiredOn": "2026-09-17",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 0
   },
   "length": 8,
   "clue": "Supporter trouble is on the rise for City (8)",
   "separatorLocations": {},
   "solution": "BRASILIA",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 0
   },
   "length": 4,
   "clue": "Angler pulled up unknown fish (4)",
   "separatorLocations": {},
   "solution": "DORY",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 0
   },
   "length": 6,
   "clue": "Shower in toilet is hot (6)",
   "separatorLocations": {},
   "solution": "LAVISH",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 0
   },
   "length": 8,
   "clue": "Here, the Marseillaise wins award for muppet (8)",
   "clueItalics": [
    [
     10,
     12
    ]
   ],
   "separatorLocations": {},
   "solution": "IMBECILE",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 0
   },
   "length": 10,
   "clue": "Spooner's old woman skewers seafood (5,5)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "STONECRABS",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 0
   },
   "length": 6,
   "clue": "Car sounding like FAB 1? (6)",
   "separatorLocations": {},
   "solution": "BEETLE",
   "annotation": null
  },
  {
   "id": "7-across",
   "number": 7,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 1
   },
   "length": 8,
   "clue": "Second half of Mozart's organ composition is imperious (8)",
   "separatorLocations": {},
   "solution": "ARROGANT",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 1
   },
   "length": 6,
   "clue": "Outspoken Bond intoxicated secretary (6)",
   "separatorLocations": {},
   "solution": "TYPIST",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 1
   },
   "length": 6,
   "clue": "Meghan's opening Spare for old lady (6)",
   "clueItalics": [
    [
     17,
     5
    ]
   ],
   "separatorLocations": {},
   "solution": "MOTHER",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 3
   },
   "length": 4,
   "clue": "Grey area's shrinking (4)",
   "separatorLocations": {},
   "solution": "ASHY",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 3
   },
   "length": 10,
   "clue": "Sculpture of T'ang empire is steep (10)",
   "separatorLocations": {},
   "solution": "IMPREGNATE",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 6,
   "clue": "Jumper cleared ditch in Irish festival (6)",
   "separatorLocations": {},
   "solution": "FLEADH",
   "annotation": null
  },
  {
   "id": "13-down",
   "number": 13,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 5
   },
   "length": 10,
   "clue": "Tackled editor following program on fish (10)",
   "separatorLocations": {},
   "solution": "APPROACHED",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 5
   },
   "length": 8,
   "clue": "Rat Scabies finally backing metal singer (8)",
   "separatorLocations": {},
   "solution": "SNITCHER",
   "annotation": null
  },
  {
   "id": "15-across",
   "number": 15,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 7
   },
   "length": 7,
   "clue": "Spiteful wife's like a viper? (7)",
   "separatorLocations": {},
   "solution": "WASPISH",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 7
   },
   "length": 8,
   "clue": "Kent lose badly in sporting event (8)",
   "separatorLocations": {},
   "solution": "SKELETON",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 7
   },
   "length": 7,
   "clue": "Revolutionary force concerning mardy bum (3,4)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "REDARMY",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 7
   },
   "length": 8,
   "clue": "22dn edges away from Pulp singer (5,3)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "MIDGEURE",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 8
   },
   "length": 6,
   "clue": "Bar pulled up about adult show (6)",
   "separatorLocations": {},
   "solution": "REVEAL",
   "annotation": null
  },
  {
   "id": "20-across",
   "number": 20,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 9
   },
   "length": 8,
   "clue": "24ac loos unfortunately out of use (8)",
   "separatorLocations": {},
   "solution": "OBSOLETE",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 9
   },
   "length": 6,
   "clue": "Drinker is only just fine for start of evening (6)",
   "separatorLocations": {},
   "solution": "BARFLY",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 9
   },
   "length": 6,
   "clue": "Moaned audibly after hip locked up (6)",
   "separatorLocations": {},
   "solution": "INSIDE",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 9
   },
   "length": 6,
   "clue": "Vet dropping soft animal (6)",
   "separatorLocations": {},
   "solution": "INSECT",
   "annotation": null
  },
  {
   "id": "23-across",
   "number": 23,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 10,
   "clue": "Players in cocaine blunder before Queen's (10)",
   "separatorLocations": {},
   "solution": "CRICKETERS",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 11
   },
   "length": 4,
   "clue": "Speculate about the end of Joe Root (4)",
   "separatorLocations": {},
   "solution": "BEET",
   "annotation": null
  },
  {
   "id": "24-down",
   "number": 24,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 11
   },
   "length": 4,
   "clue": "The Two Ronnies initially leaving soup (4)",
   "separatorLocations": {},
   "solution": "BOTH",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 13
   },
   "length": 6,
   "clue": "This is one party game (6)",
   "separatorLocations": {},
   "solution": "CLUEDO",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 13
   },
   "length": 8,
   "clue": "John pinching Nick's lines in chat room (8)",
   "separatorLocations": {},
   "solution": "LOCUTORY",
   "annotation": null
  }
 ]
} /*JSON-END*/;
