// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-29082"] = /*JSON-START*/ {
 "id": "cryptic-29082",
 "number": 29082,
 "series": "cryptic",
 "name": "Cryptic crossword No 29,082",
 "setter": "Anto",
 "date": 1685318400000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/cryptic/29082",
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 7,
   "clue": "Put together advance to break plot (7)",
   "separatorLocations": {},
   "solution": "BLENDED",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 0
   },
   "length": 7,
   "clue": "Clean up the Italian and German and US medical program (7)",
   "separatorLocations": {},
   "solution": "LAUNDER",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 0
   },
   "length": 5,
   "clue": "US city harbours a very quiet waste containment facility (5)",
   "separatorLocations": {},
   "solution": "NAPPY",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 0
   },
   "length": 7,
   "clue": "When it's due, celebrity is about to come out (7)",
   "separatorLocations": {},
   "solution": "EMANATE",
   "annotation": null
  },
  {
   "id": "5-across",
   "number": 5,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 7,
   "clue": "Deceptively rich clothing for one going commando (3,4)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "FURCOAT",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 0
   },
   "length": 6,
   "clue": "In the middle of June, Swiss friends get silly (6)",
   "separatorLocations": {},
   "solution": "UNWISE",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 0
   },
   "length": 9,
   "clue": "Company pitch a line — this may be the result (9)",
   "separatorLocations": {},
   "solution": "COROLLARY",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 0
   },
   "length": 7,
   "clue": "Sums made by relatives embracing a Latin way of working (7)",
   "separatorLocations": {},
   "solution": "AMOUNTS",
   "annotation": null
  },
  {
   "id": "9-down",
   "number": 9,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 1
   },
   "length": 13,
   "clue": "Sad mainland loser? He was very successful at sea (7,6)",
   "separatorLocations": {
    ",": [
     7
    ]
   },
   "solution": "ADMIRALNELSON",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 4,
   "clue": "Sound hesitant in signing for another quiz (4)",
   "separatorLocations": {},
   "solution": "PUMP",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 2
   },
   "length": 10,
   "clue": "Lady who ran distribution for artist  … (4,6)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "ANDYWARHOL",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 4,
   "clue": "…  hired gymnasium, showing stuff that's avant garde (4)",
   "separatorLocations": {},
   "solution": "EDGY",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 4
   },
   "length": 8,
   "clue": "It's offensive ignoring Victor when in a bad way, financially (8)",
   "separatorLocations": {},
   "solution": "INSOLENT",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 9,
   "clue": "Oscar called? Call back — he insists on marching (9)",
   "separatorLocations": {},
   "solution": "ORANGEMAN",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 6
   },
   "length": 9,
   "clue": "Wrong moment to go after rising criminal, admitting nothing (2,7)",
   "separatorLocations": {
    ",": [
     2
    ]
   },
   "solution": "NOCOMMENT",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 6
   },
   "length": 5,
   "clue": "Spoil quiet swamp (5)",
   "separatorLocations": {},
   "solution": "MARSH",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 5,
   "clue": "Knock over playground equipment? Sounds a bit rude (5)",
   "separatorLocations": {},
   "solution": "SAUCY",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 8
   },
   "length": 7,
   "clue": "Varied characters Croat actor played, for example (7)",
   "separatorLocations": {},
   "solution": "ANAGRAM",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 8
   },
   "length": 9,
   "clue": "Your howl about importing nitrogen causes major dispute (6,3)",
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "UNHOLYROW",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 8
   },
   "length": 7,
   "clue": "Legend upset by article describing old empire (7)",
   "separatorLocations": {},
   "solution": "OTTOMAN",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 8
   },
   "length": 7,
   "clue": "Fury when abandoning run leads to power loss (7)",
   "separatorLocations": {},
   "solution": "OUTRAGE",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 9
   },
   "length": 6,
   "clue": "Passion of East Ender trying to sound more tough (6)",
   "separatorLocations": {},
   "solution": "ARDOUR",
   "annotation": null
  },
  {
   "id": "23-across",
   "number": 23,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 8,
   "clue": "Where royalty may get comfort, it's said (8)",
   "separatorLocations": {},
   "solution": "BALMORAL",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 10
   },
   "length": 4,
   "clue": "Finish off job quickly but lose some information (4)",
   "separatorLocations": {},
   "solution": "BYTE",
   "annotation": null
  },
  {
   "id": "24-down",
   "number": 24,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 10
   },
   "length": 5,
   "clue": "Something obscure on book may help to sell it (5)",
   "separatorLocations": {},
   "solution": "BLURB",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 10,
   "clue": "As expected, not betraying class (4,2,4)",
   "separatorLocations": {
    ",": [
     4,
     6
    ]
   },
   "solution": "TRUETOFORM",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 12
   },
   "length": 4,
   "clue": "Urgent approach when evacuating large part of the US (4)",
   "separatorLocations": {},
   "solution": "UTAH",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 7,
   "clue": "Conservative type on warm day regularly becomes passionate (7)",
   "separatorLocations": {},
   "solution": "AMATORY",
   "annotation": null
  },
  {
   "id": "28-across",
   "number": 28,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 14
   },
   "length": 7,
   "clue": "Clever clogs finish up, when permitted (7)",
   "separatorLocations": {},
   "solution": "ENABLED",
   "annotation": null
  }
 ]
} /*JSON-END*/;
