// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-29284"] = /*JSON-START*/ {
 "id": "cryptic-29284",
 "number": 29284,
 "series": "cryptic",
 "name": "Prize crossword No 29,284",
 "setter": "Kite",
 "date": 1705708800000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/prize/29284",
 "entries": [
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 4,
   "clue": "Supports rector going down and stops (4)",
   "separatorLocations": {},
   "solution": "BARS",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 8,
   "clue": "Prisoner associated with tower plot (8)",
   "separatorLocations": {},
   "solution": "CONSPIRE",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 4,
   "clue": "Bishop and President having a tot (4)",
   "separatorLocations": {},
   "solution": "BABE",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 8,
   "clue": "Emperor is in Madrid hosting queen and other rulers (1-7)",
   "separatorLocations": {
    "-": [
     1
    ]
   },
   "solution": "TSQUARES",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 6,
   "clue": "Crosses jaw, that hurts seriously in the face (6)",
   "separatorLocations": {},
   "solution": "YAKOWS",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 10,
   "clue": "Maybe 8 block freezer (4,6)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "CUBENUMBER",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 6,
   "clue": "A rook is not so present around New England (6)",
   "separatorLocations": {},
   "solution": "HONEST",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 4,
   "clue": "Kite maybe caught for English composer (4)",
   "separatorLocations": {},
   "solution": "BYRD",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 1
   },
   "length": 5,
   "clue": "Popular Omani covered up nose (5)",
   "separatorLocations": {},
   "solution": "AROMA",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 1
   },
   "length": 9,
   "clue": "Trim bust in front of Conservative having come to be expected (9)",
   "separatorLocations": {},
   "solution": "STATUTORY",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 3
   },
   "length": 9,
   "clue": "Prolonged emergency - the last part of 6 breaking out (9)",
   "separatorLocations": {},
   "solution": "SOSTENUTO",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 3
   },
   "length": 5,
   "clue": "Repair an electronic item? Correct (5)",
   "separatorLocations": {},
   "solution": "EMEND",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 7,
   "clue": "'More unusual' place of learning associated with queen, earl and king (7)",
   "separatorLocations": {},
   "solution": "UNIQUER",
   "annotation": null
  },
  {
   "id": "13-down",
   "number": 13,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 5,
   "clue": "Posh knight better remove hat (5)",
   "separatorLocations": {},
   "solution": "UNCAP",
   "annotation": null
  },
  {
   "id": "14-down",
   "number": 14,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 5
   },
   "length": 10,
   "clue": "Make clear that engineer can slumber (10)",
   "separatorLocations": {},
   "solution": "UNSCRAMBLE",
   "annotation": null
  },
  {
   "id": "15-across",
   "number": 15,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 5
   },
   "length": 7,
   "clue": "Blind Faith ultimately deliver when following Sabbath (7)",
   "separatorLocations": {},
   "solution": "SHUTTER",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 5
   },
   "length": 5,
   "clue": "Heating enabled with this element (5)",
   "separatorLocations": {},
   "solution": "RADON",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 7
   },
   "length": 5,
   "clue": "It involves mate getting companion to accompany letter (5)",
   "separatorLocations": {},
   "solution": "CHESS",
   "annotation": null
  },
  {
   "id": "18-across",
   "number": 18,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 7
   },
   "length": 3,
   "clue": "Remove short pocket (3)",
   "separatorLocations": {},
   "solution": "SAC",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 7
   },
   "length": 8,
   "clue": "Charlie perhaps with a scruffy yak being ancient Indian polymath (8)",
   "separatorLocations": {},
   "solution": "CHANAKYA",
   "annotation": null
  },
  {
   "id": "20-across",
   "number": 20,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 7
   },
   "length": 5,
   "clue": "Mount of dictator's fed up (5)",
   "separatorLocations": {},
   "solution": "BOARD",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 7
   },
   "length": 8,
   "clue": "Functions as nice Royal Society assembly (3,5)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "ARCSINES",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 9
   },
   "length": 7,
   "clue": "A prior revolutionary queen is like some Ba'athists (3-4)",
   "separatorLocations": {
    "-": [
     3
    ]
   },
   "solution": "PROIRAQ",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 9
   },
   "length": 6,
   "clue": "Writer absorbed by dictionary spread out (6)",
   "separatorLocations": {},
   "solution": "OPENED",
   "annotation": null
  },
  {
   "id": "24-down",
   "number": 24,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 9
   },
   "length": 6,
   "clue": "Repeatedly, starts to quietly walk around former 25 homeland (6)",
   "separatorLocations": {},
   "solution": "QWAQWA",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 9
   },
   "length": 7,
   "clue": "Continental fair refurbished toilet (7)",
   "separatorLocations": {},
   "solution": "AFRICAN",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 5,
   "clue": "A plank across a ship (5)",
   "separatorLocations": {},
   "solution": "ABEAM",
   "annotation": null
  },
  {
   "id": "26-down",
   "number": 26,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 4,
   "clue": "Bohemian, gutless and irritable (4)",
   "separatorLocations": {},
   "solution": "ARSY",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 11
   },
   "length": 9,
   "clue": "One who investigates figures has stamina to be exercised (9)",
   "separatorLocations": {},
   "solution": "ANATOMIST",
   "annotation": null
  },
  {
   "id": "28-down",
   "number": 28,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 11
   },
   "length": 4,
   "clue": "It's an honour to hold doctor's second instrument (4)",
   "separatorLocations": {},
   "solution": "OBOE",
   "annotation": null
  },
  {
   "id": "29-down",
   "number": 29,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 11
   },
   "length": 4,
   "clue": "Slice served up for gin (4)",
   "separatorLocations": {},
   "solution": "TRAP",
   "annotation": null
  },
  {
   "id": "30-across",
   "number": 30,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 13
   },
   "length": 9,
   "clue": "Sneak off but stop around back of castle in the style of William the First (5,4)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "STEALAWAY",
   "annotation": null
  },
  {
   "id": "31-across",
   "number": 31,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 13
   },
   "length": 5,
   "clue": "Macbeth possibly makes comeback in Shakespeare poem (5)",
   "separatorLocations": {},
   "solution": "OPERA",
   "annotation": null
  }
 ]
} /*JSON-END*/;
