// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-29338"] = /*JSON-START*/ {
 "id": "cryptic-29338",
 "number": 29338,
 "series": "cryptic",
 "name": "Prize crossword No 29,338",
 "setter": "Soup",
 "date": 1711152000000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/prize/29338",
 "provenance": {
  "publisher": "Guardian",
  "series": "cryptic",
  "acquiredBy": "tools/fetch_puzzle.py",
  "acquiredOn": "2026-09-17",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 4,
   "clue": "Boom-box (4)",
   "separatorLocations": {},
   "solution": "SPAR",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 6,
   "clue": "Support for offspring? (4,2)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "PROPUP",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 10,
   "clue": "Perhaps Phantom registers first of your core exercises (5-5)",
   "separatorLocations": {
    "-": [
     5
    ]
   },
   "solution": "ROLLSROYCE",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 6,
   "clue": "Gossiped ‘Legend’s touching sailor on couch’ (6)",
   "separatorLocations": {},
   "solution": "GABBED",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 8,
   "clue": "Weakish Shadow roughing up barmen (8)",
   "separatorLocations": {},
   "solution": "PENUMBRA",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 4,
   "clue": "Bat-suit’s symbol (4)",
   "separatorLocations": {},
   "solution": "CLUB",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 8,
   "clue": "Introducing Nitro, psyched up, somewhat willing to take a chance (8)",
   "separatorLocations": {},
   "solution": "SPORTING",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 4,
   "clue": "Apollo oddly pulled back from dirty manoeuvre (4)",
   "separatorLocations": {},
   "solution": "PLOY",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 1
   },
   "length": 9,
   "clue": "Power Electro developed drinking a filter coffee (9)",
   "separatorLocations": {},
   "solution": "PERCOLATE",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 1
   },
   "length": 5,
   "clue": "Flap when lines cover mirror (5)",
   "separatorLocations": {},
   "solution": "LAPEL",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 3
   },
   "length": 5,
   "clue": "Reject or push back outcast (5)",
   "separatorLocations": {},
   "solution": "REPEL",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 3
   },
   "length": 9,
   "clue": "Dog from kids’ TV eats nibbles from baked egg roll, refusing fruit (9)",
   "separatorLocations": {},
   "solution": "BLUEBERRY",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 7,
   "clue": "After repeat performance, Diamond gradually tailed off (7)",
   "separatorLocations": {},
   "solution": "TAPERED",
   "annotation": null
  },
  {
   "id": "13-down",
   "number": 13,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 5,
   "clue": "Pugilist Fury is stony with rage (5)",
   "separatorLocations": {},
   "solution": "TYSON",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 5
   },
   "length": 7,
   "clue": "Shoots one below rib, retires, loses a life (7)",
   "separatorLocations": {},
   "solution": "BIRDIES",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 5
   },
   "length": 10,
   "clue": "Transport aircraft company sent a letter to Spooner (6,4)",
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "ROWINGBOAT",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 5
   },
   "length": 5,
   "clue": "Steal set of bones, but ultimately put it back (5)",
   "separatorLocations": {},
   "solution": "SKULK",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 7
   },
   "length": 5,
   "clue": "Rueful Giant backs up 3 yards (5)",
   "separatorLocations": {},
   "solution": "SORRY",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 7
   },
   "length": 8,
   "clue": "Maybe Comet is thinner, climbing to grip top of net (8)",
   "separatorLocations": {},
   "solution": "REINDEER",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 7
   },
   "length": 3,
   "clue": "Cartoonish Viper’s beginning to kickbox with Athena! (3)",
   "separatorLocations": {},
   "solution": "KAA",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 7
   },
   "length": 8,
   "clue": "Accurately measure board I’m hiding in hollow tree (4,4)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "KEEPTIME",
   "annotation": null
  },
  {
   "id": "20-across",
   "number": 20,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 7
   },
   "length": 5,
   "clue": "Bob, you called for expensive steak (5)",
   "separatorLocations": {},
   "solution": "WAGYU",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 9
   },
   "length": 7,
   "clue": "Introducing AI to disastrous event shows ingenuousness (7)",
   "separatorLocations": {},
   "solution": "NAIVETE",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 9
   },
   "length": 7,
   "clue": "Harry chased Fire (7)",
   "separatorLocations": {},
   "solution": "RANSACK",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 9
   },
   "length": 6,
   "clue": "Part of Yorkshire getting worked up (6)",
   "separatorLocations": {},
   "solution": "RIDING",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 9
   },
   "length": 6,
   "clue": "A farm animal is one of three (6)",
   "separatorLocations": {},
   "solution": "ARAMIS",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 9,
   "clue": "Bumpy, late entering – not a failure (9)",
   "separatorLocations": {},
   "solution": "NODULATED",
   "annotation": null
  },
  {
   "id": "24-down",
   "number": 24,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 4,
   "clue": "Kind? Bionic? Erm … a little! (4)",
   "separatorLocations": {},
   "solution": "NICE",
   "annotation": null
  },
  {
   "id": "25-down",
   "number": 25,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 11
   },
   "length": 4,
   "clue": "Obstructions from the net sap energy from Steel in ascent (4)",
   "separatorLocations": {},
   "solution": "LETS",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 11
   },
   "length": 5,
   "clue": "Sabre’s injured shoulders (5)",
   "separatorLocations": {},
   "solution": "BEARS",
   "annotation": null
  },
  {
   "id": "27-down",
   "number": 27,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 11
   },
   "length": 4,
   "clue": "Finals of Gladiators next Saturday? I’ve something in my eye! (4)",
   "separatorLocations": {},
   "solution": "STYE",
   "annotation": null
  },
  {
   "id": "28-across",
   "number": 28,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 13
   },
   "length": 5,
   "clue": "Take for a ride around Eliminator event (5)",
   "separatorLocations": {},
   "solution": "CHEAT",
   "annotation": null
  },
  {
   "id": "29-across",
   "number": 29,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 13
   },
   "length": 9,
   "clue": "Lying dazed, Dynamite clutching head on crashmat (9)",
   "separatorLocations": {},
   "solution": "MENDACITY",
   "annotation": null
  }
 ]
} /*JSON-END*/;
