// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-28743"] = /*JSON-START*/ {
 "id": "cryptic-28743",
 "number": 28743,
 "series": "cryptic",
 "name": "Cryptic crossword No 28,743",
 "setter": "Nutmeg",
 "date": 1651104000000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/cryptic/28743",
 "provenance": {
  "publisher": "Guardian",
  "series": "cryptic",
  "acquiredBy": "tools/fetch_puzzle.py",
  "acquiredOn": "2026-09-17",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 0
   },
   "length": 13,
   "clue": "Cooked last of three dishes perhaps lacking third of meat? (9,4)",
   "separatorLocations": {
    ",": [
     9
    ]
   },
   "solution": "SHEPHERDSPIES",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 9,
   "clue": "Could it be confusing to an Irish student of old? (9)",
   "separatorLocations": {},
   "solution": "HISTORIAN",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 5,
   "clue": "Feet heard to stop for a while (5)",
   "separatorLocations": {},
   "solution": "PAUSE",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 5,
   "clue": "Employ pundit, regardless of pressure (5)",
   "separatorLocations": {},
   "solution": "EXERT",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 9,
   "clue": "Edit clue, first of four condemned as underhand (9)",
   "separatorLocations": {},
   "solution": "DECEITFUL",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 9,
   "clue": "Views from master with time to go into particulars (9)",
   "separatorLocations": {},
   "solution": "PROSPECTS",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 5,
   "clue": "Moved cautiously and led on, scratching head (5)",
   "separatorLocations": {},
   "solution": "EASED",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 1
   },
   "length": 13,
   "clue": "Oppose return to university: student on vacation (4,2,7)",
   "separatorLocations": {
    ",": [
     4,
     6
    ]
   },
   "solution": "COMEUPAGAINST",
   "annotation": null
  },
  {
   "id": "9-down",
   "number": 9,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 1
   },
   "length": 13,
   "clue": "Majority think again briefly when cutting caper (13)",
   "separatorLocations": {},
   "solution": "PREPONDERANCE",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 7,
   "clue": "Little-known degree held by Guardian's head of entertainment (7)",
   "separatorLocations": {},
   "solution": "OBSCURE",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 2
   },
   "length": 7,
   "clue": "Snappier person coming over (7)",
   "separatorLocations": {},
   "solution": "CROSSER",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 5,
   "clue": "Call up first wife, having received go-ahead (5)",
   "separatorLocations": {},
   "solution": "EVOKE",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 4
   },
   "length": 9,
   "clue": "Left in pieces after contestant finally made a mistake (7,2)",
   "separatorLocations": {
    ",": [
     7
    ]
   },
   "solution": "TRIPPEDUP",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 5,
   "clue": "Smarten up pages around margin (5)",
   "separatorLocations": {},
   "solution": "PRIMP",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 6
   },
   "length": 9,
   "clue": "Earth's level area included in test (9)",
   "separatorLocations": {},
   "solution": "PLANETARY",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 6
   },
   "length": 9,
   "clue": "Thought to have left out light meal (9)",
   "separatorLocations": {},
   "solution": "REFECTION",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 6
   },
   "length": 9,
   "clue": "Imagined country united after one king, then another, beheaded queen (9)",
   "separatorLocations": {},
   "solution": "RURITANIA",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 6
   },
   "length": 9,
   "clue": "Frantic Yale fugitive not fit, sadly, for such a place (3,6)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "IVYLEAGUE",
   "annotation": null
  },
  {
   "id": "18-across",
   "number": 18,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 9,
   "clue": "NB regular treatment needed for part of arm (3,6)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "GUNBARREL",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 8
   },
   "length": 5,
   "clue": "Delayed training in troublesome communications app (5)",
   "separatorLocations": {},
   "solution": "SKYPE",
   "annotation": null
  },
  {
   "id": "20-across",
   "number": 20,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 9,
   "clue": "Transport official parking in trendy part of town (9)",
   "separatorLocations": {},
   "solution": "INSPECTOR",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 10
   },
   "length": 5,
   "clue": "Fibre's length unchanged on rotation (5)",
   "separatorLocations": {},
   "solution": "SISAL",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 10
   },
   "length": 5,
   "clue": "Bound work with scarlet cover (5)",
   "separatorLocations": {},
   "solution": "ROPED",
   "annotation": null
  },
  {
   "id": "23-across",
   "number": 23,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 10
   },
   "length": 5,
   "clue": "Father certainly repelled love goddess (5)",
   "separatorLocations": {},
   "solution": "FREYA",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 10
   },
   "length": 5,
   "clue": "Large leaf taken from soil often flipped over (5)",
   "separatorLocations": {},
   "solution": "FOLIO",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 7,
   "clue": "Suffer to keep up (7)",
   "separatorLocations": {},
   "solution": "SUSTAIN",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 12
   },
   "length": 7,
   "clue": "Receding storm in film of the open seas (7)",
   "separatorLocations": {},
   "solution": "PELAGIC",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 14
   },
   "length": 13,
   "clue": "Feign reluctance to give reason for theatre closure? (4,4,2,3)",
   "separatorLocations": {
    ",": [
     4,
     8,
     10
    ]
   },
   "solution": "PLAYHARDTOGET",
   "annotation": null
  }
 ]
} /*JSON-END*/;
