// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-25802"] = /*JSON-START*/ {
 "id": "cryptic-25802",
 "number": 25802,
 "series": "cryptic",
 "name": "Prize crossword No 25,802",
 "setter": "Paul",
 "date": 1353715200000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/prize/25802",
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 7,
   "clue": " Talk in which girl says she rambles, as 6 complains about cooking ingredient (7,2,8)",
   "group": [
    "1-across",
    "11-across"
   ],
   "separatorLocations": {
    ",": [
     7
    ]
   },
   "solution": "PARSLEY",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 6,
   "clue": "Part of the body, the sound of Peking? (6)",
   "separatorLocations": {},
   "solution": "PELVIS",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 6,
   "clue": "Step down first of stairs to break rule (6)",
   "separatorLocations": {},
   "solution": "RESIGN",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 10,
   "clue": "Love all? Take less time and skill — mixed doubles (10)",
   "separatorLocations": {},
   "solution": "LOOKALIKES",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 5,
   "clue": "Poet finds the mark of a leech on food (5)",
   "separatorLocations": {},
   "solution": "YEATS",
   "annotation": null
  },
  {
   "id": "5-across",
   "number": 5,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 7,
   "clue": "Enjoying oneself? Good man! (7)",
   "separatorLocations": {},
   "solution": "BONKING",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 9,
   "clue": "Poking bottom, I react badly, finding E coli, perhaps? (9)",
   "clueItalics": [
    [
     38,
     6
    ]
   ],
   "separatorLocations": {},
   "solution": "BACTERIUM",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 4,
   "clue": "Partial to pavilion, as Hanoverian architect (4)",
   "separatorLocations": {},
   "solution": "NASH",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 8,
   "clue": "King held up by goddess for nationals (8)",
   "separatorLocations": {},
   "solution": "ISRAELIS",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 8,
   "clue": "See 20",
   "group": [
    "20-down",
    "8-down"
   ],
   "separatorLocations": {
    ",": []
   },
   "solution": "GOLDFISH",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 5,
   "clue": "Lady requiring oxygen for something catching? (5)",
   "separatorLocations": {},
   "solution": "LASSO",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 2
   },
   "length": 9,
   "clue": "Family trips not starting, I abandon path (9)",
   "separatorLocations": {},
   "solution": "ANCESTRAL",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 10,
   "clue": "See 1",
   "group": [
    "1-across",
    "11-across"
   ],
   "separatorLocations": {
    ",": [
     2
    ]
   },
   "solution": "ISGHARSLEY",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 4
   },
   "length": 4,
   "clue": "Grouse to swallow? (4)",
   "separatorLocations": {},
   "solution": "BEEF",
   "annotation": null
  },
  {
   "id": "13-down",
   "number": 13,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 5
   },
   "length": 10,
   "clue": "Pulse -— bendy sort — pulse, ultimately, one gobbled by family (6,4)",
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "KIDNEYBEAN",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 3,
    "y": 6
   },
   "length": 12,
   "clue": "Impairments stabilised, one doubly mobile (12)",
   "separatorLocations": {},
   "solution": "DISABILITIES",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 6
   },
   "length": 9,
   "clue": "Sea with exclamation of discovery about bats being upside-down — or, perhaps, 6 on 23? (4,3,2)",
   "separatorLocations": {
    ",": [
     4,
     7
    ]
   },
   "solution": "ADAMHADEM",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 7
   },
   "length": 8,
   "clue": "20 8 by 6, perhaps, or from the poet Whitehead? (2,3,3)",
   "separatorLocations": {
    ",": [
     2,
     5
    ]
   },
   "solution": "OHWETPET",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 7
   },
   "length": 8,
   "clue": "Happy house passed around by rising river — that's extreme happiness! (8)",
   "separatorLocations": {},
   "solution": "EUPHORIA",
   "annotation": null
  },
  {
   "id": "18-across",
   "number": 18,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 12,
   "clue": "Get-together — in what way a hive of activity, did you say? (5-7)",
   "separatorLocations": {
    "-": [
     5
    ]
   },
   "solution": "HOUSEWARMING",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 9
   },
   "length": 6,
   "clue": "Bully's heartless right-wing bombast (6)",
   "separatorLocations": {},
   "solution": "TYRANT",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 9
   },
   "length": 6,
   "clue": " Good deal of this ornate creation of 6, perhaps (3,2,1,8)",
   "group": [
    "20-down",
    "8-down"
   ],
   "separatorLocations": {
    ",": [
     3,
     5,
     6
    ]
   },
   "solution": "ODETOA",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 4,
   "clue": "Bouncer releasing king from impossible choke (4)",
   "separatorLocations": {},
   "solution": "ECHO",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 10
   },
   "length": 10,
   "clue": "Suspicious-looking, fishy, yet astonishing journalist (6-4)",
   "separatorLocations": {
    "-": [
     6
    ]
   },
   "solution": "SHIFTYEYED",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 10
   },
   "length": 5,
   "clue": "Unwelcome visitors, first of aliens being upset about it (5)",
   "separatorLocations": {},
   "solution": "FLEAS",
   "annotation": null
  },
  {
   "id": "24-down",
   "number": 24,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 11
   },
   "length": 4,
   "clue": "Three's crowd trouble, if head to toe (4)",
   "separatorLocations": {},
   "solution": "TRIO",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 9,
   "clue": "Bird perhaps, given malicious gossip, hit back (9)",
   "separatorLocations": {},
   "solution": "PARTRIDGE",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 12
   },
   "length": 5,
   "clue": "Old key for lift (5)",
   "separatorLocations": {},
   "solution": "EXALT",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 7,
   "clue": "Male fed a bit of corn oil primarily, where cakes available? (3,4)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "TEAROOM",
   "annotation": null
  },
  {
   "id": "28-across",
   "number": 28,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 14
   },
   "length": 7,
   "clue": "Star turn in a star (7)",
   "separatorLocations": {},
   "solution": "SINATRA",
   "annotation": null
  }
 ]
} /*JSON-END*/;
