// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-22392"] = /*JSON-START*/ {
 "id": "cryptic-22392",
 "number": 22392,
 "series": "cryptic",
 "name": "Cryptic crossword No 22,392",
 "setter": "Mercury",
 "date": 1008288000000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/cryptic/22392",
 "provenance": {
  "publisher": "Guardian",
  "series": "cryptic",
  "acquiredBy": "tools/fetch_puzzle.py",
  "acquiredOn": "2026-09-18",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 7,
   "clue": "Man with hat on touring US city (7)",
   "separatorLocations": {},
   "solution": "ANTHONY",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 4,
   "clue": "It's no good girls wanting a ball to boot! (4)",
   "separatorLocations": {},
   "solution": "ALSO",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 15,
   "clue": "Aspen is rocking to music with Los Angeles ready to start (9,6)",
   "separatorLocations": {
    ",": [
     9
    ]
   },
   "solution": "TREMBLINGPOPLAR",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 6,
   "clue": "days on the way, briefly making notes (6)",
   "separatorLocations": {},
   "solution": "OCTAVE",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 6,
   "clue": "My go is ruined by a philosophical way of life (6)",
   "separatorLocations": {},
   "solution": "YOGISM",
   "annotation": null
  },
  {
   "id": "5-across",
   "number": 5,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 7,
   "clue": "Fruit in Africa's a basic necessity (7)",
   "separatorLocations": {},
   "solution": "CASABAS",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 8,
   "clue": "Is Lawrence right when following prison case? (8)",
   "separatorLocations": {},
   "solution": "CANISTER",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 8,
   "clue": "Mixed rest with water in colander (8)",
   "separatorLocations": {},
   "solution": "STRAINER",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 15,
   "clue": "Crazy bit by Len's father needs re-writing (4,2,3,6)",
   "separatorLocations": {
    ",": [
     4,
     6,
     9
    ]
   },
   "solution": "BATSINTHEBELFRY",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 10,
   "clue": "High level fire fighters? (10)",
   "separatorLocations": {},
   "solution": "SPRINKLERS",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 5,
   "clue": "Arranged to hold man's rope (5)",
   "separatorLocations": {},
   "solution": "SHEET",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 2
   },
   "length": 9,
   "clue": "Classes hill as a gas producer (9)",
   "separatorLocations": {},
   "solution": "GENERATOR",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 4
   },
   "length": 14,
   "clue": "So pub invoices a drunk having an honest reputation? (5,9)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "ABOVESUSPICION",
   "annotation": null
  },
  {
   "id": "12-down",
   "number": 12,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 10,
   "clue": "Run lad to US doctor for this type of scan (10)",
   "separatorLocations": {},
   "solution": "ULTRASOUND",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 4,
   "clue": "Try to telephone back as arranged (4)",
   "separatorLocations": {},
   "solution": "LAID",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 6
   },
   "length": 8,
   "clue": "Stand beneath a statue (8)",
   "separatorLocations": {},
   "solution": "PEDESTAL",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 7
   },
   "length": 8,
   "clue": "Because we stood up, taking a service tip off (8)",
   "separatorLocations": {},
   "solution": "FOREWARN",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 7
   },
   "length": 8,
   "clue": "A protein dispersing poison (8)",
   "separatorLocations": {},
   "solution": "ATROPINE",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 8,
   "clue": "Strike-breakers grow rebellious in plants (8)",
   "separatorLocations": {},
   "solution": "RAGWORTS",
   "annotation": null
  },
  {
   "id": "18-across",
   "number": 18,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 8
   },
   "length": 4,
   "clue": "Concern for fellow listener (4)",
   "separatorLocations": {},
   "solution": "FEAR",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 9
   },
   "length": 6,
   "clue": "Saws a girl's taking back, for example (6)",
   "separatorLocations": {},
   "solution": "ADAGES",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 9
   },
   "length": 6,
   "clue": "Not off in time for worship (6)",
   "separatorLocations": {},
   "solution": "HONOUR",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 14,
   "clue": "Beer's not sold - confused company admitted it's not drunk at all! (5-4,5)",
   "separatorLocations": {
    ",": [
     9
    ],
    "-": [
     5
    ]
   },
   "solution": "STONECOLDSOBER",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 11
   },
   "length": 4,
   "clue": "Got 1,000 to deliver power supplier (4)",
   "separatorLocations": {},
   "solution": "GRID",
   "annotation": null
  },
  {
   "id": "23-across",
   "number": 23,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 9,
   "clue": "Discharging a French boy in Gateshead after taking a ring (9)",
   "separatorLocations": {},
   "solution": "UNLOADING",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 12
   },
   "length": 5,
   "clue": "Volunteer leaving with Elizabeth (5)",
   "separatorLocations": {},
   "solution": "OFFER",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 7,
   "clue": "Put \"Out of Order\" notes on kitchen stove (7)",
   "separatorLocations": {},
   "solution": "DERANGE",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 14
   },
   "length": 7,
   "clue": "Having rest day arranged, wandered off (7)",
   "separatorLocations": {},
   "solution": "STRAYED",
   "annotation": null
  }
 ]
} /*JSON-END*/;
