// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-29549"] = /*JSON-START*/ {
 "id": "cryptic-29549",
 "number": 29549,
 "series": "cryptic",
 "name": "Cryptic crossword No 29,549",
 "setter": "Maskarade",
 "date": 1732492800000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/cryptic/29549",
 "provenance": {
  "publisher": "Guardian",
  "series": "cryptic",
  "acquiredBy": "tools/fetch_puzzle.py",
  "acquiredOn": "2026-09-17",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 7,
   "clue": "Wistful writer’s riddle broadcast (7)",
   "separatorLocations": {},
   "solution": "PENSIVE",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 0
   },
   "length": 7,
   "clue": "Apparently singular snack for teams (7)",
   "separatorLocations": {},
   "solution": "ELEVENS",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 0
   },
   "length": 9,
   "clue": "Facade’s terribly posh for New Town, initially (9)",
   "separatorLocations": {},
   "solution": "SHOPFRONT",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 0
   },
   "length": 6,
   "clue": "Trip finding Venice on yacht, principally, taking a time (6)",
   "separatorLocations": {},
   "solution": "VOYAGE",
   "annotation": null
  },
  {
   "id": "5-across",
   "number": 5,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 7,
   "clue": "Leaves in hot water here? (7)",
   "separatorLocations": {},
   "solution": "TEAPOTS",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 0
   },
   "length": 8,
   "clue": "Levi suffered somewhat, on reflection, gushing (8)",
   "separatorLocations": {},
   "solution": "EFFUSIVE",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 0
   },
   "length": 5,
   "clue": "Jacket potato and red kale are their starters (5)",
   "separatorLocations": {},
   "solution": "PARKA",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 0
   },
   "length": 7,
   "clue": "Dash over to meet a German to swap car? (5,2)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "TRADEIN",
   "annotation": null
  },
  {
   "id": "9-down",
   "number": 9,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 1
   },
   "length": 13,
   "clue": "Jargon from flyer heard on the Big Breakfast? (6,7)",
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "PIDGINENGLISH",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 6,
   "clue": "Medicinal plant back at rear of nursery (6)",
   "separatorLocations": {},
   "solution": "BETONY",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 2
   },
   "length": 8,
   "clue": "Relaxed popular class by a lake (8)",
   "separatorLocations": {},
   "solution": "INFORMAL",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 3
   },
   "length": 3,
   "clue": "Joiner is topping worker (3)",
   "separatorLocations": {},
   "solution": "AND",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 6,
   "clue": "It comes in banks in the main (3-3)",
   "separatorLocations": {
    "-": [
     3
    ]
   },
   "solution": "SEAFOG",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 4
   },
   "length": 8,
   "clue": "Flimsy material made of some rags (8)",
   "separatorLocations": {},
   "solution": "GOSSAMER",
   "annotation": null
  },
  {
   "id": "15-across",
   "number": 15,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 5,
   "clue": "Even innards of basset-hound for the Villa! (5)",
   "separatorLocations": {},
   "solution": "ASTON",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 6
   },
   "length": 9,
   "clue": "Having just one connection travelling via tunnel (9)",
   "separatorLocations": {},
   "solution": "UNIVALENT",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 6
   },
   "length": 9,
   "clue": "Whisky from wild archipelago without church (9)",
   "separatorLocations": {},
   "solution": "LAPHROAIG",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 7
   },
   "length": 8,
   "clue": "A capital girl – by Jove – ripping! (8)",
   "separatorLocations": {},
   "solution": "SARAJEVO",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 9,
   "clue": "Controlling influence of coach during time-off (9)",
   "separatorLocations": {},
   "solution": "RESTRAINT",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 8
   },
   "length": 7,
   "clue": "Touchy leading economist with reason (7)",
   "separatorLocations": {},
   "solution": "EMOTIVE",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 8
   },
   "length": 5,
   "clue": "Superior meal, seconds not required (5)",
   "separatorLocations": {},
   "solution": "UPPER",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 8
   },
   "length": 7,
   "clue": "Graceful and neat, oddly concealing limb (7)",
   "separatorLocations": {},
   "solution": "ELEGANT",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 9
   },
   "length": 6,
   "clue": "Opposed to a bit from Keats, say (6)",
   "separatorLocations": {},
   "solution": "AVERSE",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 8,
   "clue": "No farewell to learners. In no way (3,2,3)",
   "separatorLocations": {
    ",": [
     3,
     5
    ]
   },
   "solution": "NOTATALL",
   "annotation": null
  },
  {
   "id": "25-down",
   "number": 25,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 10
   },
   "length": 5,
   "clue": "Arab picked up the vernacular (5)",
   "separatorLocations": {},
   "solution": "ARGOT",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 10
   },
   "length": 6,
   "clue": "Differs showing V-sign (6)",
   "separatorLocations": {},
   "solution": "VARIES",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 11
   },
   "length": 3,
   "clue": "Furniture company no longer has active president (3)",
   "separatorLocations": {},
   "solution": "IKE",
   "annotation": null
  },
  {
   "id": "28-across",
   "number": 28,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 8,
   "clue": "Tops and just one t-shirt for starters (8)",
   "separatorLocations": {},
   "solution": "SINGLETS",
   "annotation": null
  },
  {
   "id": "29-across",
   "number": 29,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 12
   },
   "length": 6,
   "clue": "Unsure a gangster is holding president (6)",
   "separatorLocations": {},
   "solution": "REAGAN",
   "annotation": null
  },
  {
   "id": "30-across",
   "number": 30,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 7,
   "clue": "Ruin half of Rhodes and Ilium (7)",
   "separatorLocations": {},
   "solution": "DESTROY",
   "annotation": null
  },
  {
   "id": "31-across",
   "number": 31,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 14
   },
   "length": 7,
   "clue": "Massive group rowing in outskirts of Wallasey (7)",
   "separatorLocations": {},
   "solution": "WEIGHTY",
   "annotation": null
  }
 ]
} /*JSON-END*/;
