// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-25934"] = /*JSON-START*/ {
 "id": "cryptic-25934",
 "number": 25934,
 "series": "cryptic",
 "name": "Cryptic crossword No 25,934",
 "setter": "Rufus",
 "date": 1367193600000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/cryptic/25934",
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 0
   },
   "length": 9,
   "clue": "People engaged in a welcome correspondence (9)",
   "separatorLocations": {},
   "solution": "AGREEMENT",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 0
   },
   "length": 5,
   "clue": "Arterial way of vital importance (5)",
   "separatorLocations": {},
   "solution": "AORTA",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 0
   },
   "length": 7,
   "clue": "Shows respect, or perhaps the reverse (7)",
   "separatorLocations": {},
   "solution": "REVERES",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 0
   },
   "length": 5,
   "clue": "Concluded that many are in dire need (5)",
   "separatorLocations": {},
   "solution": "ENDED",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 0
   },
   "length": 7,
   "clue": "Finish with terribly sore back (7)",
   "separatorLocations": {},
   "solution": "ENDORSE",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 0
   },
   "length": 9,
   "clue": "Passing test, ran in all excited (9)",
   "separatorLocations": {},
   "solution": "TRANSIENT",
   "annotation": null
  },
  {
   "id": "6-across",
   "number": 6,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 0
   },
   "length": 4,
   "clue": "Outmoded tables may end up on the fire (4)",
   "separatorLocations": {},
   "solution": "LOGS",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 0
   },
   "length": 7,
   "clue": "Tract of grassland left untidy (7)",
   "separatorLocations": {},
   "solution": "LEAFLET",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 0
   },
   "length": 9,
   "clue": "A spirited community? Surely not! (5,4)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "GHOSTTOWN",
   "annotation": null
  },
  {
   "id": "8-across",
   "number": 8,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 8,
   "clue": "Lent on condition (8)",
   "separatorLocations": {},
   "solution": "PROVIDED",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 2
   },
   "length": 6,
   "clue": "River shrew? (6)",
   "separatorLocations": {},
   "solution": "AMAZON",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 6,
   "clue": "Heartbroken number show ill will (6)",
   "separatorLocations": {},
   "solution": "HATRED",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 4
   },
   "length": 8,
   "clue": "Determined to produce two notes on old instrument (8)",
   "separatorLocations": {},
   "solution": "RESOLUTE",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 6,
   "clue": "Sailor accustomed to being reviled (6)",
   "separatorLocations": {},
   "solution": "ABUSED",
   "annotation": null
  },
  {
   "id": "13-down",
   "number": 13,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 6
   },
   "length": 9,
   "clue": "A Schubert composition?  Capital! (9)",
   "separatorLocations": {},
   "solution": "BUCHAREST",
   "annotation": null
  },
  {
   "id": "14-down",
   "number": 14,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 6
   },
   "length": 9,
   "clue": "It need not give rise to punishment (9)",
   "separatorLocations": {},
   "solution": "DETENTION",
   "annotation": null
  },
  {
   "id": "15-across",
   "number": 15,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 6
   },
   "length": 8,
   "clue": "A time when the populace is at cross-purposes? (8)",
   "separatorLocations": {},
   "solution": "ELECTION",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 8,
   "clue": "A sign of wrong and right, we hear, in puzzle (8)",
   "separatorLocations": {},
   "solution": "ACROSTIC",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 8
   },
   "length": 7,
   "clue": "Running an exam in theory (2,5)",
   "separatorLocations": {
    ",": [
     2
    ]
   },
   "solution": "ONPAPER",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 8
   },
   "length": 7,
   "clue": "Clubs to beat? (7)",
   "separatorLocations": {},
   "solution": "CUDGELS",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 8
   },
   "length": 6,
   "clue": "Pulling to one side (6)",
   "separatorLocations": {},
   "solution": "TOWING",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 8
   },
   "length": 7,
   "clue": "The navy get under way in short film (7)",
   "separatorLocations": {},
   "solution": "WESTERN",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 8,
   "clue": "Came about Daphne possibly receiving exercise (8)",
   "separatorLocations": {},
   "solution": "HAPPENED",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 10
   },
   "length": 6,
   "clue": "Open a damaged sunroof (6)",
   "separatorLocations": {},
   "solution": "UNSTOP",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 10
   },
   "length": 5,
   "clue": "Declare total (5)",
   "separatorLocations": {},
   "solution": "UTTER",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 10
   },
   "length": 5,
   "clue": "Has to make professions of loyalty (5)",
   "separatorLocations": {},
   "solution": "OATHS",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 6,
   "clue": "Quietly get in foreign capital for Greek city (6)",
   "separatorLocations": {},
   "solution": "DELPHI",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 12
   },
   "length": 8,
   "clue": "Plea for Northeast to back contract (8)",
   "separatorLocations": {},
   "solution": "ENTREATY",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 4,
   "clue": "Good man has a right to take the lead (4)",
   "separatorLocations": {},
   "solution": "STAR",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 14
   },
   "length": 9,
   "clue": "Lack of restriction enjoyed by Pinocchio (2,7)",
   "separatorLocations": {
    ",": [
     2
    ]
   },
   "solution": "NOSTRINGS",
   "annotation": null
  }
 ]
} /*JSON-END*/;
