// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-25552"] = /*JSON-START*/ {
 "id": "cryptic-25552",
 "number": 25552,
 "series": "cryptic",
 "name": "Cryptic crossword No 25,552",
 "setter": "Brendan",
 "date": 1328572800000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/cryptic/25552",
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 11,
   "clue": "In old college, use of computers one term, as parties are organised (11)",
   "separatorLocations": {},
   "solution": "POLITICALLY",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 15,
   "clue": "Officer left in charge, introduced to author to artist (6,9)",
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "POLICECONSTABLE",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 5,
   "clue": "Sub, in practice, rewriting most of column (5)",
   "separatorLocations": {},
   "solution": "LOCUM",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 7,
   "clue": "Bald spot in style? Absolutely! (7)",
   "separatorLocations": {},
   "solution": "TONSURE",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 7,
   "clue": "What's right and proper in cleric or rector? (7)",
   "separatorLocations": {},
   "solution": "CORRECT",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 8,
   "clue": "Formation of troops moving forward on part of flight (8)",
   "separatorLocations": {},
   "solution": "LOCKSTEP",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 15,
   "clue": "Play without determination? (3,5,3,4)",
   "separatorLocations": {
    ",": [
     3,
     8,
     11
    ]
   },
   "solution": "YOUNEVERCANTELL",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 1
   },
   "length": 6,
   "clue": "A charlatan welcoming king in religious retreat (6)",
   "separatorLocations": {},
   "solution": "ASHRAM",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 1
   },
   "length": 6,
   "clue": "Feature a small computer, absorbing energy and time (6)",
   "separatorLocations": {},
   "solution": "ASPECT",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 7,
   "clue": "I left in second symbol on screen, a vital element in 1 across 4, 1 down, or 25, in short (7)",
   "separatorLocations": {},
   "solution": "SILICON",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 2
   },
   "length": 7,
   "clue": "Compensates PC user, distraught about nothing (7)",
   "separatorLocations": {},
   "solution": "RECOUPS",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 9,
   "clue": "Check accuracy of general opinion about Communist (9)",
   "separatorLocations": {},
   "solution": "RECOMPUTE",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 4
   },
   "length": 5,
   "clue": "Jobs in computing, among greatest ever (5)",
   "separatorLocations": {},
   "solution": "STEVE",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 4,
   "clue": "15 and 19 returned email from Nigeria? (4)",
   "separatorLocations": {},
   "solution": "MACS",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 6
   },
   "length": 10,
   "clue": "End of dispute in colony (10)",
   "separatorLocations": {},
   "solution": "SETTLEMENT",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 7
   },
   "length": 8,
   "clue": "Croatian altered protective garment (8)",
   "separatorLocations": {},
   "solution": "RAINCOAT",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 10,
   "clue": "A US line changed, put in and converted to yearly rate (10)",
   "separatorLocations": {},
   "solution": "ANNUALISED",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 6,
   "clue": "Simple program computer company sent, finally (6)",
   "separatorLocations": {},
   "solution": "APPLET",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 8
   },
   "length": 7,
   "clue": "Slight cut in hormone we all need (7)",
   "separatorLocations": {},
   "solution": "INSULIN",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 8
   },
   "length": 7,
   "clue": "Releases minute part in journalist's account? (7)",
   "separatorLocations": {},
   "solution": "EXEMPTS",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 8
   },
   "length": 4,
   "clue": "Old payment business set in stone (4)",
   "separatorLocations": {},
   "solution": "SCOT",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 8
   },
   "length": 6,
   "clue": "In excessively sentimental way set up online messages (6)",
   "separatorLocations": {},
   "solution": "TWEETS",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 5,
   "clue": "Elected foreign leader, repeatedly (5)",
   "separatorLocations": {},
   "solution": "PUTIN",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 10
   },
   "length": 9,
   "clue": "Realises error in various points (4,5)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "SEESSENSE",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 10
   },
   "length": 5,
   "clue": "Time in 9 that's provided for rest of travellers (5)",
   "separatorLocations": {},
   "solution": "SERAI",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 7,
   "clue": "Involve little brother, cutting back tree (7)",
   "separatorLocations": {},
   "solution": "EMBROIL",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 12
   },
   "length": 7,
   "clue": "Line drawn between circles as measure of concentration (3,4)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "PERCENT",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 2,
    "y": 14
   },
   "length": 11,
   "clue": "Become completely satisfied when stallion fee is adjusted (3,4,4)",
   "separatorLocations": {
    ",": [
     3,
     7
    ]
   },
   "solution": "EATONESFILL",
   "annotation": null
  }
 ]
} /*JSON-END*/;
