// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-26614"] = /*JSON-START*/ {
 "id": "cryptic-26614",
 "number": 26614,
 "series": "cryptic",
 "name": "Cryptic crossword No 26,614",
 "setter": "Nutmeg",
 "date": 1435881600000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/cryptic/26614",
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 9,
   "clue": "Teach girl cooking, with little response (9)",
   "separatorLocations": {},
   "solution": "LETHARGIC",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 5,
   "clue": "Extremely likeable worker tipped (5)",
   "separatorLocations": {},
   "solution": "LEANT",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 7,
   "clue": "Collection cheers Cambridge college (7)",
   "separatorLocations": {},
   "solution": "TAKINGS",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 4,
   "clue": "Top primate given cross (4)",
   "separatorLocations": {},
   "solution": "APEX",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 4,
   "clue": "Something provoking adult in Rover's Return? (4)",
   "separatorLocations": {},
   "solution": "GOAD",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 10,
   "clue": "Critique's evasive about male intellectual changing sides (10)",
   "separatorLocations": {},
   "solution": "COMMENTARY",
   "annotation": null
  },
  {
   "id": "6-across",
   "number": 6,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 5,
   "clue": "Aspect of Spain no fiction's written about (5)",
   "separatorLocations": {},
   "solution": "FACET",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 10,
   "clue": "Smitten rook dropped in far distance, fluttering (10)",
   "separatorLocations": {},
   "solution": "FASCINATED",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 7,
   "clue": "Ship that could prevent schooner making its mark? (7)",
   "separatorLocations": {},
   "solution": "COASTER",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 9,
   "clue": "Derby date produced a favourite among three-year-olds (5,4)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "TEDDYBEAR",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 15,
   "clue": "Enthusiastic, by Colman's standard? (2,4,2,7)",
   "separatorLocations": {
    ",": [
     2,
     6,
     8
    ]
   },
   "solution": "ASKEENASMUSTARD",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 4,
   "clue": "Nurse is mean, though not at home (4)",
   "separatorLocations": {},
   "solution": "TEND",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 4
   },
   "length": 8,
   "clue": "Judge again accepts servicemen's official record (8)",
   "separatorLocations": {},
   "solution": "REGISTRY",
   "annotation": null
  },
  {
   "id": "12-down",
   "number": 12,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 5
   },
   "length": 10,
   "clue": "Invader mounted soldiers cut off in Bury (10)",
   "separatorLocations": {},
   "solution": "INTERLOPER",
   "annotation": null
  },
  {
   "id": "13-down",
   "number": 13,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 5
   },
   "length": 10,
   "clue": "Brief respite as kick finally breaks long run of victories (5,5)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "FORTYWINKS",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 9,
   "clue": "Disadvantaged lions suffering painful affliction (6,3)",
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "LOSINGOUT",
   "annotation": null
  },
  {
   "id": "14-down",
   "number": 14,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 9,
   "clue": "Constable, eg, delivers father held up in church (9)",
   "separatorLocations": {},
   "solution": "LANDSCAPE",
   "annotation": null
  },
  {
   "id": "15-across",
   "number": 15,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 6
   },
   "length": 5,
   "clue": "Mature guards about to reach the same conclusion (5)",
   "separatorLocations": {},
   "solution": "AGREE",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 5,
   "clue": "Section of scenic headland appealing to small group (5)",
   "separatorLocations": {},
   "solution": "NICHE",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 8
   },
   "length": 7,
   "clue": "Cleaned house superficially affected by fire (7)",
   "separatorLocations": {},
   "solution": "CHARRED",
   "annotation": null
  },
  {
   "id": "18-across",
   "number": 18,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 8
   },
   "length": 9,
   "clue": "Person troubling troops trapped between rocky heights (9)",
   "separatorLocations": {},
   "solution": "TORMENTOR",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 8
   },
   "length": 7,
   "clue": "Audible attempt to reduce effectiveness of missile (7)",
   "separatorLocations": {},
   "solution": "TRIDENT",
   "annotation": null
  },
  {
   "id": "20-across",
   "number": 20,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 8,
   "clue": "Wide brooks bordering South Downs (8)",
   "separatorLocations": {},
   "solution": "SWALLOWS",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 10
   },
   "length": 4,
   "clue": "Leader sacked in current breach (4)",
   "separatorLocations": {},
   "solution": "RIFT",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 10
   },
   "length": 5,
   "clue": "Stimulant at bottom of scale? (5)",
   "separatorLocations": {},
   "solution": "TONIC",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 11
   },
   "length": 4,
   "clue": "Unconvincing philosophy with no place for king (4)",
   "separatorLocations": {},
   "solution": "THIN",
   "annotation": null
  },
  {
   "id": "24-down",
   "number": 24,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 11
   },
   "length": 4,
   "clue": "Up-market shop trashed (4)",
   "separatorLocations": {},
   "solution": "POSH",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 15,
   "clue": "Indian descent possibly of little consequence (1,4,2,3,5)",
   "separatorLocations": {
    ",": [
     1,
     5,
     7,
     10
    ]
   },
   "solution": "ADROPINTHEOCEAN",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 5,
   "clue": "Queen eats fish — it could be getting her down (5)",
   "separatorLocations": {},
   "solution": "EIDER",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 14
   },
   "length": 9,
   "clue": "Article on \"name\" in financial centre's rejected as inauthentic (9)",
   "separatorLocations": {},
   "solution": "SYNTHETIC",
   "annotation": null
  }
 ]
} /*JSON-END*/;
