// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-26884"] = /*JSON-START*/ {
 "id": "cryptic-26884",
 "number": 26884,
 "series": "cryptic",
 "name": "Prize crossword No 26,884",
 "setter": "Paul",
 "date": 1463184000000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/prize/26884",
 "entries": [
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 15,
   "clue": "Essentially, fat insects pumped with lead shot, then pared off (6-3,6)",
   "separatorLocations": {
    ",": [
     9
    ],
    "-": [
     6
    ]
   },
   "solution": "MIDDLEAGESPREAD",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 8,
   "clue": "Torch, innocent thing in iron and gold (8)",
   "separatorLocations": {},
   "solution": "FLAMBEAU",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 5,
   "clue": "Certain limit (5)",
   "separatorLocations": {},
   "solution": "BOUND",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 8,
   "clue": "Giant captured by boy, well I never! (6,2)",
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "STROLLON",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 6,
   "clue": "Briefly witty as some comic, I'm on guard being sent up (6)",
   "separatorLocations": {},
   "solution": "GNOMIC",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 9,
   "clue": "Enjoy a furore very much (4,5)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "LIKESTINK",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 6,
   "clue": "Las Vegas establishment equally popular, business raking it in (6)",
   "separatorLocations": {},
   "solution": "CASINO",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 15,
   "clue": "Noted communication error mine, alert leader in government when trebly confused (7,8)",
   "separatorLocations": {
    ",": [
     7
    ]
   },
   "solution": "SINGINGTELEGRAM",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 1
   },
   "length": 9,
   "clue": "Dirty dog's ending in no little trouble (3-6)",
   "separatorLocations": {
    "-": [
     3
    ]
   },
   "solution": "ILLGOTTEN",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 1
   },
   "length": 5,
   "clue": "China in Japan, damage between the two (5)",
   "separatorLocations": {},
   "solution": "IMARI",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 3
   },
   "length": 7,
   "clue": "Saving a little time, don't stay to see opera singer (7)",
   "separatorLocations": {},
   "solution": "DOMINGO",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 3
   },
   "length": 7,
   "clue": "Union supporter on course to return in Chinese dynasty (7)",
   "separatorLocations": {},
   "solution": "MEETING",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 4,
   "clue": "Runner caught someone at the top (4)",
   "separatorLocations": {},
   "solution": "EXEC",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 5
   },
   "length": 10,
   "clue": "Straggly branch OK with tall, hollow bush (10)",
   "separatorLocations": {},
   "solution": "BLACKTHORN",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 6
   },
   "length": 9,
   "clue": "Spooner's poem to Chelsea that may go to one's head? (3,6)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "SUNBONNET",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 7
   },
   "length": 7,
   "clue": "Painter, way less than a month through the alcohol (7)",
   "separatorLocations": {},
   "solution": "GAUGUIN",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 7
   },
   "length": 7,
   "clue": "Picture lover in ecstasy during fling (7)",
   "separatorLocations": {},
   "solution": "CINEAST",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 7
   },
   "length": 8,
   "clue": "Monument, knock one up in church (8)",
   "separatorLocations": {},
   "solution": "CENOTAPH",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 7
   },
   "length": 8,
   "clue": " A quality detailed, and among the best, as a nation's aspiration for a better life (8,5)",
   "group": [
    "18-down",
    "23-down"
   ],
   "separatorLocations": {
    ",": [
     8
    ]
   },
   "solution": "AMERICAN",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 9
   },
   "length": 10,
   "clue": "Drooling, one throwing up during chant (10)",
   "separatorLocations": {},
   "solution": "SLOBBERING",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 9
   },
   "length": 6,
   "clue": "Leg before wicket partly, one way to get out? (2,4)",
   "separatorLocations": {
    ",": [
     2
    ]
   },
   "solution": "ONBAIL",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 9
   },
   "length": 6,
   "clue": "US property concerned with key industry, ultimately (6)",
   "separatorLocations": {},
   "solution": "REALTY",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 9
   },
   "length": 4,
   "clue": "Shake hands on mammal with flippers (4)",
   "separatorLocations": {},
   "solution": "SEAL",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 10
   },
   "length": 5,
   "clue": "See 18",
   "group": [
    "18-down",
    "23-down"
   ],
   "separatorLocations": {
    ",": []
   },
   "solution": "DREAM",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 7,
   "clue": "Bird I adore's heading for flowering shrub (7)",
   "separatorLocations": {},
   "solution": "ROBINIA",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 11
   },
   "length": 7,
   "clue": " Looking away when gran nude, is it surprising? (7,5)",
   "group": [
    "25-across",
    "26-across"
   ],
   "separatorLocations": {
    ",": [
     7
    ]
   },
   "solution": "TURNING",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 13
   },
   "length": 5,
   "clue": "See 25",
   "group": [
    "25-across",
    "26-across"
   ],
   "separatorLocations": {
    ",": []
   },
   "solution": "ASIDE",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 13
   },
   "length": 9,
   "clue": "Leader, the best of the bunch? (3,6)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "TOPBANANA",
   "annotation": null
  }
 ]
} /*JSON-END*/;
