// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-22669"] = /*JSON-START*/ {
 "id": "cryptic-22669",
 "number": 22669,
 "series": "cryptic",
 "name": "Cryptic crossword No 22,669",
 "setter": "Rover",
 "date": 1036454400000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/cryptic/22669",
 "provenance": {
  "publisher": "Guardian",
  "series": "cryptic",
  "acquiredBy": "tools/fetch_puzzle.py",
  "acquiredOn": "2026-09-18",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 8,
   "clue": "Unpopular worker promises to pay for plant (8)",
   "separatorLocations": {},
   "solution": "SCABIOUS",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 10,
   "clue": "Mouth-watering violins at a jig (10)",
   "separatorLocations": {},
   "solution": "SALIVATION",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 10,
   "clue": "Usual train heading for East Germany (10)",
   "separatorLocations": {},
   "solution": "ACCUSTOMED",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 5,
   "clue": "Start coming back in a fortnight (5)",
   "separatorLocations": {},
   "solution": "INTRO",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 12,
   "clue": "Beano's unreal, mad, far-fetched (12)",
   "separatorLocations": {},
   "solution": "UNREASONABLE",
   "annotation": null
  },
  {
   "id": "5-across",
   "number": 5,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 0
   },
   "length": 6,
   "clue": "A resonant string brings harmony (6)",
   "separatorLocations": {},
   "solution": "ACCORD",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 9,
   "clue": "Shady dealer showing character suddenly (4-5)",
   "separatorLocations": {
    "-": [
     4
    ]
   },
   "solution": "CARDSHARP",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 4,
   "clue": "Silica is not about resin (4)",
   "separatorLocations": {},
   "solution": "OPAL",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 4,
   "clue": "It's done up and down (4)",
   "separatorLocations": {},
   "solution": "DEED",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 8,
   "clue": "Room in a monastery - but not for Trappists! (8)",
   "separatorLocations": {},
   "solution": "LOCUTORY",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 2
   },
   "length": 6,
   "clue": "Some bonnets worn at Easter are flowery (6)",
   "separatorLocations": {},
   "solution": "ORNATE",
   "annotation": null
  },
  {
   "id": "11-down",
   "number": 11,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 3
   },
   "length": 12,
   "clue": "Fast incident involved medical agent (12)",
   "separatorLocations": {},
   "solution": "DISINFECTANT",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 11,
   "clue": "Romantics seeing stars (11)",
   "separatorLocations": {},
   "solution": "VISIONARIES",
   "annotation": null
  },
  {
   "id": "13-down",
   "number": 13,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 5
   },
   "length": 10,
   "clue": "Well-read player from Hamilton? (10)",
   "separatorLocations": {},
   "solution": "ACADEMICAL",
   "annotation": null
  },
  {
   "id": "14-down",
   "number": 14,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 5
   },
   "length": 10,
   "clue": "500 seaplanes flying  along areas by the sea (10)",
   "separatorLocations": {},
   "solution": "ESPLANADES",
   "annotation": null
  },
  {
   "id": "15-across",
   "number": 15,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 5,
   "clue": "Tips worth waiting for? (5)",
   "separatorLocations": {},
   "solution": "TRONC",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 6
   },
   "length": 9,
   "clue": "A ready supply starts at the market (9)",
   "separatorLocations": {},
   "solution": "CASHPOINT",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 6
   },
   "length": 9,
   "clue": "The first of the few (9)",
   "separatorLocations": {},
   "solution": "OLIGARCHS",
   "annotation": null
  },
  {
   "id": "18-across",
   "number": 18,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 9,
   "clue": "Vast offer made to engage too many (9)",
   "separatorLocations": {},
   "solution": "OVERSTAFF",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 8
   },
   "length": 5,
   "clue": "Lever made of soft, malleable lead (5)",
   "separatorLocations": {},
   "solution": "PEDAL",
   "annotation": null
  },
  {
   "id": "20-across",
   "number": 20,
   "direction": "across",
   "position": {
    "x": 4,
    "y": 10
   },
   "length": 11,
   "clue": "They patrol with uneven paces (11)",
   "separatorLocations": {},
   "solution": "POLICEWOMEN",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 10
   },
   "length": 5,
   "clue": "It can deliver a blow while in the water (5)",
   "separatorLocations": {},
   "solution": "WHALE",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 4,
   "clue": "See 23 (4)",
   "group": [
    "23-down",
    "22-down"
   ],
   "separatorLocations": {
    ",": []
   },
   "solution": "TREK",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 11
   },
   "length": 4,
   "clue": "Starter rearranged Kirk's first journey (4,4)",
   "group": [
    "23-down",
    "22-down"
   ],
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "STAR",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 6,
   "clue": "Keep film in water (6)",
   "separatorLocations": {},
   "solution": "RETAIN",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 12
   },
   "length": 8,
   "clue": "Just man in poor surroundings (8)",
   "separatorLocations": {},
   "solution": "BALANCED",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 6,
   "clue": "Sport where girl impresses artist (6)",
   "separatorLocations": {},
   "solution": "KARATE",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 14
   },
   "length": 8,
   "clue": "They showed chasers the way to jump (8)",
   "separatorLocations": {},
   "solution": "STEEPLES",
   "annotation": null
  }
 ]
} /*JSON-END*/;
