// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-28164"] = /*JSON-START*/ {
 "id": "cryptic-28164",
 "number": 28164,
 "series": "cryptic",
 "name": "Cryptic crossword No 28,164",
 "setter": "Pasquale",
 "date": 1592524800000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/cryptic/28164",
 "provenance": {
  "publisher": "Guardian",
  "series": "cryptic",
  "acquiredBy": "tools/fetch_puzzle.py",
  "acquiredOn": "2026-09-17",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 6,
   "clue": "Rock and roll primarily lacking in training of singers (6)",
   "separatorLocations": {},
   "solution": "GNEISS",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 8,
   "clue": "Wealth coming to composer, man of musical variations (8)",
   "separatorLocations": {},
   "solution": "GOLDBERG",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 8,
   "clue": "Bar gets this for beggar that's like a frustrated bird (3-5)",
   "separatorLocations": {
    "-": [
     3
    ]
   },
   "solution": "EGGBOUND",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 5,
   "clue": "Cut made by saw initially on wood (5)",
   "separatorLocations": {},
   "solution": "STEAK",
   "annotation": null
  },
  {
   "id": "4-across",
   "number": 4,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 0
   },
   "length": 8,
   "clue": "Idiot was troubled, being attacked (8)",
   "separatorLocations": {},
   "solution": "ASSAILED",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 13,
   "clue": "Producer of sweet stuff could make one rise with fury and anger (5,8)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "SUGARREFINERY",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 9,
   "clue": "He-men at a dance outside university club in London (9)",
   "separatorLocations": {},
   "solution": "ATHENAEUM",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 6,
   "clue": "Where's the sound coming from? Cat getting round a queen (6)",
   "separatorLocations": {},
   "solution": "LARYNX",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 6,
   "clue": "Lots of celebrations outside Japanese school (6)",
   "separatorLocations": {},
   "solution": "DOZENS",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 5,
   "clue": " Scottish innovator to record a birdie in flight (5,5)",
   "group": [
    "9-across",
    "24-across"
   ],
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "LOGIE",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 2
   },
   "length": 9,
   "clue": "High frequency range, say, penetrating mum — is sore in the ears (9)",
   "separatorLocations": {},
   "solution": "MEGAHERTZ",
   "annotation": null
  },
  {
   "id": "10-down",
   "number": 10,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 2
   },
   "length": 13,
   "clue": "The mum dashing around got off to a brisk start (4,6,3)",
   "separatorLocations": {
    ",": [
     4,
     10
    ]
   },
   "solution": "MADETHINGSHUM",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 9,
   "clue": "Wartime pilot must circumvent something hairy, cause of obstruction (9)",
   "separatorLocations": {},
   "solution": "BLOCKADER",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 4
   },
   "length": 5,
   "clue": "Any number knowing about fine material (5)",
   "separatorLocations": {},
   "solution": "NINON",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 12,
   "clue": "Bird is rotten glider in a storm (4,8)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "RINGDOTTEREL",
   "annotation": null
  },
  {
   "id": "14-down",
   "number": 14,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 6
   },
   "length": 9,
   "clue": "Order without intermediate agent — something charged (9)",
   "separatorLocations": {},
   "solution": "DIRECTION",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 7
   },
   "length": 8,
   "clue": "Men probing wild animal on the lord's estate? (8)",
   "separatorLocations": {},
   "solution": "MANORIAL",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 7
   },
   "length": 8,
   "clue": "In territory in December mud annoys (8)",
   "separatorLocations": {},
   "solution": "BERMUDAN",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 3,
    "y": 8
   },
   "length": 12,
   "clue": "What's awfully tiresome, I get older — time to enjoy life in France? (9,3)",
   "separatorLocations": {
    ",": [
     9
    ]
   },
   "solution": "TROISIEMEAGE",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 9
   },
   "length": 6,
   "clue": "Dad exercises and stops to draw breath? (6)",
   "separatorLocations": {},
   "solution": "PAUSES",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 9
   },
   "length": 6,
   "clue": "Damage when river floods country (6)",
   "separatorLocations": {},
   "solution": "SPRAIN",
   "annotation": null
  },
  {
   "id": "20-across",
   "number": 20,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 5,
   "clue": "Like illustration, something set on dining table (5)",
   "separatorLocations": {},
   "solution": "ASPIC",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 10
   },
   "length": 9,
   "clue": "Never to return wearing dress in theatrical space for visitors (5,4)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "GREENROOM",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 10
   },
   "length": 5,
   "clue": "Triangular symbol composer of 1 down set up (5)",
   "separatorLocations": {},
   "solution": "NABLA",
   "annotation": null
  },
  {
   "id": "23-across",
   "number": 23,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 9,
   "clue": "What's roguish about Liberal showing no originality? (9)",
   "separatorLocations": {},
   "solution": "SLAVISHLY",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 12
   },
   "length": 5,
   "clue": "See 9",
   "group": [
    "9-across",
    "24-across"
   ],
   "separatorLocations": {
    ",": []
   },
   "solution": "BAIRD",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 8,
   "clue": "My sonny's ill — tired and worn out, maybe (8)",
   "separatorLocations": {},
   "solution": "SYNONYMS",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 14
   },
   "length": 6,
   "clue": "Jockey getting on after race accident (6)",
   "separatorLocations": {},
   "solution": "FALLON",
   "annotation": null
  }
 ]
} /*JSON-END*/;
