// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-23658"] = /*JSON-START*/ {
 "id": "cryptic-23658",
 "number": 23658,
 "series": "cryptic",
 "name": "Cryptic crossword No 23,658",
 "setter": "Rufus",
 "date": 1136764800000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/cryptic/23658",
 "provenance": {
  "publisher": "Guardian",
  "series": "cryptic",
  "acquiredBy": "tools/fetch_puzzle.py",
  "acquiredOn": "2026-09-17",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 10,
   "clue": "It does business in more than one way (6,4)",
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "CORNERSHOP",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 8,
   "clue": "Demotion? Resign! (4,4)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "STEPDOWN",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 6,
   "clue": "A tense time ahead (6)",
   "separatorLocations": {},
   "solution": "FUTURE",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 4,
   "clue": "Number four iron taken out (4)",
   "separatorLocations": {},
   "solution": "FIVE",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 10,
   "clue": "A quality one considers oneself worthy to have (4-6)",
   "separatorLocations": {
    "-": [
     4
    ]
   },
   "solution": "SELFESTEEM",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 8,
   "clue": "But it's not the time nothing happens (4,4)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "ZEROHOUR",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 6,
   "clue": "Did some evening work (6)",
   "separatorLocations": {},
   "solution": "IRONED",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 4,
   "clue": "An overcrowded children's home (4)",
   "separatorLocations": {},
   "solution": "SHOE",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 1
   },
   "length": 9,
   "clue": "Twist or bust, I've to be bold (9)",
   "separatorLocations": {},
   "solution": "OBTRUSIVE",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 1
   },
   "length": 5,
   "clue": "Slight change of heart for space traveller (5)",
   "separatorLocations": {},
   "solution": "EARTH",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 3
   },
   "length": 7,
   "clue": "The Roman's main deity (7)",
   "separatorLocations": {},
   "solution": "NEPTUNE",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 3
   },
   "length": 7,
   "clue": "Disposition of uncle to have a fling (7)",
   "separatorLocations": {},
   "solution": "FLOUNCE",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 5,
   "clue": "River cut by river (5)",
   "separatorLocations": {},
   "solution": "RHONE",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 5
   },
   "length": 9,
   "clue": "Went without saying (9)",
   "separatorLocations": {},
   "solution": "ABSCONDED",
   "annotation": null
  },
  {
   "id": "14-down",
   "number": 14,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 5
   },
   "length": 10,
   "clue": "They are named for the post (10)",
   "separatorLocations": {},
   "solution": "ADDRESSEES",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 5
   },
   "length": 10,
   "clue": "Possibly a good tryer? That's somewhat disparaging (10)",
   "separatorLocations": {},
   "solution": "DEROGATORY",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 7
   },
   "length": 15,
   "clue": "Fight of the century (7,5,3)",
   "separatorLocations": {
    ",": [
     7,
     12
    ]
   },
   "solution": "HUNDREDYEARSWAR",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 7
   },
   "length": 8,
   "clue": "Ruddy good fellow, university type (8)",
   "separatorLocations": {},
   "solution": "REDBRICK",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 7
   },
   "length": 8,
   "clue": "Pedestrian protests? (4-4)",
   "separatorLocations": {
    "-": [
     4
    ]
   },
   "solution": "WALKOUTS",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 9
   },
   "length": 9,
   "clue": "Smoker's fancy (4,5)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "PIPEDREAM",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 9
   },
   "length": 6,
   "clue": "Hose used on borders (6)",
   "separatorLocations": {},
   "solution": "PIPING",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 9
   },
   "length": 5,
   "clue": "Wartime imprisonment of a convict (5)",
   "separatorLocations": {},
   "solution": "OFLAG",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 9
   },
   "length": 6,
   "clue": "Do rise above debts admitted to be bad (6)",
   "separatorLocations": {},
   "solution": "ODIOUS",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 7,
   "clue": "Aims to get a ship round an awkward pier (7)",
   "separatorLocations": {},
   "solution": "ASPIRES",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 4,
   "clue": "A record, second highest in the European charts (4)",
   "separatorLocations": {},
   "solution": "ALPS",
   "annotation": null
  },
  {
   "id": "23-across",
   "number": 23,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 11
   },
   "length": 7,
   "clue": "Spent money on things like free range eggs (4,3)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "LAIDOUT",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 11
   },
   "length": 4,
   "clue": "Key position in rugby? (4)",
   "separatorLocations": {},
   "solution": "LOCK",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 13
   },
   "length": 5,
   "clue": "Police constable holding back in a state of terror (5)",
   "separatorLocations": {},
   "solution": "PANIC",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 13
   },
   "length": 9,
   "clue": "Meet in French bar (9)",
   "separatorLocations": {},
   "solution": "ENCOUNTER",
   "annotation": null
  }
 ]
} /*JSON-END*/;
