// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["cryptic-24487"] = /*JSON-START*/ {
 "id": "cryptic-24487",
 "number": 24487,
 "series": "cryptic",
 "name": "Prize crossword No 24,487",
 "setter": "Araucaria",
 "date": 1220659200000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/prize/24487",
 "provenance": {
  "publisher": "Guardian",
  "series": "cryptic",
  "acquiredBy": "tools/fetch_puzzle.py",
  "acquiredOn": "2026-09-17",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 15,
   "clue": "This is curious - odds on proud being involved in deception, not I (9,6)",
   "separatorLocations": {
    ",": [
     9
    ]
   },
   "solution": "CROSSWORDPUZZLE",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 8,
   "clue": "Wrong half of Hellas in Greek given to 23 (8)",
   "separatorLocations": {},
   "solution": "ATHLETIC",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 5,
   "clue": "See 20",
   "group": [
    "20-down",
    "3-down"
   ],
   "separatorLocations": {
    ",": []
   },
   "solution": "BLOCK",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 8,
   "clue": "Extremely insensitive heart under building? (4,4)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "HARDCORE",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 6,
   "clue": "Iron wheel with new base (6)",
   "separatorLocations": {},
   "solution": "FERRIC",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 9,
   "clue": "Decoration for building to get reduction on the exterior (9)",
   "separatorLocations": {},
   "solution": "PARGETING",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 6,
   "clue": "Which church has cover? (6)",
   "separatorLocations": {},
   "solution": "THATCH",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 15,
   "clue": "Compounding regal 4, flattery is our biggest fault (5,4,6)",
   "separatorLocations": {
    ",": [
     5,
     9
    ]
   },
   "solution": "GREATRIFTVALLEY",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 1
   },
   "length": 9,
   "clue": "Terrorists first and subsequently to get back  ... their own (9)",
   "separatorLocations": {},
   "solution": "RETALIATE",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 1
   },
   "length": 5,
   "clue": "Jane's tribe on stage, with A for Antony? (5)",
   "separatorLocations": {},
   "solution": "ASHER",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 3
   },
   "length": 7,
   "clue": "Married with no children, not being licensed (7)",
   "separatorLocations": {},
   "solution": "SPLICED",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 3
   },
   "length": 7,
   "clue": "A target set for aquatic event (7)",
   "separatorLocations": {},
   "solution": "REGATTA",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 4,
   "clue": "Engineer's spoken question? (4)",
   "separatorLocations": {},
   "solution": "WATT",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 5
   },
   "length": 10,
   "clue": "Fellow sentinel keeps clubs for protection of train (10)",
   "separatorLocations": {},
   "solution": "COWCATCHER",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 6
   },
   "length": 9,
   "clue": "Game, not a good one, among poets (9)",
   "separatorLocations": {},
   "solution": "BILLIARDS",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 7
   },
   "length": 7,
   "clue": "Take course to be at ease (7)",
   "separatorLocations": {},
   "solution": "RECLINE",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 7
   },
   "length": 7,
   "clue": "Wizard with access to standard return (7)",
   "separatorLocations": {},
   "solution": "GANDALF",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 7
   },
   "length": 8,
   "clue": "Cooker for idiot to put in cooked vegetables (3,5)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "GASSTOVE",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 7
   },
   "length": 8,
   "clue": "Unholy verse by the poet Lewis towards the end of April (5,3)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "ANZACDAY",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 9
   },
   "length": 10,
   "clue": "Building cover for recession initiated during infatuation (10)",
   "separatorLocations": {},
   "solution": "PEBBLEDASH",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 9
   },
   "length": 6,
   "clue": "Wind brake in building? (6,5)",
   "group": [
    "20-down",
    "3-down"
   ],
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "BREEZE",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 9
   },
   "length": 6,
   "clue": "Gather from leader in European countries (6)",
   "separatorLocations": {},
   "solution": "DEDUCE",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 9
   },
   "length": 4,
   "clue": "A 0.3125 lb return from sea (4)",
   "separatorLocations": {},
   "solution": "AZOV",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 10
   },
   "length": 5,
   "clue": "Not the 25 play? (5)",
   "separatorLocations": {},
   "solution": "SPORT",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 7,
   "clue": "Oxymoronic region where letter has dash in it (7)",
   "separatorLocations": {},
   "solution": "ZEELAND",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 11
   },
   "length": 7,
   "clue": "Extract from clay pit to be expected (7)",
   "separatorLocations": {},
   "solution": "TYPICAL",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 13
   },
   "length": 5,
   "clue": "Was idle student introduced to Sunday's 1? (5)",
   "separatorLocations": {},
   "solution": "LAZED",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 13
   },
   "length": 9,
   "clue": "Disc containing extra drink for Bible translator in Yorkshire (9)",
   "separatorLocations": {},
   "solution": "COVERDALE",
   "annotation": null
  }
 ]
} /*JSON-END*/;
