// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["everyman-3347"] = /*JSON-START*/ {
 "id": "everyman-3347",
 "number": 3347,
 "series": "everyman",
 "name": "Everyman crossword No 3,347",
 "setter": "Everyman",
 "date": 1290297600000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/everyman/3347",
 "provenance": {
  "publisher": "Observer",
  "series": "everyman",
  "acquiredBy": "tools/fetch_puzzle.py",
  "acquiredOn": "2026-09-18",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 5,
   "clue": "Part of the UK was invaded by the French (5)",
   "separatorLocations": {},
   "solution": "WALES",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 9,
   "clue": "Offender harassed dog owner on end of pier (9)",
   "separatorLocations": {},
   "solution": "WRONGDOER",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 5,
   "clue": "Tell principal of Loughborough College (3,2)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "LETON",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 7,
   "clue": "Sleeveless shirt - team's leader is after one (7)",
   "separatorLocations": {},
   "solution": "SINGLET",
   "annotation": null
  },
  {
   "id": "4-across",
   "number": 4,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 9,
   "clue": "Purchase, on the phone before work, a derivative (2-7)",
   "separatorLocations": {
    "-": [
     2
    ]
   },
   "solution": "BYPRODUCT",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 15,
   "clue": "Literary people blog Rob Roy, sum up novel (10,5)",
   "clueItalics": [
    [
     21,
     7
    ]
   ],
   "separatorLocations": {
    ",": [
     10
    ]
   },
   "solution": "BLOOMSBURYGROUP",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 15,
   "clue": "Act firmly to gain momentum (3,4,4,4)",
   "separatorLocations": {
    ",": [
     3,
     7,
     11
    ]
   },
   "solution": "PUTONESFOOTDOWN",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 7,
   "clue": "More than a couple of pounds altogether (7)",
   "separatorLocations": {},
   "solution": "OVERALL",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 9,
   "clue": "Constellation seen from Mars in our galaxy? (4,5)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "URSAMINOR",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 5,
   "clue": "Row about lodge's first doorkeeper (5)",
   "separatorLocations": {},
   "solution": "TILER",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 9,
   "clue": "Thorough? Off-target twice, apparently (3-3-3)",
   "separatorLocations": {
    "-": [
     3,
     6
    ]
   },
   "solution": "OUTANDOUT",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 2
   },
   "length": 5,
   "clue": "Treacherous type losing wife's support (5)",
   "separatorLocations": {},
   "solution": "EASEL",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 15,
   "clue": "Fragment Marlene forced out of wealthy landowner, perhaps (9-6)",
   "separatorLocations": {
    "-": [
     9
    ]
   },
   "solution": "GENTLEMANFARMER",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 5,
   "clue": "Storming start (5)",
   "separatorLocations": {},
   "solution": "ONSET",
   "annotation": null
  },
  {
   "id": "13-down",
   "number": 13,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 6
   },
   "length": 9,
   "clue": "Able to endure stormy weather was theory, unfortunately (9)",
   "separatorLocations": {},
   "solution": "SEAWORTHY",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 6
   },
   "length": 9,
   "clue": "Tennis player, contemptible on passenger ship? (9)",
   "separatorLocations": {},
   "solution": "BASELINER",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 6
   },
   "length": 9,
   "clue": "Tries during proper practice session (9)",
   "separatorLocations": {},
   "solution": "REHEARSAL",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 9,
   "clue": "Hope film director's put in new oratorio (4,2,3)",
   "separatorLocations": {
    ",": [
     4,
     6
    ]
   },
   "solution": "ROADTORIO",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 8
   },
   "length": 7,
   "clue": "Incredible bar in European capital (7)",
   "separatorLocations": {},
   "solution": "TALLINN",
   "annotation": null
  },
  {
   "id": "18-across",
   "number": 18,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 8
   },
   "length": 5,
   "clue": "Hare off across middle of neutral ground (5)",
   "separatorLocations": {},
   "solution": "EARTH",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 8
   },
   "length": 7,
   "clue": "Ecstasy obtained by tearaway, as a boost to self-esteem? (3,4)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "EGOTRIP",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 15,
   "clue": "Work for a pianist after the day job? (9,6)",
   "separatorLocations": {
    ",": [
     9
    ]
   },
   "solution": "MOONLIGHTSONATA",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 5,
   "clue": "Second suitable upturned design (5)",
   "separatorLocations": {},
   "solution": "MOTIF",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 10
   },
   "length": 5,
   "clue": "Boy losing book causes alarm (5)",
   "separatorLocations": {},
   "solution": "ALERT",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 5,
   "clue": "Expresses mild disapproval in front of one Bantu tribe member (5)",
   "separatorLocations": {},
   "solution": "TUTSI",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 12
   },
   "length": 9,
   "clue": "Lourdes so relaxing being free from smell (9)",
   "separatorLocations": {},
   "solution": "ODOURLESS",
   "annotation": null
  },
  {
   "id": "23-across",
   "number": 23,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 9,
   "clue": "Tiny fish in good bowl, item used by cook (6,3)",
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "FRYINGPAN",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 14
   },
   "length": 5,
   "clue": "Floral feature has tulip's head in centre of ring (5)",
   "separatorLocations": {},
   "solution": "PETAL",
   "annotation": null
  }
 ]
} /*JSON-END*/;
