// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["everyman-3419"] = /*JSON-START*/ {
 "id": "everyman-3419",
 "number": 3419,
 "series": "everyman",
 "name": "Everyman crossword No 3,419",
 "setter": "Everyman",
 "date": 1334448000000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/everyman/3419",
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 11,
   "clue": "Small article by Dali in Central American capital (3,8)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "SANSALVADOR",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 5,
   "clue": "Health resort in a European country (5)",
   "separatorLocations": {},
   "solution": "SPAIN",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 15,
   "clue": "Complex calculations made by anaesthetist? Crisis in middle of surgery (6-9)",
   "separatorLocations": {
    "-": [
     6
    ]
   },
   "solution": "NUMBERCRUNCHING",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 8,
   "clue": "Group of characters in sacred river requiring help (8)",
   "separatorLocations": {},
   "solution": "ALPHABET",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 6,
   "clue": "House housing a bad-tempered woman (6)",
   "separatorLocations": {},
   "solution": "VIRAGO",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 15,
   "clue": "Craftily, trader tempts one in a place on the high street (10,5)",
   "separatorLocations": {
    ",": [
     10
    ]
   },
   "solution": "DEPARTMENTSTORE",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 9,
   "clue": "Shrub grew on church official (4,5)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "ROSEELDER",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 1
   },
   "length": 6,
   "clue": "Rodent, second seen in trade centre (6)",
   "separatorLocations": {},
   "solution": "MARMOT",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 1
   },
   "length": 6,
   "clue": "A free BBC? (6)",
   "separatorLocations": {},
   "solution": "AUNTIE",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 5,
   "clue": "Put the wind up a member crossing line (5)",
   "separatorLocations": {},
   "solution": "ALARM",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 2
   },
   "length": 9,
   "clue": "Father in capital wants us brought over together (4,5)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "PARIPASSU",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 7,
   "clue": "Chap was the leader, coming over and heading for Admiral Nelson (7)",
   "separatorLocations": {},
   "solution": "MANDELA",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 4
   },
   "length": 7,
   "clue": "Gent has arm in an article of clothing (7)",
   "separatorLocations": {},
   "solution": "GARMENT",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 8,
   "clue": "Stateswoman - chat nervously with her after start of tribunal (8)",
   "separatorLocations": {},
   "solution": "THATCHER",
   "annotation": null
  },
  {
   "id": "14-down",
   "number": 14,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 6
   },
   "length": 9,
   "clue": "A ring brought in by governess for a religious leader (9)",
   "separatorLocations": {},
   "solution": "AYATOLLAH",
   "annotation": null
  },
  {
   "id": "15-across",
   "number": 15,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 6
   },
   "length": 6,
   "clue": "Streak across mud, getting immersed (6)",
   "separatorLocations": {},
   "solution": "SMUDGE",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 7
   },
   "length": 8,
   "clue": "Short signs for wrong and right beneath a puzzle (8)",
   "separatorLocations": {},
   "solution": "ACROSTIC",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 6,
   "clue": "American after a taxi back? You can count on it! (6)",
   "separatorLocations": {},
   "solution": "ABACUS",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 6,
   "clue": "Delegate, a southern character (6)",
   "separatorLocations": {},
   "solution": "ASSIGN",
   "annotation": null
  },
  {
   "id": "18-across",
   "number": 18,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 8
   },
   "length": 8,
   "clue": "So, a nicer new storyline (8)",
   "separatorLocations": {},
   "solution": "SCENARIO",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 8
   },
   "length": 6,
   "clue": "Key man, first to bat (6)",
   "separatorLocations": {},
   "solution": "OPENER",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 9
   },
   "length": 6,
   "clue": "Means to support a learner driver, whatever the circumstances (6)",
   "separatorLocations": {},
   "solution": "ALWAYS",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 7,
   "clue": "Long-suffering patient, uncomplaining (7)",
   "separatorLocations": {},
   "solution": "STOICAL",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 10
   },
   "length": 7,
   "clue": "Look at our Sunday paper, endlessly (7)",
   "separatorLocations": {},
   "solution": "OBSERVE",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 10
   },
   "length": 5,
   "clue": "Hot drink, not busker's first (5)",
   "separatorLocations": {},
   "solution": "RANDY",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 9,
   "clue": "Irritation shown by terrible Russian chap having little time to gad about (9)",
   "separatorLocations": {},
   "solution": "GALLIVANT",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 12
   },
   "length": 5,
   "clue": "The snow leopard, at one time around for all to see (5)",
   "separatorLocations": {},
   "solution": "OUNCE",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 2,
    "y": 14
   },
   "length": 11,
   "clue": "Excellent company making film (4,7)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "HIGHSOCIETY",
   "annotation": null
  }
 ]
} /*JSON-END*/;
