// Generated by tools/fetch_globeandmail.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["globeandmail-3126"] = /*JSON-START*/ {
 "id": "globeandmail-3126",
 "number": 3126,
 "series": "globeandmail",
 "name": "Globe and Mail cryptic crossword No 3,126",
 "setter": "Asp / ©News Licensing/Times Media Limited",
 "date": 1765238400000,
 "dimensions": {
  "cols": 13,
  "rows": 13
 },
 "sourceUrl": "https://www.theglobeandmail.com/puzzles-and-crosswords/new-cryptic/?date=20251209",
 "provenance": {
  "publisher": "Globe and Mail",
  "series": "globeandmail",
  "acquiredBy": "tools/fetch_globeandmail.py",
  "acquiredOn": "2026-09-17",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 8,
   "clue": "Odd article in Le Monde showing lack of sophistication (8)",
   "separatorLocations": {},
   "solution": "UNCOMMON",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 7,
   "clue": "Releases elite US troops to support peacekeeping force (7)",
   "separatorLocations": {},
   "solution": "UNSEALS",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 5,
   "clue": "Make a detailed plan of church painting and sculpture? (5)",
   "separatorLocations": {},
   "solution": "CHART",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 10,
   "clue": "One unable to shut up car opening (10)",
   "separatorLocations": {},
   "solution": "MOTORMOUTH",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 6,
   "clue": "Highly decorated knight coming in to deliver speech (6)",
   "separatorLocations": {},
   "solution": "ORNATE",
   "annotation": null
  },
  {
   "id": "5-across",
   "number": 5,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 0
   },
   "length": 4,
   "clue": "Prominent piece of land held by businessman (4)",
   "separatorLocations": {},
   "solution": "NESS",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 7,
   "clue": "English vicar’s first financial backer for any of the Gospels (7)",
   "separatorLocations": {},
   "solution": "EVANGEL",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 5,
   "clue": "Exhausted writer found in street (5)",
   "separatorLocations": {},
   "solution": "SPENT",
   "annotation": null
  },
  {
   "id": "8-across",
   "number": 8,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 8,
   "clue": "Line is removed from shocking opening (8)",
   "separatorLocations": {},
   "solution": "STARTING",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 2
   },
   "length": 4,
   "clue": "Podcaster’s way of running portal (4)",
   "separatorLocations": {},
   "solution": "GATE",
   "annotation": null
  },
  {
   "id": "10-down",
   "number": 10,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 3
   },
   "length": 10,
   "clue": "Roaming on coast via Canadian province (4,6)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "NOVASCOTIA",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 5,
   "clue": "Following source of financial news during tumultuous era (5)",
   "separatorLocations": {},
   "solution": "AFTER",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 4
   },
   "length": 7,
   "clue": "However, idiot finally had an idea (7)",
   "separatorLocations": {},
   "solution": "THOUGHT",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 6,
   "clue": "Salt spring? (6)",
   "separatorLocations": {},
   "solution": "SEASON",
   "annotation": null
  },
  {
   "id": "14-down",
   "number": 14,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 6
   },
   "length": 7,
   "clue": "Leader of American party unconcerned about others (7)",
   "separatorLocations": {},
   "solution": "ASOCIAL",
   "annotation": null
  },
  {
   "id": "15-across",
   "number": 15,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 6
   },
   "length": 6,
   "clue": "Everyone in Slough yielded to temptation (6)",
   "separatorLocations": {},
   "solution": "FALLEN",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 6
   },
   "length": 7,
   "clue": "How to identify someone 9 staff upset (7)",
   "separatorLocations": {},
   "solution": "NAMETAG",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 7
   },
   "length": 6,
   "clue": "Stick plug in this place (6)",
   "separatorLocations": {},
   "solution": "ADHERE",
   "annotation": null
  },
  {
   "id": "18-across",
   "number": 18,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 7,
   "clue": "Fool regularly ignored trendy set (7)",
   "separatorLocations": {},
   "solution": "CLOTTED",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 5,
   "clue": "Crude bombs made better (5)",
   "separatorLocations": {},
   "solution": "CURED",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 8
   },
   "length": 5,
   "clue": "Best part of dairy product (5)",
   "separatorLocations": {},
   "solution": "CREAM",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 8
   },
   "length": 5,
   "clue": "Resin obtained from bio-fuel emissions (5)",
   "separatorLocations": {},
   "solution": "ELEMI",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 4,
   "clue": "Control time in office for auditor (4)",
   "separatorLocations": {},
   "solution": "REIN",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 10
   },
   "length": 8,
   "clue": "Smashed TV set screening men’s formal attire (8)",
   "separatorLocations": {},
   "solution": "VESTMENT",
   "annotation": null
  },
  {
   "id": "23-across",
   "number": 23,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 4,
   "clue": "First person guided around shop (4)",
   "separatorLocations": {},
   "solution": "DELI",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 12
   },
   "length": 8,
   "clue": "Reprimanding despicable person’s boring existence (8)",
   "separatorLocations": {},
   "solution": "BERATING",
   "annotation": null
  }
 ]
} /*JSON-END*/;
