// Generated by tools/fetch_globeandmail.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["globeandmail-3127"] = /*JSON-START*/ {
 "id": "globeandmail-3127",
 "number": 3127,
 "series": "globeandmail",
 "name": "Globe and Mail cryptic crossword No 3,127",
 "setter": "Teazel / ©News Licensing/Times Media Limited",
 "date": 1765324800000,
 "dimensions": {
  "cols": 13,
  "rows": 13
 },
 "sourceUrl": "https://www.theglobeandmail.com/puzzles-and-crosswords/new-cryptic/?date=20251210",
 "provenance": {
  "publisher": "Globe and Mail",
  "series": "globeandmail",
  "acquiredBy": "tools/fetch_globeandmail.py",
  "acquiredOn": "2026-09-17",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 7,
   "clue": "Prudent, being consumed by worry? (7)",
   "separatorLocations": {},
   "solution": "CAREFUL",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 10,
   "clue": "Armistice broken by Charlie Potter (10)",
   "separatorLocations": {},
   "solution": "CERAMICIST",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 5,
   "clue": "Mat to hand for sport (5)",
   "separatorLocations": {},
   "solution": "RUGBY",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 9,
   "clue": "Close relative in Highland dance showing off (9)",
   "separatorLocations": {},
   "solution": "FLAUNTING",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 6,
   "clue": "Refuse group of newborn (6)",
   "separatorLocations": {},
   "solution": "LITTER",
   "annotation": null
  },
  {
   "id": "5-across",
   "number": 5,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 4,
   "clue": "Plunder big bag (4)",
   "separatorLocations": {},
   "solution": "SACK",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 3,
   "clue": "Juice: nothing odd in usual power (3)",
   "separatorLocations": {},
   "solution": "SAP",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 7,
   "clue": "Panic at changing leader (7)",
   "separatorLocations": {},
   "solution": "CAPTAIN",
   "annotation": null
  },
  {
   "id": "7-across",
   "number": 7,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 3,
   "clue": "From the start relish a good scrap (3)",
   "separatorLocations": {},
   "solution": "RAG",
   "annotation": null
  },
  {
   "id": "8-across",
   "number": 8,
   "direction": "across",
   "position": {
    "x": 4,
    "y": 2
   },
   "length": 8,
   "clue": "A new bit of advice: work with energy for unrecognised leader (8)",
   "separatorLocations": {},
   "solution": "ANTIPOPE",
   "annotation": null
  },
  {
   "id": "9-down",
   "number": 9,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 3
   },
   "length": 10,
   "clue": "Write feeble second half of letter in verse (10)",
   "separatorLocations": {},
   "solution": "PENTAMETER",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 5,
   "clue": "Old Central American person hides always (5)",
   "separatorLocations": {},
   "solution": "MAYAN",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 4
   },
   "length": 7,
   "clue": "Hug me back: steady! (7)",
   "separatorLocations": {},
   "solution": "EMBRACE",
   "annotation": null
  },
  {
   "id": "12-down",
   "number": 12,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 4
   },
   "length": 9,
   "clue": "Sign to leave miserable apostle (4,5)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "BLUEPETER",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 6,
   "clue": "Where knockout is likely, put ice out (3,3)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "CUPTIE",
   "annotation": null
  },
  {
   "id": "14-down",
   "number": 14,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 6
   },
   "length": 7,
   "clue": "Demonstrate in favour of trial (7)",
   "separatorLocations": {},
   "solution": "PROTEST",
   "annotation": null
  },
  {
   "id": "15-across",
   "number": 15,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 6
   },
   "length": 6,
   "clue": "Turning up, mean at last to score basket (6)",
   "separatorLocations": {},
   "solution": "PUNNET",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 7
   },
   "length": 6,
   "clue": "Request recording of a cascade of bells (6)",
   "separatorLocations": {},
   "solution": "APPEAL",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 7,
   "clue": "Temporary fix as apps got confused (7)",
   "separatorLocations": {},
   "solution": "STOPGAP",
   "annotation": null
  },
  {
   "id": "18-across",
   "number": 18,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 8
   },
   "length": 5,
   "clue": "Saint breaks into type of Sunday hymn (5)",
   "separatorLocations": {},
   "solution": "PSALM",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 8
   },
   "length": 5,
   "clue": "Make embarrassed in a party (5)",
   "separatorLocations": {},
   "solution": "ABASH",
   "annotation": null
  },
  {
   "id": "20-across",
   "number": 20,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 10
   },
   "length": 8,
   "clue": "Once more grab time off, trailing back (8)",
   "separatorLocations": {},
   "solution": "REARREST",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 10
   },
   "length": 3,
   "clue": "Polish most of gemstone (3)",
   "separatorLocations": {},
   "solution": "RUB",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 10
   },
   "length": 3,
   "clue": "Perhaps member of army finishing lieutenant (3)",
   "separatorLocations": {},
   "solution": "ANT",
   "annotation": null
  },
  {
   "id": "23-across",
   "number": 23,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 12
   },
   "length": 4,
   "clue": "Go and return potty (4)",
   "separatorLocations": {},
   "solution": "STAB",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 12
   },
   "length": 7,
   "clue": "Unsteady dog? (7)",
   "separatorLocations": {},
   "solution": "LURCHER",
   "annotation": null
  }
 ]
} /*JSON-END*/;
