// Generated by tools/fetch_globeandmail.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["globeandmail-3232"] = /*JSON-START*/ {
 "id": "globeandmail-3232",
 "number": 3232,
 "series": "globeandmail",
 "name": "Globe and Mail cryptic crossword No 3,232",
 "setter": "Pipsqueak",
 "date": 1775966400000,
 "dimensions": {
  "cols": 13,
  "rows": 13
 },
 "sourceUrl": "https://www.theglobeandmail.com/puzzles-and-crosswords/new-cryptic/?date=20260412",
 "provenance": {
  "publisher": "Globe and Mail",
  "series": "globeandmail",
  "acquiredBy": "tools/fetch_globeandmail.py",
  "acquiredOn": "2026-09-17",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 0
   },
   "length": 4,
   "clue": "Two personal assistants for old man (4)",
   "separatorLocations": {},
   "solution": "PAPA",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 0
   },
   "length": 6,
   "clue": "US state harbouring resistance fighter (6)",
   "separatorLocations": {},
   "solution": "MARINE",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 0
   },
   "length": 8,
   "clue": "Depart NY in turmoil, splitting hairs (8)",
   "separatorLocations": {},
   "solution": "PEDANTRY",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 0
   },
   "length": 4,
   "clue": "Contact attendant at court (4)",
   "separatorLocations": {},
   "solution": "PAGE",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 0
   },
   "length": 6,
   "clue": "Policeman, one managing to acquire power (6)",
   "separatorLocations": {},
   "solution": "COPPER",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 0
   },
   "length": 8,
   "clue": "No crossword setter could be so ignorant (8)",
   "separatorLocations": {},
   "solution": "CLUELESS",
   "annotation": null
  },
  {
   "id": "7-across",
   "number": 7,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 1
   },
   "length": 6,
   "clue": "Is monkey allowed to eat this? (6)",
   "separatorLocations": {},
   "solution": "CANAPE",
   "annotation": null
  },
  {
   "id": "8-across",
   "number": 8,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 1
   },
   "length": 6,
   "clue": "A vote, initially on name for space programme (6)",
   "separatorLocations": {},
   "solution": "APOLLO",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 3
   },
   "length": 8,
   "clue": "Confirm live data needs correcting (8)",
   "separatorLocations": {},
   "solution": "VALIDATE",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 3
   },
   "length": 4,
   "clue": "Support nobleman when caught (4)",
   "separatorLocations": {},
   "solution": "PIER",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 6,
   "clue": "Abandon the Sahara? (6)",
   "separatorLocations": {},
   "solution": "DESERT",
   "annotation": null
  },
  {
   "id": "12-down",
   "number": 12,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 5
   },
   "length": 8,
   "clue": "Ultimate net value to be adjusted (8)",
   "separatorLocations": {},
   "solution": "EVENTUAL",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 5
   },
   "length": 5,
   "clue": "Quietly recommend expulsion (5)",
   "separatorLocations": {},
   "solution": "PURGE",
   "annotation": null
  },
  {
   "id": "13-down",
   "number": 13,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 5
   },
   "length": 8,
   "clue": "What you might have at breakfast time in prison? (8)",
   "separatorLocations": {},
   "solution": "PORRIDGE",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 6
   },
   "length": 3,
   "clue": "Aussie native runs round and round (3)",
   "separatorLocations": {},
   "solution": "ROO",
   "annotation": null
  },
  {
   "id": "15-across",
   "number": 15,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 7
   },
   "length": 5,
   "clue": "Almost losing head at dawn? (5)",
   "separatorLocations": {},
   "solution": "EARLY",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 7
   },
   "length": 6,
   "clue": "Last of weather holding me up (6)",
   "separatorLocations": {},
   "solution": "REMAIN",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 7
   },
   "length": 6,
   "clue": "Careless about failure (6)",
   "separatorLocations": {},
   "solution": "REMISS",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 7
   },
   "length": 6,
   "clue": "Former Lothario hoards red wine (6)",
   "separatorLocations": {},
   "solution": "MERLOT",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 9
   },
   "length": 4,
   "clue": "Couple I encountered on way back (4)",
   "separatorLocations": {},
   "solution": "ITEM",
   "annotation": null
  },
  {
   "id": "20-across",
   "number": 20,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 9
   },
   "length": 8,
   "clue": "Tory I rip off is most pressing concern (8)",
   "separatorLocations": {},
   "solution": "PRIORITY",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 9
   },
   "length": 4,
   "clue": "Periodically protect man of letters (4)",
   "separatorLocations": {},
   "solution": "POET",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 9
   },
   "length": 4,
   "clue": "Outsiders expelled from Athens at that time (4)",
   "separatorLocations": {},
   "solution": "THEN",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 6,
   "clue": "Resident gullible about start of trouble (6)",
   "separatorLocations": {},
   "solution": "NATIVE",
   "annotation": null
  },
  {
   "id": "23-across",
   "number": 23,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 11
   },
   "length": 6,
   "clue": "Shopkeeper selling food increasingly vulgar, I hear (6)",
   "separatorLocations": {},
   "solution": "GROCER",
   "annotation": null
  }
 ]
} /*JSON-END*/;
