// Generated by tools/fetch_independent.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["independent-12016"] = /*JSON-START*/ {
 "id": "independent-12016",
 "number": 12016,
 "series": "independent",
 "name": "Independent cryptic crossword No 12,016",
 "setter": "Bluth",
 "date": 1744588800000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://puzzles.independent.co.uk/games/cryptic-crossword-independent/",
 "provenance": {
  "publisher": "Independent",
  "series": "independent",
  "acquiredBy": "tools/fetch_independent.py",
  "acquiredOn": "2026-09-17",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 0
   },
   "length": 10,
   "clue": "Profit-sheet he adjusted after discounting electronics – bargains can be found here (6,4)",
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "THRIFTSHOP",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 0
   },
   "length": 4,
   "clue": "Post office rejected a large gemstone ... (4)",
   "separatorLocations": {},
   "solution": "OPAL",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 0
   },
   "length": 15,
   "clue": "... or tasty apple (6,9)",
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "GOLDENDELICIOUS",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 0
   },
   "length": 4,
   "clue": "Almost mount deer (4)",
   "separatorLocations": {},
   "solution": "STAG",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 0
   },
   "length": 15,
   "clue": "Friends maybe setting my code incorrectly (9,6)",
   "separatorLocations": {
    ",": [
     9
    ]
   },
   "solution": "SITUATIONCOMEDY",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 0
   },
   "length": 4,
   "clue": "Funny scene in small outfit (4)",
   "separatorLocations": {},
   "solution": "SKIT",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 0
   },
   "length": 4,
   "clue": "After being connected – oddly disappearing (4)",
   "separatorLocations": {},
   "solution": "ONCE",
   "annotation": null
  },
  {
   "id": "8-across",
   "number": 8,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 1
   },
   "length": 15,
   "clue": "Supply hot kettle chips around noon – now things are getting interesting (3,4,8)",
   "separatorLocations": {
    ",": [
     3,
     7
    ]
   },
   "solution": "THEPLOTTHICKENS",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 3
   },
   "length": 5,
   "clue": "Papers and student journalist did nothing (5)",
   "separatorLocations": {},
   "solution": "IDLED",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 3
   },
   "length": 8,
   "clue": "Pinched Grant's glove (8)",
   "separatorLocations": {},
   "solution": "GAUNTLET",
   "annotation": null
  },
  {
   "id": "11-down",
   "number": 11,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 3
   },
   "length": 3,
   "clue": "Wreath that is left on the counter (3)",
   "separatorLocations": {},
   "solution": "LEI",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 4,
   "clue": "First episode has pace (4)",
   "separatorLocations": {},
   "solution": "STEP",
   "annotation": null
  },
  {
   "id": "13-down",
   "number": 13,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 5
   },
   "length": 5,
   "clue": "Old Iranian standard is raised (5)",
   "separatorLocations": {},
   "solution": "PARSI",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 5
   },
   "length": 10,
   "clue": "Part of workforce in evening dress (5,5)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "NIGHTSHIFT",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 5
   },
   "length": 5,
   "clue": "Finally melt butter on the outside as suggested (3,2)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "GOTAT",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 5
   },
   "length": 5,
   "clue": "Egg supplier fencing in a very safe place (5)",
   "separatorLocations": {},
   "solution": "HAVEN",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 5
   },
   "length": 10,
   "clue": "Give warning as climbing up red ash carelessly splits bark (10)",
   "separatorLocations": {},
   "solution": "FORESHADOW",
   "annotation": null
  },
  {
   "id": "18-across",
   "number": 18,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 7
   },
   "length": 13,
   "clue": "US President's in that woman's bed over and over again (7,6)",
   "separatorLocations": {
    ",": [
     7
    ]
   },
   "solution": "HERBERTHOOVER",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 9
   },
   "length": 10,
   "clue": "Curry for one after work, putting no-frills rice on first and expecting good stuff (10)",
   "separatorLocations": {},
   "solution": "OPTIMISTIC",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 9
   },
   "length": 3,
   "clue": "Advice: put mine back (3)",
   "separatorLocations": {},
   "solution": "TIP",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 9
   },
   "length": 4,
   "clue": "Realises in audition for feature (4)",
   "separatorLocations": {},
   "solution": "NOSE",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 8,
   "clue": "Extent of calcium deficiency not universal (8)",
   "separatorLocations": {},
   "solution": "CAPACITY",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 11
   },
   "length": 4,
   "clue": "Fine following morning on the rampage (4)",
   "separatorLocations": {},
   "solution": "AMOK",
   "annotation": null
  },
  {
   "id": "24-down",
   "number": 24,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 11
   },
   "length": 4,
   "clue": "High-pitch results when key fob is out of bounds (4)",
   "separatorLocations": {},
   "solution": "ALTO",
   "annotation": null
  },
  {
   "id": "25-down",
   "number": 25,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 11
   },
   "length": 4,
   "clue": "Perhaps 2001: A Space Odyssey ultimately used up Kubrick's focus (4)",
   "clueItalics": [
    [
     8,
     21
    ]
   ],
   "separatorLocations": {},
   "solution": "YEAR",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 11
   },
   "length": 5,
   "clue": "Second tea or coffee? (5)",
   "separatorLocations": {},
   "solution": "MOCHA",
   "annotation": null
  },
  {
   "id": "27-down",
   "number": 27,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 11
   },
   "length": 4,
   "clue": "Quickly learn stuff (4)",
   "separatorLocations": {},
   "solution": "CRAM",
   "annotation": null
  },
  {
   "id": "28-across",
   "number": 28,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 13
   },
   "length": 15,
   "clue": "Department store keep Gary Oldman's line out when broadcast (7,3,5)",
   "separatorLocations": {
    ",": [
     7,
     10
    ]
   },
   "solution": "FORTNUMANDMASON",
   "annotation": null
  }
 ]
} /*JSON-END*/;
