// Generated by tools/fetch_independent.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["independent-10557"] = /*JSON-START*/ {
 "id": "independent-10557",
 "number": 10557,
 "series": "independent",
 "name": "Independent cryptic crossword No 10,557",
 "setter": "Monk",
 "date": 1597276800000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://puzzles.independent.co.uk/games/cryptic-crossword-independent/",
 "entries": [
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 10,
   "clue": "Loves to go round 6 in which social workers leave kids? (10)",
   "separatorLocations": {},
   "solution": "HONEYCOMBS",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 8,
   "clue": "Signal not to go after a woman, one who wasn't ready? (8)",
   "separatorLocations": {},
   "solution": "ETHELRED",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 6,
   "clue": "Soon about to embrace vice, outwardly displaying devotion (6)",
   "separatorLocations": {},
   "solution": "NOVENA",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 8,
   "clue": "Attention -- quiet needed by Polish listening device (8)",
   "separatorLocations": {},
   "solution": "EARPHONE",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 6,
   "clue": "Queen's accommodation in Taipei, fairly regularly visited (6)",
   "separatorLocations": {},
   "solution": "APIARY",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 4,
   "clue": "Uncover a bit of northern Greek architecture (4)",
   "separatorLocations": {},
   "solution": "RAKE",
   "annotation": null
  },
  {
   "id": "7-across",
   "number": 7,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 1
   },
   "length": 7,
   "clue": "Working space satellite capturing salt lake, as an example (7)",
   "separatorLocations": {},
   "solution": "ONTARIO",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 1
   },
   "length": 5,
   "clue": "Proportion of speech discovered? (5)",
   "separatorLocations": {},
   "solution": "RATIO",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 1
   },
   "length": 7,
   "clue": "General, Italian American, one who holds broadcast (7)",
   "separatorLocations": {},
   "solution": "AGRIPPA",
   "annotation": null
  },
  {
   "id": "10-down",
   "number": 10,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 1
   },
   "length": 7,
   "clue": "Somehow limit a time when filling in summary (4-3)",
   "separatorLocations": {
    "-": [
     4
    ]
   },
   "solution": "RATECAP",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 3
   },
   "length": 5,
   "clue": "Turn out fine, ultimately about to go into black (5)",
   "separatorLocations": {},
   "solution": "EJECT",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 3
   },
   "length": 9,
   "clue": "Elaborate exile having run away (9)",
   "separatorLocations": {},
   "solution": "EXPATIATE",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 9,
   "clue": "Initially, chef's assistant on board cooked stew (9)",
   "separatorLocations": {},
   "solution": "CARBONADO",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 5
   },
   "length": 5,
   "clue": "Lines contributing to hollow praise (3,2)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "CRYUP",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 5
   },
   "length": 10,
   "clue": "Composed repeats in D flat? (10)",
   "separatorLocations": {},
   "solution": "PEDESTRIAN",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 7
   },
   "length": 15,
   "clue": "Some time in the past, padre blessed breadbasket (6-3,6)",
   "separatorLocations": {
    "-": [
     6
    ],
    ",": [
     9
    ]
   },
   "solution": "MIDDLEAGESPREAD",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 7
   },
   "length": 7,
   "clue": "Light, flavourless, plucked bird (7)",
   "separatorLocations": {},
   "solution": "LANTERN",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 7
   },
   "length": 8,
   "clue": "Supplement programme with part of game nine (8)",
   "separatorLocations": {},
   "solution": "APPENDIX",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 7
   },
   "length": 8,
   "clue": "Foreign appearance (8)",
   "separatorLocations": {},
   "solution": "EXTERIOR",
   "annotation": null
  },
  {
   "id": "20-across",
   "number": 20,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 9
   },
   "length": 5,
   "clue": "Offence involving small-time singer-songwriter, one of 12? (5)",
   "separatorLocations": {},
   "solution": "SIMON",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 9
   },
   "length": 6,
   "clue": "Stone workers present during roll call? (6)",
   "separatorLocations": {},
   "solution": "MENHIR",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 9
   },
   "length": 9,
   "clue": "Blithe Spirit only half reviewed, causing complaint (9)",
   "clueItalics": [
    [
     0,
     13
    ]
   ],
   "separatorLocations": {},
   "solution": "PHLEBITIS",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 9
   },
   "length": 6,
   "clue": "Where some go mainly to introduce daughter and dashing chap (6)",
   "separatorLocations": {},
   "solution": "LADDIE",
   "annotation": null
  },
  {
   "id": "24-down",
   "number": 24,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 9
   },
   "length": 5,
   "clue": "Resist old Irishman (5)",
   "separatorLocations": {},
   "solution": "BUCKO",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 9,
   "clue": "Business errand, extremely involved (9)",
   "separatorLocations": {},
   "solution": "CONCERNED",
   "annotation": null
  },
  {
   "id": "25-down",
   "number": 25,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 4,
   "clue": "Without having left, face familiar bloke (4)",
   "separatorLocations": {},
   "solution": "COCK",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 11
   },
   "length": 5,
   "clue": "European sacked in job tender (5)",
   "separatorLocations": {},
   "solution": "CARER",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 13
   },
   "length": 7,
   "clue": "EU character not for making EU wine (7)",
   "separatorLocations": {},
   "solution": "CHIANTI",
   "annotation": null
  },
  {
   "id": "28-across",
   "number": 28,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 13
   },
   "length": 7,
   "clue": "Woodlice poo said to be awful (7)",
   "separatorLocations": {},
   "solution": "ISOPODA",
   "annotation": null
  }
 ]
} /*JSON-END*/;
