// Generated by tools/fetch_independent.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["independent-10072"] = /*JSON-START*/ {
 "id": "independent-10072",
 "number": 10072,
 "series": "independent",
 "name": "Independent cryptic crossword No 10,072",
 "setter": "Serpent",
 "date": 1548288000000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://puzzles.independent.co.uk/games/cryptic-crossword-independent/",
 "provenance": {
  "publisher": "Independent",
  "series": "independent",
  "acquiredBy": "tools/fetch_independent.py",
  "acquiredOn": "2026-09-17",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 6,
   "clue": "Basket concealing case of sparkling wine (6)",
   "separatorLocations": {},
   "solution": "HAMPER",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 6,
   "clue": "Rubbish in derelict housing block (6)",
   "separatorLocations": {},
   "solution": "HINDER",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 6,
   "clue": "Very drunk person liable to die (6)",
   "separatorLocations": {},
   "solution": "MORTAL",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 10,
   "clue": "Energy emitted around the speed of light is annihilated (10)",
   "separatorLocations": {},
   "solution": "ERADICATED",
   "annotation": null
  },
  {
   "id": "4-across",
   "number": 4,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 0
   },
   "length": 8,
   "clue": "Uses model to encourage cycling outside (8)",
   "separatorLocations": {},
   "solution": "PURPOSES",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 4,
   "clue": "Heard you are in charge of number one (4)",
   "separatorLocations": {},
   "solution": "URIC",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 4,
   "clue": "Snobbish, but not winning sympathy (4)",
   "separatorLocations": {},
   "solution": "PITY",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 8,
   "clue": "One continuing to live with zero resistance against virus surprisingly (8)",
   "separatorLocations": {},
   "solution": "SURVIVOR",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 8,
   "clue": "American cops belt around carelessly (8)",
   "separatorLocations": {},
   "solution": "SLAPDASH",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 6,
   "clue": "Someone who's not British and not male (6)",
   "separatorLocations": {},
   "solution": "NORMAN",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 2
   },
   "length": 8,
   "clue": "State through with initial expansion according to NATO (8)",
   "separatorLocations": {},
   "solution": "VICTORIA",
   "annotation": null
  },
  {
   "id": "11-down",
   "number": 11,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 3
   },
   "length": 7,
   "clue": "Decided church school has to promote reading? (7)",
   "separatorLocations": {},
   "solution": "CERTAIN",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 8,
   "clue": "Tested revolutionary fabric cutter (8)",
   "separatorLocations": {},
   "solution": "EXAMINED",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 4
   },
   "length": 4,
   "clue": "Snake scared off everybody in the end (4)",
   "separatorLocations": {},
   "solution": "WIND",
   "annotation": null
  },
  {
   "id": "14-down",
   "number": 14,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 5
   },
   "length": 7,
   "clue": "Cook large quantity of coq au vin amid empty space (2,5)",
   "separatorLocations": {
    ",": [
     2
    ]
   },
   "solution": "INVACUO",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 5
   },
   "length": 10,
   "clue": "Update assignment to groups of engineers providing stylish shelters (10)",
   "separatorLocations": {},
   "solution": "RECLASSIFY",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 3,
    "y": 6
   },
   "length": 12,
   "clue": "Cross three-quarters of river on tin vessel (12)",
   "separatorLocations": {},
   "solution": "CANTANKEROUS",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 7
   },
   "length": 8,
   "clue": "Ends of 10 and 20 could be rendered identically (8)",
   "separatorLocations": {},
   "solution": "VERBATIM",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 7
   },
   "length": 8,
   "clue": "Write down almost everything and forget it (3,2,3)",
   "separatorLocations": {
    ",": [
     3,
     5
    ]
   },
   "solution": "NOTATALL",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 12,
   "clue": "Reality close to collapse in a mysterious way (12)",
   "separatorLocations": {},
   "solution": "ESOTERICALLY",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 9
   },
   "length": 6,
   "clue": "22 million stolen by Italian banker (6)",
   "separatorLocations": {},
   "solution": "TIMBER",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 9
   },
   "length": 6,
   "clue": "One set free following slight drop in temperature (6)",
   "separatorLocations": {},
   "solution": "UNITED",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 4,
   "clue": "Broadcast live in the morning (4)",
   "separatorLocations": {},
   "solution": "BEAM",
   "annotation": null
  },
  {
   "id": "23-across",
   "number": 23,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 10
   },
   "length": 8,
   "clue": "Doubt nothing will stop search happening (8)",
   "separatorLocations": {},
   "solution": "QUESTION",
   "annotation": null
  },
  {
   "id": "24-down",
   "number": 24,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 11
   },
   "length": 4,
   "clue": "Was aware of being left out (4)",
   "separatorLocations": {},
   "solution": "FELT",
   "annotation": null
  },
  {
   "id": "25-down",
   "number": 25,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 11
   },
   "length": 4,
   "clue": "One taking advantage of scheme right to the end (4)",
   "separatorLocations": {},
   "solution": "USER",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 8,
   "clue": "Cross with partygoers in centre of Cheltenham (8)",
   "separatorLocations": {},
   "solution": "TRAVERSE",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 12
   },
   "length": 6,
   "clue": "Where suspension took place having rejected substantial stake (6)",
   "separatorLocations": {},
   "solution": "GIBBET",
   "annotation": null
  },
  {
   "id": "28-across",
   "number": 28,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 8,
   "clue": "Services settled on being included in year end retrospectively (8)",
   "separatorLocations": {},
   "solution": "MILITARY",
   "annotation": null
  },
  {
   "id": "29-across",
   "number": 29,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 14
   },
   "length": 6,
   "clue": "Cross letters from grouchy bridegroom (6)",
   "separatorLocations": {},
   "solution": "HYBRID",
   "annotation": null
  }
 ]
} /*JSON-END*/;
