// Generated by tools/fetch_independent.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["independent-10764"] = /*JSON-START*/ {
 "id": "independent-10764",
 "number": 10764,
 "series": "independent",
 "name": "Independent cryptic crossword No 10,764",
 "setter": "Crosophile",
 "date": 1618272000000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://puzzles.independent.co.uk/games/cryptic-crossword-independent/",
 "provenance": {
  "publisher": "Independent",
  "series": "independent",
  "acquiredBy": "tools/fetch_independent.py",
  "acquiredOn": "2026-09-17",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 0
   },
   "length": 8,
   "clue": "Like these down entries and calm our nerves, just a bit churned up (8)",
   "separatorLocations": {},
   "solution": "COLUMNAR",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 0
   },
   "length": 10,
   "clue": "Fungus perhaps mostly evenly dispersed (10)",
   "separatorLocations": {},
   "solution": "SAPROPHYTE",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 0
   },
   "length": 6,
   "clue": "What’s left for instance in puddled clay (6)",
   "separatorLocations": {},
   "solution": "LEGACY",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 0
   },
   "length": 4,
   "clue": "Cut out central section of rough drawings (4)",
   "separatorLocations": {},
   "solution": "ETCH",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 0
   },
   "length": 8,
   "clue": "Attire of doctor in conflict with honour (8)",
   "separatorLocations": {},
   "solution": "WARDROBE",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 0
   },
   "length": 4,
   "clue": "Independent’s new head of telesales? On the contrary (4)",
   "separatorLocations": {},
   "solution": "ISNT",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 0
   },
   "length": 6,
   "clue": "A metal splinter I picked up (6)",
   "separatorLocations": {},
   "solution": "SILVER",
   "annotation": null
  },
  {
   "id": "8-across",
   "number": 8,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 1
   },
   "length": 6,
   "clue": "Five yoga exercises on European cruise (6)",
   "separatorLocations": {},
   "solution": "VOYAGE",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 1
   },
   "length": 8,
   "clue": "Broadcast mike in a van (8)",
   "separatorLocations": {},
   "solution": "TRANSMIT",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 3
   },
   "length": 8,
   "clue": "Transcend extravagant endless pain (8)",
   "separatorLocations": {},
   "solution": "OUTREACH",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 3
   },
   "length": 6,
   "clue": "District attorney initially thinks I have a case (6)",
   "separatorLocations": {},
   "solution": "DATIVE",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 6,
   "clue": "Smart game to play outside (6)",
   "separatorLocations": {},
   "solution": "SNAPPY",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 5
   },
   "length": 8,
   "clue": "How rook flapping by motorway gets a parasite (8)",
   "separatorLocations": {},
   "solution": "HOOKWORM",
   "annotation": null
  },
  {
   "id": "13-down",
   "number": 13,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 5
   },
   "length": 5,
   "clue": "Many a white one’s seen from rocky shore (5)",
   "separatorLocations": {},
   "solution": "HORSE",
   "annotation": null
  },
  {
   "id": "14-down",
   "number": 14,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 5
   },
   "length": 10,
   "clue": "Gnu edible when minced in boiled stew (10)",
   "separatorLocations": {},
   "solution": "WILDEBEEST",
   "annotation": null
  },
  {
   "id": "15-across",
   "number": 15,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 7
   },
   "length": 4,
   "clue": "Like a member of the military? (4)",
   "separatorLocations": {},
   "solution": "ARMY",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 7
   },
   "length": 5,
   "clue": "At any time that is weird (5)",
   "separatorLocations": {},
   "solution": "EERIE",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 7
   },
   "length": 8,
   "clue": "Take food into doorway for begging (8)",
   "separatorLocations": {},
   "solution": "ENTREATY",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 7
   },
   "length": 4,
   "clue": "Greeny-yellow mucus after wiping top of sleeve (4)",
   "separatorLocations": {},
   "solution": "LIME",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 7
   },
   "length": 8,
   "clue": "Wizard guy conceals all-American private intelligence (8)",
   "separatorLocations": {},
   "solution": "MAGICIAN",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 9
   },
   "length": 8,
   "clue": "Half out of uniform ointment on cut leg's rough (8)",
   "separatorLocations": {},
   "solution": "UNGENTLE",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 9
   },
   "length": 6,
   "clue": "Vitamin in one way and another gives protection for a cold (6)",
   "separatorLocations": {},
   "solution": "NIACIN",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 9
   },
   "length": 6,
   "clue": "Security needed for place on the border (6)",
   "separatorLocations": {},
   "solution": "PLEDGE",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 9
   },
   "length": 6,
   "clue": "Royal Navy invested in value (6)",
   "separatorLocations": {},
   "solution": "PRINCE",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 6,
   "clue": "Struggle to keep dry in a load of hay? (6)",
   "separatorLocations": {},
   "solution": "BATTLE",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 11
   },
   "length": 4,
   "clue": "It’s ending in aftermath (4)",
   "separatorLocations": {},
   "solution": "TERM",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 11
   },
   "length": 8,
   "clue": "Proof of a base immorality around hideout (8)",
   "separatorLocations": {},
   "solution": "EVIDENCE",
   "annotation": null
  },
  {
   "id": "24-down",
   "number": 24,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 11
   },
   "length": 4,
   "clue": "Start off banquet as one at table (4)",
   "separatorLocations": {},
   "solution": "EAST",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 13
   },
   "length": 8,
   "clue": "Russian fighter speeds and leaves country (8)",
   "separatorLocations": {},
   "solution": "MIGRATES",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 13
   },
   "length": 6,
   "clue": "Charlie, like so often, needing us to go easy (6)",
   "separatorLocations": {},
   "solution": "CASUAL",
   "annotation": null
  }
 ]
} /*JSON-END*/;
