// Generated by tools/fetch_independent.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["independent-8964"] = /*JSON-START*/ {
 "id": "independent-8964",
 "number": 8964,
 "series": "independent",
 "name": "Independent cryptic crossword No 8,964",
 "setter": "Dac",
 "date": 1436313600000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://puzzles.independent.co.uk/games/cryptic-crossword-independent/",
 "provenance": {
  "publisher": "Independent",
  "series": "independent",
  "acquiredBy": "tools/fetch_independent.py",
  "acquiredOn": "2026-09-18",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 4,
   "clue": "Post selection of Christmas tidings (4)",
   "separatorLocations": {},
   "solution": "MAST",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 10,
   "clue": "Island briefly manufactured a vehicle without petrol (10)",
   "separatorLocations": {},
   "solution": "MADAGASCAR",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 7,
   "clue": "Champion winning in tennis, perhaps (7)",
   "separatorLocations": {},
   "solution": "SUPPORT",
   "annotation": null
  },
  {
   "id": "3-across",
   "number": 3,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 0
   },
   "length": 10,
   "clue": "Member of wedding party travels, with mother in command (10)",
   "separatorLocations": {},
   "solution": "BRIDESMAID",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 6,
   "clue": "One singer at far end of Tower Bridge (6)",
   "separatorLocations": {},
   "solution": "RIALTO",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 8,
   "clue": "Confuse old man swallowing one medium-sized tranquilliser (8)",
   "separatorLocations": {},
   "solution": "DIAZEPAM",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 3,
   "clue": "Note used in Peruvian currency (3)",
   "separatorLocations": {},
   "solution": "SOL",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 7,
   "clue": "A repeated note lute played in small band (7)",
   "separatorLocations": {},
   "solution": "ANNULET",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 4,
   "clue": "Colour expert is terrible, by the sound of it (4)",
   "separatorLocations": {},
   "solution": "DYER",
   "annotation": null
  },
  {
   "id": "9-down",
   "number": 9,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 1
   },
   "length": 10,
   "clue": "Discussion about where indecisive people are found round about (10)",
   "separatorLocations": {},
   "solution": "CONFERENCE",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 7,
   "clue": "After brief decline, see graduate getting qualification (7)",
   "separatorLocations": {},
   "solution": "DIPLOMA",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 2
   },
   "length": 7,
   "clue": "Former president completely ruined? Not completely (7)",
   "separatorLocations": {},
   "solution": "ALLENDE",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 5,
   "clue": "Be mad to take sudden dislike to waders? (2,3,3,5)",
   "group": [
    "12-across",
    "13-across"
   ],
   "separatorLocations": {
    ",": [
     2,
     5
    ]
   },
   "solution": "GOOFF",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 4
   },
   "length": 8,
   "clue": "See 12",
   "group": [
    "12-across",
    "13-across"
   ],
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "THERAILS",
   "annotation": null
  },
  {
   "id": "14-down",
   "number": 14,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 4
   },
   "length": 10,
   "clue": "Shortly feel embarrassed during play about Lancashire town (10)",
   "separatorLocations": {},
   "solution": "ACCRINGTON",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 5
   },
   "length": 10,
   "clue": "Protect lad, waving implement - that's shocking! (6,4)",
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "CATTLEPROD",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 6,
   "clue": "Educated woman's bowled over by European lampoon (6)",
   "separatorLocations": {},
   "solution": "SATIRE",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 6
   },
   "length": 8,
   "clue": "US state axed army in old port (8)",
   "separatorLocations": {},
   "solution": "CALCUTTA",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 7
   },
   "length": 8,
   "clue": "A bit shattered, Henry covers only half of London sporting event (8)",
   "separatorLocations": {},
   "solution": "BIATHLON",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 8,
   "clue": "A writer fills page ten in French section of book (8)",
   "separatorLocations": {},
   "solution": "APPENDIX",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 8
   },
   "length": 7,
   "clue": "Key player is overshadowed by very good worker (7)",
   "separatorLocations": {},
   "solution": "PIANIST",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 8
   },
   "length": 6,
   "clue": "Quite shocked by partner's lead in card game (6)",
   "separatorLocations": {},
   "solution": "PIQUET",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 8
   },
   "length": 7,
   "clue": "Losing head, cuddle with a north African (7)",
   "separatorLocations": {},
   "solution": "UGANDAN",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 9
   },
   "length": 6,
   "clue": "Gives response concerning statutes (6)",
   "separatorLocations": {},
   "solution": "REACTS",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 10
   },
   "length": 8,
   "clue": "Achieves satisfactory standard in new Maths, Greek and - after vacation - English (5,3,5)",
   "group": [
    "24-across",
    "25-across"
   ],
   "separatorLocations": {
    ",": [
     5,
     8
    ]
   },
   "solution": "MAKESTHE",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 10
   },
   "length": 5,
   "clue": "See 24",
   "group": [
    "24-across",
    "25-across"
   ],
   "separatorLocations": {},
   "solution": "GRADE",
   "annotation": null
  },
  {
   "id": "26-down",
   "number": 26,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 4,
   "clue": "Coffee tax reduced after agreement from Merkel (4)",
   "separatorLocations": {},
   "solution": "JAVA",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 7,
   "clue": "She served David a litre of beer, you say? (7)",
   "separatorLocations": {},
   "solution": "ABIGAIL",
   "annotation": null
  },
  {
   "id": "28-down",
   "number": 28,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 12
   },
   "length": 3,
   "clue": "A small point that's relevant (3)",
   "separatorLocations": {},
   "solution": "APT",
   "annotation": null
  },
  {
   "id": "29-across",
   "number": 29,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 12
   },
   "length": 7,
   "clue": "Soup: food cardinal rejected (7)",
   "separatorLocations": {},
   "solution": "CHOWDER",
   "annotation": null
  },
  {
   "id": "30-across",
   "number": 30,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 10,
   "clue": "During day, ten can board a ship, showing intelligence (10)",
   "separatorLocations": {},
   "solution": "ASTUTENESS",
   "annotation": null
  },
  {
   "id": "31-across",
   "number": 31,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 14
   },
   "length": 4,
   "clue": "Mean biddy regularly withheld name (4)",
   "separatorLocations": {},
   "solution": "ENID",
   "annotation": null
  }
 ]
} /*JSON-END*/;
