// Generated by tools/fetch_independent.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["independent-9669"] = /*JSON-START*/ {
 "id": "independent-9669",
 "number": 9669,
 "series": "independent",
 "name": "Independent cryptic crossword No 9,669",
 "setter": "Kairos",
 "date": 1507507200000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://puzzles.independent.co.uk/games/cryptic-crossword-independent/",
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 0
   },
   "length": 14,
   "clue": "Entertaining and emotional description of film? (5-9)",
   "separatorLocations": {
    "-": [
     5
    ]
   },
   "solution": "LIGHTSENSITIVE",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 9,
   "clue": "Football team contend with audience (9)",
   "separatorLocations": {},
   "solution": "INTERVIEW",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 5,
   "clue": "Stylish seaman in Augustine's place? (5)",
   "separatorLocations": {},
   "solution": "HIPPO",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 9,
   "clue": "Images of one short promontory in vertebrae (9)",
   "separatorLocations": {},
   "solution": "SIMULACRA",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 5,
   "clue": "New Hebrides regularly excluded the socially inept (5)",
   "separatorLocations": {},
   "solution": "NERDS",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 9,
   "clue": "Before long editor injecting heroin becomes occupied (9)",
   "separatorLocations": {},
   "solution": "INHABITED",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 5,
   "clue": "Lyricist on panel game is a foreigner (5)",
   "separatorLocations": {},
   "solution": "IRAQI",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 7,
   "clue": "What banks do in a recession without capital is boring (7)",
   "separatorLocations": {},
   "solution": "ENDLESS",
   "annotation": null
  },
  {
   "id": "9-down",
   "number": 9,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 1
   },
   "length": 6,
   "clue": "Secure the heart of Ms Kendal? (6)",
   "separatorLocations": {},
   "solution": "ELICIT",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 5,
   "clue": "Drunk started to smoke (3,2)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "LITUP",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 2
   },
   "length": 9,
   "clue": "Everyone leaves US planner to capture Slough (9)",
   "separatorLocations": {},
   "solution": "MARSHLAND",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 7,
   "clue": "Ring drivers' organisation about transport facility (3,4)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "CARPOOL",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 4
   },
   "length": 7,
   "clue": "August’s subject, “Fruit” (7)",
   "separatorLocations": {},
   "solution": "SUBLIME",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 5,
   "clue": "Returning in local air transport is a test (5)",
   "separatorLocations": {},
   "solution": "TRIAL",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 6
   },
   "length": 9,
   "clue": "Heroic cricket side intent on woman leaving Mark (9)",
   "separatorLocations": {},
   "solution": "LEGENDARY",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 6
   },
   "length": 9,
   "clue": "Vicars tee off with advertising types (9)",
   "separatorLocations": {},
   "solution": "CREATIVES",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 6
   },
   "length": 9,
   "clue": "On record Geordie work unit returns retaining its vigour (9)",
   "separatorLocations": {},
   "solution": "EVERGREEN",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 6
   },
   "length": 9,
   "clue": "Late 19th Century men (9)",
   "separatorLocations": {},
   "solution": "VICTORIAN",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 9,
   "clue": "Reduce the quality of quilt filling? (9)",
   "separatorLocations": {},
   "solution": "DOWNGRADE",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 7,
   "clue": "Duke meets stranger tattooist? (7)",
   "separatorLocations": {},
   "solution": "DRUMMER",
   "annotation": null
  },
  {
   "id": "20-across",
   "number": 20,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 8
   },
   "length": 5,
   "clue": "Risked three diamonds (5)",
   "separatorLocations": {},
   "solution": "DICED",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 8
   },
   "length": 6,
   "clue": "Plan to remove signature! (6)",
   "separatorLocations": {},
   "solution": "DESIGN",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 7,
   "clue": "Drunken Viscount dumping Charlie for Peter? (7)",
   "separatorLocations": {},
   "solution": "USTINOV",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 10
   },
   "length": 5,
   "clue": "Medicine knocked back during vaccinotherapy (5)",
   "separatorLocations": {},
   "solution": "TONIC",
   "annotation": null
  },
  {
   "id": "24-down",
   "number": 24,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 10
   },
   "length": 5,
   "clue": "Refer to love in film (5)",
   "separatorLocations": {},
   "solution": "VIDEO",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 10
   },
   "length": 7,
   "clue": "Travels over stream heading off to see lizards (7)",
   "separatorLocations": {},
   "solution": "GECKOES",
   "annotation": null
  },
  {
   "id": "26-down",
   "number": 26,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 10
   },
   "length": 5,
   "clue": "Lady Grantham drinking British beer (5)",
   "separatorLocations": {},
   "solution": "COBRA",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 9,
   "clue": "Maltreat male composer we hear (9)",
   "separatorLocations": {},
   "solution": "MANHANDLE",
   "annotation": null
  },
  {
   "id": "28-across",
   "number": 28,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 12
   },
   "length": 5,
   "clue": "Jewellery changing hands in institute (5)",
   "separatorLocations": {},
   "solution": "BLING",
   "annotation": null
  },
  {
   "id": "29-across",
   "number": 29,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 14,
   "clue": "Range of dodgy horse while touring Indiana (5,9)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "ROCKYMOUNTAINS",
   "annotation": null
  }
 ]
} /*JSON-END*/;
