// Generated by tools/fetch_independent.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["independent-12195"] = /*JSON-START*/ {
 "id": "independent-12195",
 "number": 12195,
 "series": "independent",
 "name": "Independent cryptic crossword No 12,195",
 "setter": "Quince",
 "date": 1762560000000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://puzzles.independent.co.uk/games/cryptic-crossword-independent/",
 "provenance": {
  "publisher": "Independent",
  "series": "independent",
  "acquiredBy": "tools/fetch_independent.py",
  "acquiredOn": "2026-09-17",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 10,
   "clue": "Fed herb tea, settling down for the night (7,3)",
   "separatorLocations": {
    ",": [
     7
    ]
   },
   "solution": "FEATHERBED",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 4,
   "clue": "Family at first has trouble evacuating kids (4)",
   "separatorLocations": {},
   "solution": "FIBS",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 4,
   "clue": "Notice welcoming church offered great service (4)",
   "separatorLocations": {},
   "solution": "ACED",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 12,
   "clue": "Subtle design feature of Volkswagen dashboard (6,6)",
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "HIDDENAGENDA",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 7,
   "clue": "Artist sketches endless daily struggle (3,4)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "RATRACE",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 7,
   "clue": "Mess exposed murder deeds (7)",
   "separatorLocations": {},
   "solution": "ESCROWS",
   "annotation": null
  },
  {
   "id": "6-across",
   "number": 6,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 0
   },
   "length": 4,
   "clue": "Hammer thrower nicked the gold (4)",
   "separatorLocations": {},
   "solution": "THOR",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 10,
   "clue": "Do I hang on lipreader? Hm, on head occasionally (7,3)",
   "separatorLocations": {
    ",": [
     7
    ]
   },
   "solution": "HEARINGAID",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 10,
   "clue": "Redo, create anew! (10)",
   "separatorLocations": {},
   "solution": "REDECORATE",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 10,
   "clue": "Snack money primarily spent on credit (10)",
   "separatorLocations": {},
   "solution": "BREADSTICK",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 2
   },
   "length": 4,
   "clue": "Performer Sandra Bullock returns in part (4)",
   "separatorLocations": {},
   "solution": "BARD",
   "annotation": null
  },
  {
   "id": "11-down",
   "number": 11,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 3
   },
   "length": 12,
   "clue": "Polonius and King Hamlet perhaps taste sweet (6,6)",
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "DANISHPASTRY",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 3,
    "y": 4
   },
   "length": 12,
   "clue": "Wannabe influencer girl on Love Island has one account following me (12)",
   "clueItalics": [
    [
     27,
     11
    ]
   ],
   "separatorLocations": {},
   "solution": "MEGALOMANIAC",
   "annotation": null
  },
  {
   "id": "13-down",
   "number": 13,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 10,
   "clue": "Idiots delighted about marks in test (10)",
   "separatorLocations": {},
   "solution": "ASSESSMENT",
   "annotation": null
  },
  {
   "id": "14-down",
   "number": 14,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 5
   },
   "length": 10,
   "clue": "Overplay retro Jamaican music covers Kiss sampled (10)",
   "separatorLocations": {},
   "solution": "EXAGGERATE",
   "annotation": null
  },
  {
   "id": "15-across",
   "number": 15,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 7,
   "clue": "Way to preserve old copy for congressional record (3,4)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "SEXTAPE",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 6
   },
   "length": 7,
   "clue": "Spain's top footballer is one scoring openly (7)",
   "separatorLocations": {},
   "solution": "SWINGER",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 7,
   "clue": "Gates and Elon struggling to deliver on newcomers to Twitter? (7)",
   "separatorLocations": {},
   "solution": "EAGLETS",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 8
   },
   "length": 7,
   "clue": "Outrage two of Georgia's neighbours, briefly (7)",
   "separatorLocations": {},
   "solution": "SCANDAL",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 8
   },
   "length": 7,
   "clue": "Unfaithful type at his wit's end taking pill (7)",
   "separatorLocations": {},
   "solution": "ATHEIST",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 8
   },
   "length": 7,
   "clue": "Alpha males upset by a single buttercup (7)",
   "separatorLocations": {},
   "solution": "ANEMONE",
   "annotation": null
  },
  {
   "id": "20-across",
   "number": 20,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 12,
   "clue": "They could catch you by the way (5,7)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "SPEEDCAMERAS",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 11
   },
   "length": 4,
   "clue": "Wilder for one pool party? (4)",
   "separatorLocations": {},
   "solution": "GENE",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 11
   },
   "length": 4,
   "clue": "Setter and solver and editor getting exhausted (4)",
   "separatorLocations": {},
   "solution": "USED",
   "annotation": null
  },
  {
   "id": "23-across",
   "number": 23,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 4,
   "clue": "Seconds from leaving alehouse, have another spirit (4)",
   "separatorLocations": {},
   "solution": "ELAN",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 12
   },
   "length": 10,
   "clue": "Ron DeSantis about to axe new facility (10)",
   "separatorLocations": {},
   "solution": "ADROITNESS",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 4,
   "clue": "Who's responsible for wedding row? (4)",
   "separatorLocations": {},
   "solution": "TIER",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 14
   },
   "length": 10,
   "clue": "He's a deeply distressed person keen to retire (10)",
   "separatorLocations": {},
   "solution": "SLEEPYHEAD",
   "annotation": null
  }
 ]
} /*JSON-END*/;
