// Generated by tools/fetch_independent.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["independent-9261"] = /*JSON-START*/ {
 "id": "independent-9261",
 "number": 9261,
 "series": "independent",
 "name": "Independent cryptic crossword No 9,261",
 "setter": "Vigo",
 "date": 1466380800000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://puzzles.independent.co.uk/games/cryptic-crossword-independent/",
 "entries": [
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 0
   },
   "length": 10,
   "clue": "Boxers possibly step and run about (10)",
   "separatorLocations": {},
   "solution": "UNDERPANTS",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 0
   },
   "length": 6,
   "clue": "Knight accepting nothing, wanting nothing for something precious (6)",
   "separatorLocations": {},
   "solution": "SILVER",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 0
   },
   "length": 4,
   "clue": "Broadcast live with a mike (4)",
   "separatorLocations": {},
   "solution": "BEAM",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 0
   },
   "length": 8,
   "clue": "Delve about in waste matter to unearth ancestral line (8)",
   "separatorLocations": {},
   "solution": "PEDIGREE",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 0
   },
   "length": 4,
   "clue": "100% leather upholstery covers from bottom up (4)",
   "separatorLocations": {},
   "solution": "PURE",
   "annotation": null
  },
  {
   "id": "6-across",
   "number": 6,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 1
   },
   "length": 7,
   "clue": "Rebuild ruins in the Home Counties for star's first appearance of the day (7)",
   "separatorLocations": {},
   "solution": "SUNRISE",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 1
   },
   "length": 5,
   "clue": "12 fish (5)",
   "separatorLocations": {},
   "solution": "SKATE",
   "annotation": null
  },
  {
   "id": "7-across",
   "number": 7,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 1
   },
   "length": 5,
   "clue": "Provide European with gag (5)",
   "separatorLocations": {},
   "solution": "EQUIP",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 1
   },
   "length": 7,
   "clue": "Identify stench that's part of drug trial? (7)",
   "separatorLocations": {},
   "solution": "PLACEBO",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 3
   },
   "length": 4,
   "clue": "Film abuse in Hollywood (4)",
   "separatorLocations": {},
   "solution": "HAZE",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 3
   },
   "length": 10,
   "clue": "Temptress to rage and club furry mammal (7,3)",
   "separatorLocations": {
    ",": [
     7
    ]
   },
   "solution": "VAMPIREBAT",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 8,
   "clue": "A golfer is upset about start of previous game (8)",
   "separatorLocations": {},
   "solution": "LEAPFROG",
   "annotation": null
  },
  {
   "id": "12-down",
   "number": 12,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 5
   },
   "length": 5,
   "clue": "Leader ditches uniform for liberal way to move (5)",
   "separatorLocations": {},
   "solution": "GLIDE",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 5
   },
   "length": 6,
   "clue": "Retro Fairy King embraces without thinking (6)",
   "separatorLocations": {},
   "solution": "REFLEX",
   "annotation": null
  },
  {
   "id": "14-down",
   "number": 14,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 5
   },
   "length": 10,
   "clue": "Quaker's joint alliance (10)",
   "separatorLocations": {},
   "solution": "FRIENDSHIP",
   "annotation": null
  },
  {
   "id": "15-across",
   "number": 15,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 7
   },
   "length": 4,
   "clue": "A great number say missing beast (4)",
   "separatorLocations": {},
   "solution": "LION",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 7
   },
   "length": 7,
   "clue": "Ballpark popular with former player (7)",
   "separatorLocations": {},
   "solution": "INEXACT",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 7
   },
   "length": 5,
   "clue": "Race to reach Italian border exhausts front runners (5)",
   "separatorLocations": {},
   "solution": "TRIBE",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 7
   },
   "length": 8,
   "clue": "Male gets gold to propel ship into the future (8)",
   "separatorLocations": {},
   "solution": "TOMORROW",
   "annotation": null
  },
  {
   "id": "18-across",
   "number": 18,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 7
   },
   "length": 4,
   "clue": "Wildfowl dropping odd bits onto statue (4)",
   "separatorLocations": {},
   "solution": "IDOL",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 9
   },
   "length": 6,
   "clue": "Rubbish spread over alien sun (6)",
   "separatorLocations": {},
   "solution": "JETSAM",
   "annotation": null
  },
  {
   "id": "20-across",
   "number": 20,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 9
   },
   "length": 8,
   "clue": "Bearing designs affected tension (8)",
   "separatorLocations": {},
   "solution": "EDGINESS",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 9
   },
   "length": 6,
   "clue": "Go around empty gallery at speed (6)",
   "separatorLocations": {},
   "solution": "GYRATE",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 9
   },
   "length": 5,
   "clue": "Work out alone outside entrance to velodrome (5)",
   "separatorLocations": {},
   "solution": "SOLVE",
   "annotation": null
  },
  {
   "id": "23-across",
   "number": 23,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 10,
   "clue": "Man ruined by queen's uncle (10)",
   "separatorLocations": {},
   "solution": "PAWNBROKER",
   "annotation": null
  },
  {
   "id": "24-down",
   "number": 24,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 11
   },
   "length": 4,
   "clue": "Relation leaders of National Assembly never anticipated (4)",
   "separatorLocations": {},
   "solution": "NANA",
   "annotation": null
  },
  {
   "id": "25-down",
   "number": 25,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 11
   },
   "length": 4,
   "clue": "Vegetable ingredient in cock-a-leekie (4)",
   "separatorLocations": {},
   "solution": "KALE",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 11
   },
   "length": 4,
   "clue": "Material of special kind (4)",
   "separatorLocations": {},
   "solution": "SILK",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 13
   },
   "length": 5,
   "clue": "Fly back over steps (5)",
   "separatorLocations": {},
   "solution": "TANGO",
   "annotation": null
  },
  {
   "id": "28-across",
   "number": 28,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 13
   },
   "length": 7,
   "clue": "The French road race ditches on and off support for climbers (7)",
   "separatorLocations": {},
   "solution": "LATTICE",
   "annotation": null
  }
 ]
} /*JSON-END*/;
