// Generated by tools/fetch_independent.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["independent-11826"] = /*JSON-START*/ {
 "id": "independent-11826",
 "number": 11826,
 "series": "independent",
 "name": "Independent cryptic crossword No 11,826",
 "setter": "Filbert",
 "date": 1725408000000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://puzzles.independent.co.uk/games/cryptic-crossword-independent/",
 "provenance": {
  "publisher": "Independent",
  "series": "independent",
  "acquiredBy": "tools/fetch_independent.py",
  "acquiredOn": "2026-09-17",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 8,
   "clue": "Maybe bow's shot showing expertise in Sherwood? (8)",
   "separatorLocations": {},
   "solution": "FORESTRY",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 4,
   "clue": "Iron clothes in the morning for dance show (4)",
   "separatorLocations": {},
   "solution": "FAME",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 7,
   "clue": "Mark on uniform damaged in riot (3,4)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "RUNAMOK",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 11,
   "clue": "Manage at home with lovely nurse coming round (11)",
   "separatorLocations": {},
   "solution": "SUPERINTEND",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 9,
   "clue": "Scotsman had to bag trash in cleric's office (9)",
   "separatorLocations": {},
   "solution": "RABBINATE",
   "annotation": null
  },
  {
   "id": "5-across",
   "number": 5,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 0
   },
   "length": 6,
   "clue": "Chat about head of finance in taxi (6)",
   "separatorLocations": {},
   "solution": "CONFAB",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 3,
   "clue": "Fellow's outer door starts to open after knock (3)",
   "separatorLocations": {},
   "solution": "OAK",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 7,
   "clue": "Fast asleep after lying down (4,3)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "FLATOUT",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 10,
   "clue": "Notice sticker up in office electioneer vacated, supporting Clinton (4,6)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "BILLPOSTER",
   "annotation": null
  },
  {
   "id": "9-down",
   "number": 9,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 1
   },
   "length": 4,
   "clue": "Retail event that's small beer (4)",
   "separatorLocations": {},
   "solution": "SALE",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 5,
   "clue": "Pressure on football club to get some balls (3,2)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "MANUP",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 2
   },
   "length": 9,
   "clue": "Bar's last pot to clear up (9)",
   "separatorLocations": {},
   "solution": "BLACKBALL",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 2,
    "y": 4
   },
   "length": 13,
   "clue": "Cheers at the Olympics intensified (5,8)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "MERCIBEAUCOUP",
   "annotation": null
  },
  {
   "id": "13-down",
   "number": 13,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 4
   },
   "length": 11,
   "clue": "OK, what might a flea-ridden bear get in winter? (2,2,7)",
   "separatorLocations": {
    ",": [
     2,
     4
    ]
   },
   "solution": "UPTOSCRATCH",
   "annotation": null
  },
  {
   "id": "14-down",
   "number": 14,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 10,
   "clue": "Expensive stuff in the window at GAP sells badly (5,5)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "PLATEGLASS",
   "annotation": null
  },
  {
   "id": "15-across",
   "number": 15,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 5,
   "clue": "Compare Liz with Boris's predecessor - we mustn't have her back (5)",
   "separatorLocations": {},
   "solution": "LIKEN",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 6
   },
   "length": 9,
   "clue": "New tea set Pip wants (9)",
   "separatorLocations": {},
   "solution": "APPETITES",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 6
   },
   "length": 9,
   "clue": "Favourite uncle manipulated with a childish impatience (9)",
   "separatorLocations": {},
   "solution": "PETULANCE",
   "annotation": null
  },
  {
   "id": "18-across",
   "number": 18,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 9,
   "clue": "American's hat trick putting European record in danger (9)",
   "separatorLocations": {},
   "solution": "THREEPEAT",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 8
   },
   "length": 7,
   "clue": "Oven one opens touching hot potato (7)",
   "separatorLocations": {},
   "solution": "ROASTIE",
   "annotation": null
  },
  {
   "id": "20-across",
   "number": 20,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 8
   },
   "length": 5,
   "clue": "Several crosses mark battlefield (5)",
   "separatorLocations": {},
   "solution": "SOMME",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 8
   },
   "length": 7,
   "clue": "Labour in 2024? A lot are switching (3,4)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "MANYEAR",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 13,
   "clue": "Issue of one's own, when phoney Dr Chandler Bing releases book (13)",
   "separatorLocations": {},
   "solution": "GRANDCHILDREN",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 10
   },
   "length": 4,
   "clue": "Rwandan who also must be heard (4)",
   "separatorLocations": {},
   "solution": "HUTU",
   "annotation": null
  },
  {
   "id": "24-down",
   "number": 24,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 11
   },
   "length": 4,
   "clue": "Unknown priest going to heaven, incredibly (4)",
   "separatorLocations": {},
   "solution": "VERY",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 9,
   "clue": "Aunt short of time keeps mislabelled fruit machine (9)",
   "separatorLocations": {},
   "solution": "AUTOMATON",
   "annotation": null
  },
  {
   "id": "26-down",
   "number": 26,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 12
   },
   "length": 3,
   "clue": "Online supervisor sulks, removing 50% of content (3)",
   "separatorLocations": {},
   "solution": "MOD",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 12
   },
   "length": 5,
   "clue": "Don't worry about her elephant hides (5)",
   "separatorLocations": {},
   "solution": "THERE",
   "annotation": null
  },
  {
   "id": "28-across",
   "number": 28,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 6,
   "clue": "Meter made by Siemens went round (6)",
   "separatorLocations": {},
   "solution": "SPEEDO",
   "annotation": null
  },
  {
   "id": "29-across",
   "number": 29,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 14
   },
   "length": 8,
   "clue": "Reluctance to move grey hat fixed on lady's head (8)",
   "separatorLocations": {},
   "solution": "LETHARGY",
   "annotation": null
  }
 ]
} /*JSON-END*/;
