// Generated by tools/fetch_independent.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["independent-11541"] = /*JSON-START*/ {
 "id": "independent-11541",
 "number": 11541,
 "series": "independent",
 "name": "Independent cryptic crossword No 11,541",
 "setter": "Methuselah",
 "date": 1696636800000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://puzzles.independent.co.uk/games/cryptic-crossword-independent/",
 "entries": [
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 8,
   "clue": "Parasitic imp struggling with vicar (8)",
   "separatorLocations": {},
   "solution": "VAMPIRIC",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 6,
   "clue": "In role of monarch, heir ignores son's latest quote (6,5)",
   "group": [
    "2-down",
    "27-across"
   ],
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "ASKING",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 8,
   "clue": "Little creature's become large one, according to Spooner (8)",
   "separatorLocations": {},
   "solution": "MONGOOSE",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 6,
   "clue": "Some of us live dangerously around sources of temptation (6)",
   "separatorLocations": {},
   "solution": "DEVILS",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 8,
   "clue": "Charlie more or less gets through drunken toast without slurring (8)",
   "separatorLocations": {},
   "solution": "STACCATO",
   "annotation": null
  },
  {
   "id": "6-across",
   "number": 6,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 1
   },
   "length": 5,
   "clue": "Blokes with love for power causing havoc (5)",
   "separatorLocations": {},
   "solution": "CHAOS",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 1
   },
   "length": 6,
   "clue": "Conservative senior's not so hot (6)",
   "separatorLocations": {},
   "solution": "COLDER",
   "annotation": null
  },
  {
   "id": "7-across",
   "number": 7,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 1
   },
   "length": 9,
   "clue": "Nose put out of joint by shameless suggestions (9)",
   "separatorLocations": {},
   "solution": "OVERTONES",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 1
   },
   "length": 5,
   "clue": "Sisters gathering round letter in Sense and Sensibility? (5)",
   "clueItalics": [
    [
     34,
     21
    ]
   ],
   "separatorLocations": {},
   "solution": "NOUNS",
   "annotation": null
  },
  {
   "id": "9-down",
   "number": 9,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 1
   },
   "length": 6,
   "clue": "Solver repeatedly excoriated Methuselah cryptic (6)",
   "separatorLocations": {},
   "solution": "SLEUTH",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 3
   },
   "length": 7,
   "clue": "Drinking buddy knocked back beer shortly before golf (7)",
   "separatorLocations": {},
   "solution": "LAPPING",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 3
   },
   "length": 7,
   "clue": "Don't forget: I like skinny-dippers to swallow chlorine (7)",
   "separatorLocations": {},
   "solution": "INCLUDE",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 9,
   "clue": "Very bad egg seizes on signs of debt (9)",
   "separatorLocations": {},
   "solution": "EGREGIOUS",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 5
   },
   "length": 5,
   "clue": "Private property where hound doesn't need lead (5)",
   "separatorLocations": {},
   "solution": "ASSET",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 2,
    "y": 7
   },
   "length": 11,
   "clue": "DCIs troop about, keeping eyes peeled for correctional officers (4,7)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "COPYEDITORS",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 7
   },
   "length": 8,
   "clue": "Multilingual talking parrot ultimately sitting on fortune (8)",
   "separatorLocations": {},
   "solution": "POLYGLOT",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 7
   },
   "length": 8,
   "clue": "Writer's skewering trendy piece of music straight away (2,2,4)",
   "separatorLocations": {
    ",": [
     2,
     4
    ]
   },
   "solution": "INNOTIME",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 7
   },
   "length": 8,
   "clue": "In the end, students carry stories about half-cut academic across whole institution (8)",
   "separatorLocations": {},
   "solution": "SYSTEMIC",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 6,
   "clue": "Damsel's rescue secured by knights, perhaps (6)",
   "separatorLocations": {},
   "solution": "MAIDEN",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 8
   },
   "length": 6,
   "clue": "Buttons turned up volume right before end of pantomime (6)",
   "separatorLocations": {},
   "solution": "REMOTE",
   "annotation": null
  },
  {
   "id": "20-across",
   "number": 20,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 9
   },
   "length": 5,
   "clue": "Has Portillo oddly dropped May's predecessor? (5)",
   "separatorLocations": {},
   "solution": "APRIL",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 9
   },
   "length": 5,
   "clue": "One quarter of peace-mongering outfit (5)",
   "separatorLocations": {},
   "solution": "RINGO",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 9
   },
   "length": 9,
   "clue": "Look after recording of game played by Venus and Serena Williams? (9)",
   "separatorLocations": {},
   "solution": "TENNESSEE",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 9
   },
   "length": 6,
   "clue": "A cool comeback finally written into Bond film (6)",
   "separatorLocations": {},
   "solution": "TALKIE",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 9
   },
   "length": 6,
   "clue": "Delighted empty nesters romped atop pantry table, initially (6)",
   "separatorLocations": {},
   "solution": "ENRAPT",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 7,
   "clue": "Irish county's accomplished - another's losing its way (7)",
   "separatorLocations": {},
   "solution": "DONEGAL",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 11
   },
   "length": 7,
   "clue": "Striker sent off after starting on a sub (7)",
   "separatorLocations": {},
   "solution": "TORPEDO",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 13
   },
   "length": 9,
   "clue": "Some lingo in need of circulation (9)",
   "separatorLocations": {},
   "solution": "NEOLOGISM",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 13
   },
   "length": 5,
   "clue": "See 2",
   "group": [
    "2-down",
    "27-across"
   ],
   "separatorLocations": {},
   "solution": "PRICE",
   "annotation": null
  }
 ]
} /*JSON-END*/;
