// Generated by tools/fetch_independent.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["indysunday-1434"] = /*JSON-START*/ {
 "id": "indysunday-1434",
 "number": 1434,
 "series": "indysunday",
 "name": "Independent on Sunday cryptic crossword No 1,434",
 "setter": "Kairos",
 "date": 1503187200000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://puzzles.independent.co.uk/games/cryptic-crossword-independent/",
 "provenance": {
  "publisher": "Independent",
  "series": "indysunday",
  "acquiredBy": "tools/fetch_independent.py",
  "acquiredOn": "2026-09-17",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 4,
   "clue": "Expression of annoyance over principal (4)",
   "separatorLocations": {},
   "solution": "STAR",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 10,
   "clue": "Receipts from small beer fall on board ship (5,5)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "SALESSLIPS",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 7,
   "clue": "A county council regrets increases (7)",
   "separatorLocations": {},
   "solution": "ACCRUES",
   "annotation": null
  },
  {
   "id": "3-across",
   "number": 3,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 0
   },
   "length": 10,
   "clue": "Gets thorny shrub for Capability Brown? (10)",
   "separatorLocations": {},
   "solution": "LANDSCAPER",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 9,
   "clue": "Foolishly points at a dish (9)",
   "separatorLocations": {},
   "solution": "ANTIPASTO",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 5,
   "clue": "Challenged measure adopted by theologian (5)",
   "separatorLocations": {},
   "solution": "DARED",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 7,
   "clue": "Powerful people defile old Schutzstaffel unit (7)",
   "separatorLocations": {},
   "solution": "COLOSSI",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 7,
   "clue": "Language of paper supporting sarcastic fellow leaving Punch (7)",
   "separatorLocations": {},
   "solution": "PUNJABI",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 4,
   "clue": "Corrosive effect of Russia over time (4)",
   "separatorLocations": {},
   "solution": "RUST",
   "annotation": null
  },
  {
   "id": "9-down",
   "number": 9,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 1
   },
   "length": 6,
   "clue": "Hand book, say, to leading lady (6)",
   "separatorLocations": {},
   "solution": "WORKER",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 7,
   "clue": "Leave work heading off for bar (7)",
   "separatorLocations": {},
   "solution": "LOCKOUT",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 2
   },
   "length": 7,
   "clue": "Yields the Spanish received in payments (7)",
   "separatorLocations": {},
   "solution": "RELENTS",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 7,
   "clue": "Without resistance began to be high and mighty (5-2)",
   "separatorLocations": {
    "-": [
     5
    ]
   },
   "solution": "STUCKUP",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 4
   },
   "length": 6,
   "clue": "Policeman's mother beginning to yell alarm (6)",
   "separatorLocations": {},
   "solution": "DISMAY",
   "annotation": null
  },
  {
   "id": "14-down",
   "number": 14,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 5
   },
   "length": 10,
   "clue": "Group of foreigners touring Luxembourg (10)",
   "separatorLocations": {},
   "solution": "STRANGLERS",
   "annotation": null
  },
  {
   "id": "15-across",
   "number": 15,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 5,
   "clue": "Scientific instrument used in catalase research (5)",
   "separatorLocations": {},
   "solution": "LASER",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 6
   },
   "length": 9,
   "clue": "Left winger arranged last sit-in (9)",
   "separatorLocations": {},
   "solution": "STALINIST",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 6
   },
   "length": 9,
   "clue": "Imbalance of my tyres man briefly realigned (9)",
   "separatorLocations": {},
   "solution": "ASYMMETRY",
   "annotation": null
  },
  {
   "id": "18-across",
   "number": 18,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 9,
   "clue": "Meanness of charge over ecclesiastical offence (9)",
   "separatorLocations": {},
   "solution": "PARSIMONY",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 8
   },
   "length": 7,
   "clue": "Snubs those who love religious education? (7)",
   "separatorLocations": {},
   "solution": "REBUFFS",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 8
   },
   "length": 7,
   "clue": "Island artist meets old priest and King David? (7)",
   "separatorLocations": {},
   "solution": "ISRAELI",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 8
   },
   "length": 5,
   "clue": "Present a plant (5)",
   "separatorLocations": {},
   "solution": "HOSTA",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 8
   },
   "length": 6,
   "clue": "Intensely passionate leader changes to become nasty (6)",
   "separatorLocations": {},
   "solution": "HORRID",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 8
   },
   "length": 7,
   "clue": "Certain to assimilate East Indian Zone in attack (7)",
   "separatorLocations": {},
   "solution": "SEIZURE",
   "annotation": null
  },
  {
   "id": "23-across",
   "number": 23,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 10
   },
   "length": 6,
   "clue": "Native spitting out one drink away from the mouth (6)",
   "separatorLocations": {},
   "solution": "ABORAL",
   "annotation": null
  },
  {
   "id": "24-down",
   "number": 24,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 10
   },
   "length": 5,
   "clue": "Subsequently coming up in adventure tale ... (5)",
   "separatorLocations": {},
   "solution": "LATER",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 10
   },
   "length": 7,
   "clue": "Utter desolation before noon (7)",
   "separatorLocations": {},
   "solution": "MORNING",
   "annotation": null
  },
  {
   "id": "26-down",
   "number": 26,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 4,
   "clue": "... Tolkien's beginning to crush monster with twisted metal band (4)",
   "separatorLocations": {},
   "solution": "TORC",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 7,
   "clue": "Oddball to attend on officer (7)",
   "separatorLocations": {},
   "solution": "OFFBEAT",
   "annotation": null
  },
  {
   "id": "28-across",
   "number": 28,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 12
   },
   "length": 7,
   "clue": "Tax credit (7)",
   "separatorLocations": {},
   "solution": "TRIBUTE",
   "annotation": null
  },
  {
   "id": "29-across",
   "number": 29,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 10,
   "clue": "Cover over Nissan car beginning to stop radiation (6,4)",
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "COSMICRAYS",
   "annotation": null
  },
  {
   "id": "30-across",
   "number": 30,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 14
   },
   "length": 4,
   "clue": "Means to enter Cambridge College we hear (4)",
   "separatorLocations": {},
   "solution": "KEYS",
   "annotation": null
  }
 ]
} /*JSON-END*/;
