// Generated by tools/fetch_independent.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["indysunday-1768"] = /*JSON-START*/ {
 "id": "indysunday-1768",
 "number": 1768,
 "series": "indysunday",
 "name": "Independent on Sunday cryptic crossword No 1,768",
 "setter": "Tees",
 "date": 1705190400000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://puzzles.independent.co.uk/games/cryptic-crossword-independent/",
 "entries": [
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 8,
   "clue": "Respected English horse touring Middle East (8)",
   "separatorLocations": {},
   "solution": "ESTEEMED",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 6,
   "clue": "Manager charged with change, Harlow's ending season last in table (6,12)",
   "group": [
    "2-down",
    "4-down",
    "8-down"
   ],
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "WALTER",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 10,
   "clue": "Sound clear and brilliant inside skull — is this needed? (7,3)",
   "separatorLocations": {
    ",": [
     7
    ]
   },
   "solution": "HEARINGAID",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 6,
   "clue": "See 2",
   "group": [
    "2-down",
    "4-down",
    "8-down"
   ],
   "separatorLocations": {},
   "solution": "WINTER",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 8,
   "clue": "More safe crackers triggering alarm? (8)",
   "separatorLocations": {},
   "solution": "FEARSOME",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 4,
   "clue": "Neptunian feature regularly seen that spews lava (4)",
   "separatorLocations": {},
   "solution": "ETNA",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 8,
   "clue": "World's response where Conservative rises (8)",
   "separatorLocations": {},
   "solution": "CREATION",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 6,
   "clue": "See 2",
   "group": [
    "2-down",
    "4-down",
    "8-down"
   ],
   "separatorLocations": {},
   "solution": "BOTTOM",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 1
   },
   "length": 9,
   "clue": "Room tiny arachnid enters backwards — it has four dimensions (5-4)",
   "separatorLocations": {
    "-": [
     5
    ]
   },
   "solution": "SPACETIME",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 1
   },
   "length": 5,
   "clue": "Strange sort of force leaving dismembered body (5)",
   "separatorLocations": {},
   "solution": "TORSO",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 3
   },
   "length": 5,
   "clue": "Metallica finally exiting festival compound (5)",
   "separatorLocations": {},
   "solution": "ESTER",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 3
   },
   "length": 9,
   "clue": "Brawling woman to call Turkish leader, not without guts (9)",
   "separatorLocations": {},
   "solution": "TERMAGANT",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 7,
   "clue": "Sailor runs into sea, extremely eager (7)",
   "separatorLocations": {},
   "solution": "MARINER",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 5
   },
   "length": 7,
   "clue": "Mansion rebuilt for personal pleasure (7)",
   "separatorLocations": {},
   "solution": "ONANISM",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 5
   },
   "length": 10,
   "clue": "Supremely evil influence in Chartist reforms (10)",
   "separatorLocations": {},
   "solution": "ANTICHRIST",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 7
   },
   "length": 5,
   "clue": "American rotter holding Henry back in Russian cottage (5)",
   "separatorLocations": {},
   "solution": "DACHA",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 7
   },
   "length": 8,
   "clue": "Dish with seafood: chicken to follow (8)",
   "separatorLocations": {},
   "solution": "COCKTAIL",
   "annotation": null
  },
  {
   "id": "18-across",
   "number": 18,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 7
   },
   "length": 3,
   "clue": "Proper contest shortened (3)",
   "separatorLocations": {},
   "solution": "DUE",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 7
   },
   "length": 8,
   "clue": "Kid arrested by police inspector, put away for attack (8)",
   "separatorLocations": {},
   "solution": "DIATRIBE",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 7
   },
   "length": 5,
   "clue": "End of sunbathing? Make tracks for dance (5)",
   "separatorLocations": {},
   "solution": "TANGO",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 7
   },
   "length": 8,
   "clue": "Insider from Acton wrongly claiming prize (8)",
   "separatorLocations": {},
   "solution": "OCCUPANT",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 9
   },
   "length": 7,
   "clue": "Atlantic Provinces bordering right rural idyll (7)",
   "separatorLocations": {},
   "solution": "ARCADIA",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 9
   },
   "length": 6,
   "clue": "Cold in HGV in polar region (6)",
   "separatorLocations": {},
   "solution": "ARCTIC",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 9
   },
   "length": 7,
   "clue": "Short French article perhaps coming to a point? (7)",
   "separatorLocations": {},
   "solution": "LACONIC",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 9
   },
   "length": 6,
   "clue": "Secure gold in horse-drawn carriage (6)",
   "separatorLocations": {},
   "solution": "LANDAU",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 9
   },
   "length": 6,
   "clue": "Drink downed noisily at bar after opening (6)",
   "separatorLocations": {},
   "solution": "NECTAR",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 11
   },
   "length": 9,
   "clue": "Vessel crossing river in southwest — atomic boat (9)",
   "separatorLocations": {},
   "solution": "CATAMARAN",
   "annotation": null
  },
  {
   "id": "25-down",
   "number": 25,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 11
   },
   "length": 4,
   "clue": "Sheep's flesh not being cooked for dog (4)",
   "separatorLocations": {},
   "solution": "MUTT",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 11
   },
   "length": 5,
   "clue": "State main points again where MP bans duke (5)",
   "separatorLocations": {},
   "solution": "RECAP",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 13
   },
   "length": 5,
   "clue": "Tees had the ne plus ultra, ensnaring old fool (5)",
   "clueItalics": [
    [
     13,
     13
    ]
   ],
   "separatorLocations": {},
   "solution": "IDIOT",
   "annotation": null
  },
  {
   "id": "28-across",
   "number": 28,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 13
   },
   "length": 9,
   "clue": "Seaman stole this empty wagon (9)",
   "separatorLocations": {},
   "solution": "BOATSWAIN",
   "annotation": null
  }
 ]
} /*JSON-END*/;
