// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["quiptic-813"] = /*JSON-START*/ {
 "id": "quiptic-813",
 "number": 813,
 "series": "quiptic",
 "name": "Quiptic crossword No 813",
 "setter": "Provis",
 "date": 1434326400000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/quiptic/813",
 "provenance": {
  "publisher": "Guardian",
  "series": "quiptic",
  "acquiredBy": "tools/fetch_puzzle.py",
  "acquiredOn": "2026-09-18",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 8,
   "clue": "Change to a nicer garment that is particularly striking (8)",
   "separatorLocations": {},
   "solution": "CREATION",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 6,
   "clue": "Copper starts to suspect traffic officer's methadone habit (6)",
   "separatorLocations": {},
   "solution": "CUSTOM",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 6,
   "clue": "Involve former reservists in line-up (6)",
   "separatorLocations": {},
   "solution": "ENTAIL",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 6,
   "clue": "Vegetable rotation is supported by final 20% of membership (6)",
   "separatorLocations": {},
   "solution": "TURNIP",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 10,
   "clue": "Expose rogue as incredibly immoderate (10)",
   "separatorLocations": {},
   "solution": "OUTRAGEOUS",
   "annotation": null
  },
  {
   "id": "5-across",
   "number": 5,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 0
   },
   "length": 6,
   "clue": "Flipping games leads to tantrums (6)",
   "separatorLocations": {},
   "solution": "STROPS",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 8,
   "clue": "Shorten time to dash about at the back (8)",
   "separatorLocations": {},
   "solution": "TRUNCATE",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 8,
   "clue": "Degree in golf management (8)",
   "separatorLocations": {},
   "solution": "ORDERING",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 8,
   "clue": "Parted from Sun journalist over German article (8)",
   "separatorLocations": {},
   "solution": "SUNDERED",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 8,
   "clue": "Swamp rat in US ate bananas (8)",
   "separatorLocations": {},
   "solution": "SATURATE",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 2
   },
   "length": 6,
   "clue": "Load of dye heartlessly dumped in stream (6)",
   "separatorLocations": {},
   "solution": "BURDEN",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 8,
   "clue": "Gold I trap by a lake is not fake (8)",
   "separatorLocations": {},
   "solution": "ORIGINAL",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 4
   },
   "length": 6,
   "clue": "Mark's chief executive initially hard to find (6)",
   "separatorLocations": {},
   "solution": "SCARCE",
   "annotation": null
  },
  {
   "id": "13-down",
   "number": 13,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 5
   },
   "length": 10,
   "clue": "Quiet individual on drugs cartel is opening up (10)",
   "separatorLocations": {},
   "solution": "PIONEERING",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 6
   },
   "length": 10,
   "clue": "Work in secret as an underground movement (10)",
   "separatorLocations": {},
   "solution": "RESISTANCE",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 7
   },
   "length": 8,
   "clue": "Head lied about preceding unemployment (8)",
   "separatorLocations": {},
   "solution": "IDLENESS",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 7
   },
   "length": 8,
   "clue": "It starts with a star's flutter (8)",
   "separatorLocations": {},
   "solution": "ALPHABET",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 7
   },
   "length": 8,
   "clue": "Content to fingerprint rude Russian gatecrasher (8)",
   "separatorLocations": {},
   "solution": "INTRUDER",
   "annotation": null
  },
  {
   "id": "18-across",
   "number": 18,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 10,
   "clue": "State inquest changes its final direction for offender (10)",
   "separatorLocations": {},
   "solution": "DELINQUENT",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 9
   },
   "length": 6,
   "clue": "Fashionable sister does't hesitate to make firm demands (6)",
   "separatorLocations": {},
   "solution": "INSIST",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 9
   },
   "length": 6,
   "clue": "Consequence of Ulster struggle (6)",
   "separatorLocations": {},
   "solution": "RESULT",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 9
   },
   "length": 6,
   "clue": "Regularly sick at finish, after a climb (6)",
   "separatorLocations": {},
   "solution": "ASCEND",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 6,
   "clue": "Spur is a feature of Sussex horticulture (6)",
   "separatorLocations": {},
   "solution": "EXHORT",
   "annotation": null
  },
  {
   "id": "23-across",
   "number": 23,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 10
   },
   "length": 8,
   "clue": "Invaders reduced by half after nasty winds (8)",
   "separatorLocations": {},
   "solution": "MEANDERS",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 6,
   "clue": "Represent group on the fringes of eco-terrorism (6)",
   "separatorLocations": {},
   "solution": "EMBODY",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 12
   },
   "length": 8,
   "clue": "Make fun of independent investigator endlessly breaking the law (8)",
   "separatorLocations": {},
   "solution": "RIDICULE",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 6,
   "clue": "Stitch uterus after an operation (6)",
   "separatorLocations": {},
   "solution": "SUTURE",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 14
   },
   "length": 8,
   "clue": "Upset a barrier protecting Italian diamonds (8)",
   "separatorLocations": {},
   "solution": "AGITATED",
   "annotation": null
  }
 ]
} /*JSON-END*/;
