// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["quiptic-1063"] = /*JSON-START*/ {
 "id": "quiptic-1063",
 "number": 1063,
 "series": "quiptic",
 "name": "Quiptic crossword No 1,063",
 "setter": "Hectence",
 "date": 1585526400000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/quiptic/1063",
 "provenance": {
  "publisher": "Guardian",
  "series": "quiptic",
  "acquiredBy": "tools/fetch_puzzle.py",
  "acquiredOn": "2026-09-17",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 6,
   "clue": "Select the French relish (6)",
   "separatorLocations": {},
   "solution": "PICKLE",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 7,
   "clue": "Catch up with 1 across left incomplete (7)",
   "separatorLocations": {},
   "solution": "PARTIAL",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 5,
   "clue": "Tweet about redhead with cool clothing (5)",
   "separatorLocations": {},
   "solution": "CHIRP",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 9,
   "clue": "We call son about things happening near home (5,4)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "LOCALNEWS",
   "annotation": null
  },
  {
   "id": "4-across",
   "number": 4,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 7,
   "clue": "Lady's half cut after quite strange drink (7)",
   "separatorLocations": {},
   "solution": "TEQUILA",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 7,
   "clue": "High grade knowledge crammed in can be absorbed (5,2)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "TAKENIN",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 5,
   "clue": "Share question on team regularly (5)",
   "separatorLocations": {},
   "solution": "QUOTA",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 9,
   "clue": "Feeling for Greenlander with temperature inside home about zero (9)",
   "separatorLocations": {},
   "solution": "INTUITION",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 6,
   "clue": "Allowed one good journalist to follow soldiers (6)",
   "separatorLocations": {},
   "solution": "AGREED",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 1
   },
   "length": 6,
   "clue": "Rats maybe found inside? Never mind! (6)",
   "separatorLocations": {},
   "solution": "VERMIN",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 9,
   "clue": "Examine said rule first to get ticket that's valid later (4,5)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "RAINCHECK",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 2
   },
   "length": 5,
   "clue": "Animal taking over English river's eating tons (5)",
   "separatorLocations": {},
   "solution": "OTTER",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 5,
   "clue": "Urge politician to block stupid lie (5)",
   "separatorLocations": {},
   "solution": "IMPEL",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 4
   },
   "length": 9,
   "clue": "Often Mum's describing an unknown era (4,1,4)",
   "separatorLocations": {
    ",": [
     4,
     5
    ]
   },
   "solution": "MANYATIME",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 7,
   "clue": "Bird comes down shortly before light (7)",
   "separatorLocations": {},
   "solution": "LANTERN",
   "annotation": null
  },
  {
   "id": "14-down",
   "number": 14,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 6
   },
   "length": 9,
   "clue": "Chart-topping song has Eno making a comeback (6,3)",
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "NUMBERONE",
   "annotation": null
  },
  {
   "id": "15-across",
   "number": 15,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 6
   },
   "length": 6,
   "clue": "Idiot returned money with reduction (6)",
   "separatorLocations": {},
   "solution": "NITWIT",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 6
   },
   "length": 9,
   "clue": "Sad story reported dog and old women seized by enemy (4,2,3)",
   "separatorLocations": {
    ",": [
     4,
     6
    ]
   },
   "solution": "TALEOFWOE",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 8
   },
   "length": 6,
   "clue": "Delighted with a thought (6)",
   "separatorLocations": {},
   "solution": "AMUSED",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 8
   },
   "length": 7,
   "clue": "Decline evil calls (5,2)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "DROPSIN",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 8
   },
   "length": 7,
   "clue": "North American scientific establishment rejected church correspondence (7)",
   "separatorLocations": {},
   "solution": "BALANCE",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 8
   },
   "length": 6,
   "clue": "King and Queen welcomed in niche bread shop (6)",
   "separatorLocations": {},
   "solution": "BAKERY",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 8
   },
   "length": 7,
   "clue": "Absolutely demand extremes of loyalty (7)",
   "separatorLocations": {},
   "solution": "EXACTLY",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 9
   },
   "length": 6,
   "clue": "Heading off and travelling #amazed (6)",
   "separatorLocations": {},
   "solution": "AGHAST",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 9,
   "clue": "Grouses about window finally breaking, putting a thousand on estimate (9)",
   "separatorLocations": {},
   "solution": "GUESSWORK",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 10
   },
   "length": 5,
   "clue": "Locates reported tourist attractions (5)",
   "separatorLocations": {},
   "solution": "SITES",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 10
   },
   "length": 5,
   "clue": "Home game includes last in a series (5)",
   "separatorLocations": {},
   "solution": "OMEGA",
   "annotation": null
  },
  {
   "id": "25-down",
   "number": 25,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 10
   },
   "length": 5,
   "clue": "Equal odds in final game against English partners (5)",
   "separatorLocations": {},
   "solution": "EVENS",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 5,
   "clue": "Seaman's forbidden in the vicinity (5)",
   "separatorLocations": {},
   "solution": "ABOUT",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 12
   },
   "length": 9,
   "clue": "Most intelligent rodent without hesitation in desert (9)",
   "separatorLocations": {},
   "solution": "SHREWDEST",
   "annotation": null
  },
  {
   "id": "28-across",
   "number": 28,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 7,
   "clue": "Tortured senator for disloyalty (7)",
   "separatorLocations": {},
   "solution": "TREASON",
   "annotation": null
  },
  {
   "id": "29-across",
   "number": 29,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 14
   },
   "length": 6,
   "clue": "Producer of milk with thick top (6)",
   "separatorLocations": {},
   "solution": "JERSEY",
   "annotation": null
  }
 ]
} /*JSON-END*/;
