// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["quiptic-472"] = /*JSON-START*/ {
 "id": "quiptic-472",
 "number": 472,
 "series": "quiptic",
 "name": "Quiptic crossword No 472",
 "setter": "Beale",
 "date": 1228089600000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/quiptic/472",
 "provenance": {
  "publisher": "Guardian",
  "series": "quiptic",
  "acquiredBy": "tools/fetch_puzzle.py",
  "acquiredOn": "2026-09-18",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 7,
   "clue": "Panto character, often pressed (7)",
   "separatorLocations": {},
   "solution": "BUTTONS",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 4,
   "clue": "Speculate about a defeat (4)",
   "separatorLocations": {},
   "solution": "BEAT",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 2,
    "y": 0
   },
   "length": 15,
   "clue": "React calmly to failure of mixture in the hot cake tin (4,2,2,3,4)",
   "separatorLocations": {
    ",": [
     4,
     6,
     8,
     11
    ]
   },
   "solution": "TAKEITONTHECHIN",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 0
   },
   "length": 6,
   "clue": "Single approach is not mutual (3-3)",
   "separatorLocations": {
    "-": [
     3
    ]
   },
   "solution": "ONEWAY",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 0
   },
   "length": 6,
   "clue": "Agent takes shelter inside when tired (6)",
   "separatorLocations": {},
   "solution": "SLEEPY",
   "annotation": null
  },
  {
   "id": "5-across",
   "number": 5,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 7,
   "clue": "Fit message inside a page (7)",
   "separatorLocations": {},
   "solution": "CAPABLE",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 8,
   "clue": "Man taken to health centre gets cold (8)",
   "separatorLocations": {},
   "solution": "CLINICAL",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 0
   },
   "length": 8,
   "clue": "Cue pilot to change dressing (8)",
   "separatorLocations": {},
   "solution": "POULTICE",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 12,
    "y": 0
   },
   "length": 15,
   "clue": "Confidentially, this is what keeps us apart (7,3,3,2)",
   "separatorLocations": {
    ",": [
     7,
     10,
     13
    ]
   },
   "solution": "BETWEENYOUANDME",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 0
   },
   "length": 10,
   "clue": "People who make one cross? (10)",
   "separatorLocations": {},
   "solution": "ELECTORATE",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 5,
   "clue": "Has no right to hurt part of the body (5)",
   "separatorLocations": {},
   "solution": "ANKLE",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 2
   },
   "length": 9,
   "clue": "Rules are anyhow quite alien at the start and finish (9)",
   "separatorLocations": {},
   "solution": "ETIQUETTE",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 4
   },
   "length": 14,
   "clue": "Frustration of man turning up to meeting (14)",
   "separatorLocations": {},
   "solution": "DISAPPOINTMENT",
   "annotation": null
  },
  {
   "id": "12-down",
   "number": 12,
   "direction": "down",
   "position": {
    "x": 0,
    "y": 5
   },
   "length": 10,
   "clue": "Drink until one man returns, beaten to a pulp (10)",
   "separatorLocations": {},
   "solution": "LIQUIDISED",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 4,
   "clue": "Fashionable to retain company image (4)",
   "separatorLocations": {},
   "solution": "ICON",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 6
   },
   "length": 8,
   "clue": "Birdman, having left once, strangely goes into RAF on return (8)",
   "separatorLocations": {},
   "solution": "FALCONER",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 4,
    "y": 7
   },
   "length": 8,
   "clue": "Campaigns somehow scared us (8)",
   "separatorLocations": {},
   "solution": "CRUSADES",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 6,
    "y": 7
   },
   "length": 8,
   "clue": "Theatrical training? (4,4)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "ROLEPLAY",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 8,
   "clue": "Concealed? Or rule it out? (8)",
   "separatorLocations": {},
   "solution": "ULTERIOR",
   "annotation": null
  },
  {
   "id": "18-across",
   "number": 18,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 8
   },
   "length": 4,
   "clue": "Pay for a measure (4)",
   "separatorLocations": {},
   "solution": "FOOT",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 8,
    "y": 9
   },
   "length": 6,
   "clue": "Look to bring in publicity for article (6)",
   "separatorLocations": {},
   "solution": "LEADER",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 10,
    "y": 9
   },
   "length": 6,
   "clue": "Small stones left by tomb (6)",
   "separatorLocations": {},
   "solution": "GRAVEL",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 14,
   "clue": "It's uniform practice for the cast (5,9)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "DRESSREHEARSAL",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 14,
    "y": 11
   },
   "length": 4,
   "clue": "Grow less pale before the end (4)",
   "separatorLocations": {},
   "solution": "WANE",
   "annotation": null
  },
  {
   "id": "23-across",
   "number": 23,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 9,
   "clue": "Foreign duchess nearly went first as planned (9)",
   "separatorLocations": {},
   "solution": "SCHEDULED",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 12
   },
   "length": 5,
   "clue": "In the museum do go back to ask, finally, for a drink (5)",
   "separatorLocations": {},
   "solution": "VODKA",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 7,
   "clue": "Titled woman half missed horrible family (7)",
   "separatorLocations": {},
   "solution": "DYNASTY",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 14
   },
   "length": 7,
   "clue": "Help go through it again, putting in extra energy (7)",
   "separatorLocations": {},
   "solution": "RELIEVE",
   "annotation": null
  }
 ]
} /*JSON-END*/;
