// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["quiptic-43"] = /*JSON-START*/ {
 "id": "quiptic-43",
 "number": 43,
 "series": "quiptic",
 "name": "Quiptic crossword No 43",
 "setter": "Arachne",
 "date": 968630400000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/quiptic/43",
 "provenance": {
  "publisher": "Guardian",
  "series": "quiptic",
  "acquiredBy": "tools/fetch_puzzle.py",
  "acquiredOn": "2026-09-18",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 0
   },
   "length": 6,
   "clue": "Knickers made from mixed fibres (6)",
   "separatorLocations": {},
   "solution": "BRIEFS",
   "annotation": null
  },
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 0
   },
   "length": 7,
   "clue": "007's over age for sexual activity (7)",
   "separatorLocations": {},
   "solution": "BONDAGE",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 0
   },
   "length": 5,
   "clue": "Imbecile Amin, heartless outcast (5)",
   "separatorLocations": {},
   "solution": "IDIOT",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 0
   },
   "length": 7,
   "clue": "Cheat violinist (7)",
   "separatorLocations": {},
   "solution": "FIDDLER",
   "annotation": null
  },
  {
   "id": "4-across",
   "number": 4,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 6,
   "clue": "Six involved in endless trial for minor matters (6)",
   "separatorLocations": {},
   "solution": "TRIVIA",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 0
   },
   "length": 6,
   "clue": "Eager to return to take in good Caribbean music (6)",
   "separatorLocations": {},
   "solution": "REGGAE",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 0
   },
   "length": 9,
   "clue": "Confirms TV deal is a fix (9)",
   "separatorLocations": {},
   "solution": "VALIDATES",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 0
   },
   "length": 7,
   "clue": "Changed key with broken reed (7)",
   "separatorLocations": {},
   "solution": "ALTERED",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 1
   },
   "length": 13,
   "clue": "Blair first term is in disarray (5,8)",
   "separatorLocations": {
    ",": [
     5
    ]
   },
   "solution": "PRIMEMINISTER",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 4,
   "clue": "Against taking refuge in Byzantium (4)",
   "separatorLocations": {},
   "solution": "ANTI",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 2
   },
   "length": 10,
   "clue": "Greed: oddly acceptable socially and, after due time, free from controls (10)",
   "separatorLocations": {},
   "solution": "DEREGULATE",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 6,
   "clue": "Blended palest soft colour (6)",
   "separatorLocations": {},
   "solution": "PASTEL",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 4
   },
   "length": 8,
   "clue": "Wanders randomly and pointlessly after me (8)",
   "separatorLocations": {},
   "solution": "MEANDERS",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 9,
   "clue": "Sensational play upset moral dame (9)",
   "separatorLocations": {},
   "solution": "MELODRAMA",
   "annotation": null
  },
  {
   "id": "14-down",
   "number": 14,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 6
   },
   "length": 9,
   "clue": "Cry for each beheaded native worker (9)",
   "separatorLocations": {},
   "solution": "OPERATIVE",
   "annotation": null
  },
  {
   "id": "15-across",
   "number": 15,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 6
   },
   "length": 4,
   "clue": "Casanova initially seemed too unutterably debauched (4)",
   "separatorLocations": {},
   "solution": "STUD",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 8
   },
   "length": 4,
   "clue": "Walk backward, darlings! (4)",
   "separatorLocations": {},
   "solution": "STEP",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 8
   },
   "length": 7,
   "clue": "Reverend gentleman who 'watched birds'? (7)",
   "separatorLocations": {},
   "solution": "SPOONER",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 8
   },
   "length": 9,
   "clue": "Constantly object to Liberal:  'e's cunning! (9)",
   "separatorLocations": {},
   "solution": "ENDLESSLY",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 8
   },
   "length": 7,
   "clue": "Love affair involving Liam (not married) with a boy (7)",
   "separatorLocations": {},
   "solution": "LIAISON",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 8
   },
   "length": 7,
   "clue": "Gamble a pound on animal: we hear why (7)",
   "separatorLocations": {},
   "solution": "LOTTERY",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 9
   },
   "length": 6,
   "clue": "Wildly praise Hope (6)",
   "separatorLocations": {},
   "solution": "ASPIRE",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 8,
   "clue": "Maureen and girls making something from sugar (8)",
   "separatorLocations": {},
   "solution": "MOLASSES",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 10
   },
   "length": 6,
   "clue": "Part of die-cast utensil is sharp (6)",
   "separatorLocations": {},
   "solution": "ASTUTE",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 10
   },
   "length": 5,
   "clue": "Boozer involved in a secret operation (5)",
   "separatorLocations": {},
   "solution": "TOPER",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 10,
   "clue": "Mess and jumble suit Dennis (10)",
   "separatorLocations": {},
   "solution": "UNTIDINESS",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 12
   },
   "length": 4,
   "clue": "American writer, male, produces verse (4)",
   "separatorLocations": {},
   "solution": "POEM",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 14
   },
   "length": 6,
   "clue": "Joint production by Coral and Elizabeth (6)",
   "separatorLocations": {},
   "solution": "REEFER",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 14
   },
   "length": 6,
   "clue": "Generally breaking down, losing all force (6)",
   "separatorLocations": {},
   "solution": "ENERGY",
   "annotation": null
  }
 ]
} /*JSON-END*/;
