// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["quiptic-1051"] = /*JSON-START*/ {
 "id": "quiptic-1051",
 "number": 1051,
 "series": "quiptic",
 "name": "Quiptic crossword No 1,051",
 "setter": "Matilda",
 "date": 1578268800000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/quiptic/1051",
 "entries": [
  {
   "id": "1-across",
   "number": 1,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 0
   },
   "length": 7,
   "clue": "Know-how that hurts in the media (7)",
   "separatorLocations": {},
   "solution": "PROWESS",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 0
   },
   "length": 7,
   "clue": "Soldier's right: a pistol backfired (7)",
   "separatorLocations": {},
   "solution": "REGULAR",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 0
   },
   "length": 5,
   "clue": "Jam and a piece of cheese? (5)",
   "separatorLocations": {},
   "solution": "WEDGE",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 0
   },
   "length": 7,
   "clue": "City bird on the water (7)",
   "separatorLocations": {},
   "solution": "SWANSEA",
   "annotation": null
  },
  {
   "id": "5-across",
   "number": 5,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 0
   },
   "length": 7,
   "clue": "Moves up since first of challenges is over (7)",
   "separatorLocations": {},
   "solution": "ASCENDS",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 0
   },
   "length": 6,
   "clue": "The way to get a six-pack? It's in drinks (3-3)",
   "separatorLocations": {
    "-": [
     3
    ]
   },
   "solution": "SITUPS",
   "annotation": null
  },
  {
   "id": "7-down",
   "number": 7,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 0
   },
   "length": 9,
   "clue": "Again, come out for self-styled VIP (9)",
   "separatorLocations": {},
   "solution": "EGOMANIAC",
   "annotation": null
  },
  {
   "id": "8-down",
   "number": 8,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 0
   },
   "length": 7,
   "clue": "Fancy mash, Your Grace? (7)",
   "separatorLocations": {},
   "solution": "DUCHESS",
   "annotation": null
  },
  {
   "id": "9-down",
   "number": 9,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 1
   },
   "length": 13,
   "clue": "Can Simon Armitage drive with this? (6,7)",
   "separatorLocations": {
    ",": [
     6
    ]
   },
   "solution": "POETICLICENCE",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 2
   },
   "length": 4,
   "clue": "Venerable part of tragedy (4)",
   "separatorLocations": {},
   "solution": "AGED",
   "annotation": null
  },
  {
   "id": "11-across",
   "number": 11,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 2
   },
   "length": 10,
   "clue": "Caress most of bottom frequently to begin with (one's amenable) (1,4,5)",
   "separatorLocations": {
    ",": [
     1,
     5
    ]
   },
   "solution": "ASOFTTOUCH",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 4
   },
   "length": 6,
   "clue": "Trees could be 10 (6)",
   "separatorLocations": {},
   "solution": "ELDERS",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 4
   },
   "length": 8,
   "clue": "We part at revolting Adam's Ale (3,5)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "TAPWATER",
   "annotation": null
  },
  {
   "id": "14-across",
   "number": 14,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 6
   },
   "length": 9,
   "clue": "Country carrying paper bouquet (9)",
   "separatorLocations": {},
   "solution": "FRAGRANCE",
   "annotation": null
  },
  {
   "id": "15-down",
   "number": 15,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 6
   },
   "length": 9,
   "clue": "Wilder race, by and large (9)",
   "separatorLocations": {},
   "solution": "GENERALLY",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 10,
    "y": 6
   },
   "length": 5,
   "clue": "No 1, Douglas Street? (5)",
   "separatorLocations": {},
   "solution": "FIRST",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 8
   },
   "length": 5,
   "clue": "Reportedly I spill the beans on the cake? (5)",
   "separatorLocations": {},
   "solution": "ICING",
   "annotation": null
  },
  {
   "id": "18-down",
   "number": 18,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 8
   },
   "length": 7,
   "clue": "Designer admits fashion finally is sound (7)",
   "separatorLocations": {},
   "solution": "CHANNEL",
   "annotation": null
  },
  {
   "id": "19-across",
   "number": 19,
   "direction": "across",
   "position": {
    "x": 6,
    "y": 8
   },
   "length": 9,
   "clue": "Wee! - rubbish clue (9)",
   "separatorLocations": {},
   "solution": "MINUSCULE",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 8
   },
   "length": 7,
   "clue": "Never smoked but still sick (7)",
   "separatorLocations": {},
   "solution": "UNCURED",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 8
   },
   "length": 7,
   "clue": "12 with a madness for captains (7)",
   "separatorLocations": {},
   "solution": "LEADERS",
   "annotation": null
  },
  {
   "id": "22-down",
   "number": 22,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 9
   },
   "length": 6,
   "clue": "Calling nurse to inject drug (6)",
   "separatorLocations": {},
   "solution": "CAREER",
   "annotation": null
  },
  {
   "id": "23-across",
   "number": 23,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 10
   },
   "length": 8,
   "clue": "Andrew and I get on — it's a match! (8)",
   "separatorLocations": {},
   "solution": "MARRIAGE",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 10
   },
   "length": 6,
   "clue": "Primarily, chimps, orang-utans, monkeys, macaques and suchlike found here? (6)",
   "separatorLocations": {},
   "solution": "COMMAS",
   "annotation": null
  },
  {
   "id": "25-down",
   "number": 25,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 10
   },
   "length": 5,
   "clue": "Second to right car (5)",
   "separatorLocations": {},
   "solution": "MOTOR",
   "annotation": null
  },
  {
   "id": "26-across",
   "number": 26,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 12
   },
   "length": 10,
   "clue": "Scruffy Uncle Fin, with hesitation, is a trendsetter (10)",
   "separatorLocations": {},
   "solution": "INFLUENCER",
   "annotation": null
  },
  {
   "id": "27-across",
   "number": 27,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 12
   },
   "length": 4,
   "clue": "Trio not right for you once (4)",
   "separatorLocations": {},
   "solution": "THEE",
   "annotation": null
  },
  {
   "id": "28-across",
   "number": 28,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 14
   },
   "length": 7,
   "clue": "Team for quiet films (7)",
   "separatorLocations": {},
   "solution": "PLAYERS",
   "annotation": null
  },
  {
   "id": "29-across",
   "number": 29,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 14
   },
   "length": 7,
   "clue": "Some salad dressing seen at 16 (7)",
   "separatorLocations": {},
   "solution": "ADDRESS",
   "annotation": null
  }
 ]
} /*JSON-END*/;
