// Generated by tools/fetch_puzzle.py — puzzle © its original publisher.
// Annotations (type/definition/indicators/blocks/walkthrough) are original
// to this project. Edit the annotation objects freely; keep the JSON markers.
window.CRYPTIC_PUZZLES = window.CRYPTIC_PUZZLES || {};
window.CRYPTIC_PUZZLES["quiptic-1128"] = /*JSON-START*/ {
 "id": "quiptic-1128",
 "number": 1128,
 "series": "quiptic",
 "name": "Quiptic crossword No 1,128",
 "setter": "Pan",
 "date": 1624838400000,
 "dimensions": {
  "cols": 15,
  "rows": 15
 },
 "sourceUrl": "https://www.theguardian.com/crosswords/quiptic/1128",
 "provenance": {
  "publisher": "Guardian",
  "series": "quiptic",
  "acquiredBy": "tools/fetch_puzzle.py",
  "acquiredOn": "2026-09-17",
  "retrievedFrom": "publisher",
  "retrievedUrl": null,
  "gridOrigin": "published",
  "solutionOrigin": "published"
 },
 "entries": [
  {
   "id": "1-down",
   "number": 1,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 0
   },
   "length": 4,
   "clue": "Transport initially included in price of holiday (4)",
   "separatorLocations": {},
   "solution": "FETE",
   "annotation": null
  },
  {
   "id": "2-down",
   "number": 2,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 0
   },
   "length": 8,
   "clue": "Piece of music at service primarily for common people (4-4)",
   "separatorLocations": {
    "-": [
     4
    ]
   },
   "solution": "RIFFRAFF",
   "annotation": null
  },
  {
   "id": "3-down",
   "number": 3,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 0
   },
   "length": 6,
   "clue": "Closure of zoo interrupting bear's routine (6)",
   "separatorLocations": {},
   "solution": "BORING",
   "annotation": null
  },
  {
   "id": "4-down",
   "number": 4,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 0
   },
   "length": 8,
   "clue": "Setter ingesting ecstasy and heroin got nasty bug (8)",
   "separatorLocations": {},
   "solution": "PATHOGEN",
   "annotation": null
  },
  {
   "id": "5-down",
   "number": 5,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 0
   },
   "length": 6,
   "clue": "End up having sleepover away from home (3,3)",
   "separatorLocations": {
    ",": [
     3
    ]
   },
   "solution": "PANOUT",
   "annotation": null
  },
  {
   "id": "6-down",
   "number": 6,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 0
   },
   "length": 4,
   "clue": "Covers for songs (4)",
   "separatorLocations": {},
   "solution": "LAYS",
   "annotation": null
  },
  {
   "id": "7-across",
   "number": 7,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 1
   },
   "length": 7,
   "clue": "Stone container with drug-free contents (7)",
   "separatorLocations": {},
   "solution": "PERIDOT",
   "annotation": null
  },
  {
   "id": "8-across",
   "number": 8,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 1
   },
   "length": 7,
   "clue": "Vehicles crossing America in convoy (7)",
   "separatorLocations": {},
   "solution": "CARAVAN",
   "annotation": null
  },
  {
   "id": "9-across",
   "number": 9,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 3
   },
   "length": 4,
   "clue": "Letter following complaint? (4)",
   "separatorLocations": {},
   "solution": "BEEF",
   "annotation": null
  },
  {
   "id": "10-across",
   "number": 10,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 3
   },
   "length": 9,
   "clue": "I soon chat freely, as part of a conspiracy (2,7)",
   "separatorLocations": {
    ",": [
     2
    ]
   },
   "solution": "INCAHOOTS",
   "annotation": null
  },
  {
   "id": "11-down",
   "number": 11,
   "direction": "down",
   "position": {
    "x": 7,
    "y": 3
   },
   "length": 9,
   "clue": "Conservative bishop entertained by old artist (9)",
   "separatorLocations": {},
   "solution": "CONSTABLE",
   "annotation": null
  },
  {
   "id": "12-across",
   "number": 12,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 5
   },
   "length": 5,
   "clue": "Priest called to road accident (5)",
   "separatorLocations": {},
   "solution": "PRANG",
   "annotation": null
  },
  {
   "id": "12-down",
   "number": 12,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 5
   },
   "length": 5,
   "clue": "Philosopher climbing old mountain outside Turkish capital (5)",
   "separatorLocations": {},
   "solution": "PLATO",
   "annotation": null
  },
  {
   "id": "13-across",
   "number": 13,
   "direction": "across",
   "position": {
    "x": 7,
    "y": 5
   },
   "length": 8,
   "clue": "Bird near foot of mast on vessel (8)",
   "separatorLocations": {},
   "solution": "NIGHTJAR",
   "annotation": null
  },
  {
   "id": "14-down",
   "number": 14,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 5
   },
   "length": 5,
   "clue": "Note found amongst burnt remains of US sect (5)",
   "separatorLocations": {},
   "solution": "AMISH",
   "annotation": null
  },
  {
   "id": "15-across",
   "number": 15,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 7
   },
   "length": 4,
   "clue": "Female supporter rejected as vulgar (4)",
   "separatorLocations": {},
   "solution": "NAFF",
   "annotation": null
  },
  {
   "id": "16-across",
   "number": 16,
   "direction": "across",
   "position": {
    "x": 5,
    "y": 7
   },
   "length": 5,
   "clue": "Limits of taboo stopping pleasure in bed (5)",
   "separatorLocations": {},
   "solution": "FUTON",
   "annotation": null
  },
  {
   "id": "16-down",
   "number": 16,
   "direction": "down",
   "position": {
    "x": 5,
    "y": 7
   },
   "length": 8,
   "clue": "Admirer and crook go to a dance (8)",
   "separatorLocations": {},
   "solution": "FANDANGO",
   "annotation": null
  },
  {
   "id": "17-across",
   "number": 17,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 7
   },
   "length": 4,
   "clue": "Ice originally put in china bucket (4)",
   "separatorLocations": {},
   "solution": "PAIL",
   "annotation": null
  },
  {
   "id": "17-down",
   "number": 17,
   "direction": "down",
   "position": {
    "x": 11,
    "y": 7
   },
   "length": 8,
   "clue": "River stopping quiet monster's advance (8)",
   "separatorLocations": {},
   "solution": "PROGRESS",
   "annotation": null
  },
  {
   "id": "18-across",
   "number": 18,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 9
   },
   "length": 8,
   "clue": "Hit cross back with handle (8)",
   "separatorLocations": {},
   "solution": "DOORKNOB",
   "annotation": null
  },
  {
   "id": "19-down",
   "number": 19,
   "direction": "down",
   "position": {
    "x": 3,
    "y": 9
   },
   "length": 6,
   "clue": "Radio broadcast by Elvis' first crew member? (6)",
   "separatorLocations": {},
   "solution": "ROADIE",
   "annotation": null
  },
  {
   "id": "20-across",
   "number": 20,
   "direction": "across",
   "position": {
    "x": 9,
    "y": 9
   },
   "length": 5,
   "clue": "Bamboo thatch covering market stall (5)",
   "separatorLocations": {},
   "solution": "BOOTH",
   "annotation": null
  },
  {
   "id": "20-down",
   "number": 20,
   "direction": "down",
   "position": {
    "x": 9,
    "y": 9
   },
   "length": 6,
   "clue": "Perfect hit to leg (4,2)",
   "separatorLocations": {
    ",": [
     4
    ]
   },
   "solution": "BANGON",
   "annotation": null
  },
  {
   "id": "21-across",
   "number": 21,
   "direction": "across",
   "position": {
    "x": 1,
    "y": 11
   },
   "length": 9,
   "clue": "A male line broken in battle (2,7)",
   "separatorLocations": {
    ",": [
     2
    ]
   },
   "solution": "ELALAMEIN",
   "annotation": null
  },
  {
   "id": "21-down",
   "number": 21,
   "direction": "down",
   "position": {
    "x": 1,
    "y": 11
   },
   "length": 4,
   "clue": "Censor woman with no husband (4)",
   "separatorLocations": {},
   "solution": "EDIT",
   "annotation": null
  },
  {
   "id": "22-across",
   "number": 22,
   "direction": "across",
   "position": {
    "x": 11,
    "y": 11
   },
   "length": 4,
   "clue": "Retired thespian ignoring head of casting's staffing schedule (4)",
   "separatorLocations": {},
   "solution": "ROTA",
   "annotation": null
  },
  {
   "id": "23-down",
   "number": 23,
   "direction": "down",
   "position": {
    "x": 13,
    "y": 11
   },
   "length": 4,
   "clue": "Net found twisted round foot of body in river (4)",
   "separatorLocations": {},
   "solution": "TYNE",
   "annotation": null
  },
  {
   "id": "24-across",
   "number": 24,
   "direction": "across",
   "position": {
    "x": 0,
    "y": 13
   },
   "length": 7,
   "clue": "Journalist finally in digs broadcast news (7)",
   "separatorLocations": {},
   "solution": "TIDINGS",
   "annotation": null
  },
  {
   "id": "25-across",
   "number": 25,
   "direction": "across",
   "position": {
    "x": 8,
    "y": 13
   },
   "length": 7,
   "clue": "Composer crossing heart on island (7)",
   "separatorLocations": {},
   "solution": "ROSSINI",
   "annotation": null
  }
 ]
} /*JSON-END*/;
